#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x5e862211, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x2f1cad0e, __VMLINUX_SYMBOL_STR(reset_shadow_zero_bits_mask) },
	{ 0x8b8a081e, __VMLINUX_SYMBOL_STR(alloc_pages_current) },
	{ 0xac9ce195, __VMLINUX_SYMBOL_STR(kvm_async_pf_task_wait) },
	{ 0x7e104a81, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xa7ca98c1, __VMLINUX_SYMBOL_STR(kvm_complete_insn_gp) },
	{ 0x2c2f5a09, __VMLINUX_SYMBOL_STR(x86_family) },
	{ 0x74c08941, __VMLINUX_SYMBOL_STR(kvm_async_pf_task_wake) },
	{ 0x6da70163, __VMLINUX_SYMBOL_STR(kvm_mmu_load) },
	{ 0x78abcf44, __VMLINUX_SYMBOL_STR(kvm_release_page_dirty) },
	{ 0xb5b3d126, __VMLINUX_SYMBOL_STR(kvm_require_dr) },
	{ 0x44046cb1, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_nested_vmexit_inject) },
	{ 0x616bf458, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0xf296d6aa, __VMLINUX_SYMBOL_STR(perf_event_release_kernel) },
	{ 0x93d53ab0, __VMLINUX_SYMBOL_STR(kvm_set_msr_common) },
	{ 0x77444060, __VMLINUX_SYMBOL_STR(kvm_mmu_invlpg) },
	{ 0xf6fd8f5c, __VMLINUX_SYMBOL_STR(kvm_vcpu_init) },
	{ 0x6b9bda7f, __VMLINUX_SYMBOL_STR(boot_cpu_data) },
	{ 0x6b93d705, __VMLINUX_SYMBOL_STR(kvm_emulate_cpuid) },
	{ 0xa4d57013, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_exit) },
	{ 0x804e9076, __VMLINUX_SYMBOL_STR(kvm_queue_exception_e) },
	{ 0x1ac0ce2, __VMLINUX_SYMBOL_STR(kvm_get_rflags) },
	{ 0x485cd7f6, __VMLINUX_SYMBOL_STR(kvm_rebooting) },
	{ 0xc0a3d105, __VMLINUX_SYMBOL_STR(find_next_bit) },
	{ 0xa320b11c, __VMLINUX_SYMBOL_STR(kvm_vcpu_on_spin) },
	{ 0x1f711b3, __VMLINUX_SYMBOL_STR(kvm_cpuid) },
	{ 0x819d1f3b, __VMLINUX_SYMBOL_STR(kvm_mmu_unload) },
	{ 0xd4617810, __VMLINUX_SYMBOL_STR(kvm_vcpu_read_guest) },
	{ 0x3422a941, __VMLINUX_SYMBOL_STR(__tracepoint_read_msr) },
	{ 0x603ff9a, __VMLINUX_SYMBOL_STR(kvm_mmu_reset_context) },
	{ 0x4c1c5b, __VMLINUX_SYMBOL_STR(do_trace_write_msr) },
	{ 0x3f7692b9, __VMLINUX_SYMBOL_STR(kvm_mmu_page_fault) },
	{ 0x4629334c, __VMLINUX_SYMBOL_STR(__preempt_count) },
	{ 0x7a2af7b4, __VMLINUX_SYMBOL_STR(cpu_number) },
	{ 0x21564cf4, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_nested_intercepts) },
	{ 0xd351dd79, __VMLINUX_SYMBOL_STR(kvm_get_dr) },
	{ 0x80be3ad, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_invlpga) },
	{ 0x6ecf5ebd, __VMLINUX_SYMBOL_STR(kvm_set_cr8) },
	{ 0xf7a777ea, __VMLINUX_SYMBOL_STR(kvm_set_cr0) },
	{ 0xdfab4d1c, __VMLINUX_SYMBOL_STR(kvm_get_cs_db_l_bits) },
	{ 0x56abe061, __VMLINUX_SYMBOL_STR(kvm_set_cr4) },
	{ 0xfe7c4287, __VMLINUX_SYMBOL_STR(nr_cpu_ids) },
	{ 0xc599bc18, __VMLINUX_SYMBOL_STR(kvm_max_tsc_scaling_ratio) },
	{ 0x751af884, __VMLINUX_SYMBOL_STR(kvm_mmu_unprotect_page_virt) },
	{ 0x4d52dcc8, __VMLINUX_SYMBOL_STR(kvm_vcpu_read_guest_page) },
	{ 0x59c1d110, __VMLINUX_SYMBOL_STR(__cpu_possible_mask) },
	{ 0x25b27ff4, __VMLINUX_SYMBOL_STR(load_pdptrs) },
	{ 0xc1adc2cb, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_skinit) },
	{ 0x9c91b47e, __VMLINUX_SYMBOL_STR(kvm_write_tsc) },
	{ 0xbcf9c794, __VMLINUX_SYMBOL_STR(current_task) },
	{ 0xd0459e67, __VMLINUX_SYMBOL_STR(kvm_has_tsc_control) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x709cd8cb, __VMLINUX_SYMBOL_STR(kvm_spurious_fault) },
	{ 0xadf7e47c, __VMLINUX_SYMBOL_STR(__cpu_online_mask) },
	{ 0x5fdfa2c1, __VMLINUX_SYMBOL_STR(amd_pmu_enable_virt) },
	{ 0x70f9719, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_msr) },
	{ 0x4c9d28b0, __VMLINUX_SYMBOL_STR(phys_base) },
	{ 0xbf6a78b1, __VMLINUX_SYMBOL_STR(kvm_emulate_hypercall) },
	{ 0xf3f948ef, __VMLINUX_SYMBOL_STR(kvm_set_dr) },
	{ 0x3e1f72e0, __VMLINUX_SYMBOL_STR(kvm_vcpu_cache) },
	{ 0x4a9f4d38, __VMLINUX_SYMBOL_STR(kvm_is_linear_rip) },
	{ 0x28722978, __VMLINUX_SYMBOL_STR(kvm_x86_ops) },
	{ 0x1014708f, __VMLINUX_SYMBOL_STR(kvm_get_cr8) },
	{ 0xe17f8bc8, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xf9be585d, __VMLINUX_SYMBOL_STR(kvm_set_cr3) },
	{ 0x8f734ce7, __VMLINUX_SYMBOL_STR(kvm_emulate_wbinvd) },
	{ 0x792f694e, __VMLINUX_SYMBOL_STR(kvm_before_handle_nmi) },
	{ 0xa0527cf3, __VMLINUX_SYMBOL_STR(kvm_scale_tsc) },
	{ 0xb1cc6be5, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_inj_virq) },
	{ 0x73ae496a, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_page_fault) },
	{ 0x7260e249, __VMLINUX_SYMBOL_STR(___preempt_schedule_notrace) },
	{ 0xf2f286c4, __VMLINUX_SYMBOL_STR(kvm_tsc_scaling_ratio_frac_bits) },
	{ 0xe8f8a409, __VMLINUX_SYMBOL_STR(kvm_set_rflags) },
	{ 0xd4adf8b, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_nested_intr_vmexit) },
	{ 0xd189bba9, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0x78764f4e, __VMLINUX_SYMBOL_STR(pv_irq_ops) },
	{ 0x79df5377, __VMLINUX_SYMBOL_STR(__free_pages) },
	{ 0x87e3ad23, __VMLINUX_SYMBOL_STR(kvm_vcpu_is_reset_bsp) },
	{ 0x6f75e3ea, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_write_tsc_offset) },
	{ 0x80892351, __VMLINUX_SYMBOL_STR(cpu_tlbstate) },
	{ 0x5b3d30e0, __VMLINUX_SYMBOL_STR(kvm_after_handle_nmi) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x5a237eec, __VMLINUX_SYMBOL_STR(kvm_queue_exception) },
	{ 0xc0cd3b13, __VMLINUX_SYMBOL_STR(___ratelimit) },
	{ 0x536c43c9, __VMLINUX_SYMBOL_STR(kvm_init_shadow_mmu) },
	{ 0x775a6ef5, __VMLINUX_SYMBOL_STR(kvm_read_and_reset_pf_reason) },
	{ 0x3d9ee9f0, __VMLINUX_SYMBOL_STR(clear_page) },
	{ 0x9ed60dc5, __VMLINUX_SYMBOL_STR(kvm_requeue_exception_e) },
	{ 0x245ccad5, __VMLINUX_SYMBOL_STR(pv_cpu_ops) },
	{ 0xaaf935, __VMLINUX_SYMBOL_STR(kvm_disable_tdp) },
	{ 0xf5d64d7c, __VMLINUX_SYMBOL_STR(x86_emulate_instruction) },
	{ 0x102833a6, __VMLINUX_SYMBOL_STR(kvm_vcpu_gfn_to_page) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0x8ce4f3ab, __VMLINUX_SYMBOL_STR(kvm_enable_tdp) },
	{ 0xc73a8771, __VMLINUX_SYMBOL_STR(do_trace_read_msr) },
	{ 0x589efc84, __VMLINUX_SYMBOL_STR(kvm_task_switch) },
	{ 0x3dc165ee, __VMLINUX_SYMBOL_STR(kvm_find_cpuid_entry) },
	{ 0xe69002d6, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x2846dd8a, __VMLINUX_SYMBOL_STR(perf_event_read_value) },
	{ 0xed433664, __VMLINUX_SYMBOL_STR(__per_cpu_offset) },
	{ 0x49c8d275, __VMLINUX_SYMBOL_STR(reprogram_gp_counter) },
	{ 0x8b2ffff3, __VMLINUX_SYMBOL_STR(kvm_set_xcr) },
	{ 0x7ff1ca84, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_nested_vmrun) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0x4df4a20d, __VMLINUX_SYMBOL_STR(kvm_emulate_halt) },
	{ 0x6340434e, __VMLINUX_SYMBOL_STR(x86_model) },
	{ 0xe118a92e, __VMLINUX_SYMBOL_STR(kvm_vcpu_uninit) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0xfa01ee8a, __VMLINUX_SYMBOL_STR(kvm_get_msr_common) },
	{ 0x8b97de6d, __VMLINUX_SYMBOL_STR(pv_mmu_ops) },
	{ 0x23d99842, __VMLINUX_SYMBOL_STR(kvm_fast_pio_out) },
	{ 0x317f9e6b, __VMLINUX_SYMBOL_STR(kvm_enable_efer_bits) },
	{ 0xf8f4642c, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_nested_vmexit) },
	{ 0xe129f9fb, __VMLINUX_SYMBOL_STR(kvm_set_msr) },
	{ 0x3ba7b6c6, __VMLINUX_SYMBOL_STR(kvm_init) },
	{ 0x27046576, __VMLINUX_SYMBOL_STR(kvm_exit) },
	{ 0x2d5eb7ce, __VMLINUX_SYMBOL_STR(kvm_requeue_exception) },
	{ 0x18582826, __VMLINUX_SYMBOL_STR(amd_pmu_disable_virt) },
	{ 0x827d55ef, __VMLINUX_SYMBOL_STR(kvm_rdpmc) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=kvm";

MODULE_ALIAS("cpu:type:x86,ven*fam*mod*:feature:*00C2*");
