#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x5e862211, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x7e104a81, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xf9a482f9, __VMLINUX_SYMBOL_STR(msleep) },
	{ 0x38c08dbd, __VMLINUX_SYMBOL_STR(snd_hda_codec_get_pin_target) },
	{ 0x349cba85, __VMLINUX_SYMBOL_STR(strchr) },
	{ 0xaadfc33f, __VMLINUX_SYMBOL_STR(snd_hda_multi_out_dig_prepare) },
	{ 0x375cacd5, __VMLINUX_SYMBOL_STR(snd_hda_input_mux_info) },
	{ 0x2b0cdda1, __VMLINUX_SYMBOL_STR(snd_hda_mixer_amp_volume_put) },
	{ 0xc4b33c76, __VMLINUX_SYMBOL_STR(snd_hdac_codec_read) },
	{ 0x9a8e1877, __VMLINUX_SYMBOL_STR(snd_array_free) },
	{ 0x5806a217, __VMLINUX_SYMBOL_STR(snd_hda_get_default_vref) },
	{ 0x64958c7d, __VMLINUX_SYMBOL_STR(snd_hda_enum_helper_info) },
	{ 0x30c174ef, __VMLINUX_SYMBOL_STR(snd_hda_apply_fixup) },
	{ 0xca53b5cd, __VMLINUX_SYMBOL_STR(snd_hda_sync_vmaster_hook) },
	{ 0x1600a531, __VMLINUX_SYMBOL_STR(snd_hda_codec_amp_stereo) },
	{ 0x7891635, __VMLINUX_SYMBOL_STR(__snd_hda_add_vmaster) },
	{ 0xbe7dd7dc, __VMLINUX_SYMBOL_STR(snd_array_new) },
	{ 0x33a88eb3, __VMLINUX_SYMBOL_STR(snd_hda_mixer_amp_tlv) },
	{ 0xabc1c037, __VMLINUX_SYMBOL_STR(snd_hda_jack_add_kctls) },
	{ 0xb5f05fbc, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x676f5ac, __VMLINUX_SYMBOL_STR(snd_hda_get_input_pin_attr) },
	{ 0x18a27a1c, __VMLINUX_SYMBOL_STR(snd_hda_check_amp_list_power) },
	{ 0x865c36f0, __VMLINUX_SYMBOL_STR(snd_hda_jack_unsol_event) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0xc499ae1e, __VMLINUX_SYMBOL_STR(kstrdup) },
	{ 0xe118de5d, __VMLINUX_SYMBOL_STR(snd_pcm_2_1_chmaps) },
	{ 0x521403ba, __VMLINUX_SYMBOL_STR(snd_hda_mixer_amp_switch_put) },
	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
	{ 0x7a61ab81, __VMLINUX_SYMBOL_STR(snd_hda_jack_detect_enable_callback) },
	{ 0xa9173f34, __VMLINUX_SYMBOL_STR(snd_hdac_check_power_state) },
	{ 0xf9c0b663, __VMLINUX_SYMBOL_STR(strlcat) },
	{ 0x24c80769, __VMLINUX_SYMBOL_STR(snd_hda_check_amp_caps) },
	{ 0xa311b266, __VMLINUX_SYMBOL_STR(snd_hda_mixer_amp_volume_get) },
	{ 0x4cdf4adf, __VMLINUX_SYMBOL_STR(snd_hdac_regmap_write_raw) },
	{ 0x11089ac7, __VMLINUX_SYMBOL_STR(_ctype) },
	{ 0x8dc44e03, __VMLINUX_SYMBOL_STR(_snd_hda_set_pin_ctl) },
	{ 0x98782fd0, __VMLINUX_SYMBOL_STR(dev_err) },
	{ 0x5e5acd5e, __VMLINUX_SYMBOL_STR(snd_hda_attach_beep_device) },
	{ 0x3d7149d9, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x366434d, __VMLINUX_SYMBOL_STR(snd_hda_codec_set_pin_target) },
	{ 0xda096c7d, __VMLINUX_SYMBOL_STR(snd_hda_mixer_amp_switch_get) },
	{ 0xc34ec8ad, __VMLINUX_SYMBOL_STR(snd_hda_get_conn_list) },
	{ 0xbb4ee510, __VMLINUX_SYMBOL_STR(snd_ctl_boolean_stereo_info) },
	{ 0x53efb74f, __VMLINUX_SYMBOL_STR(snd_hda_multi_out_analog_prepare) },
	{ 0xd5ffe08, __VMLINUX_SYMBOL_STR(snd_hda_multi_out_analog_cleanup) },
	{ 0x5792f848, __VMLINUX_SYMBOL_STR(strlcpy) },
	{ 0x1081a331, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x2b96b5fd, __VMLINUX_SYMBOL_STR(is_jack_detectable) },
	{ 0xb8a490e2, __VMLINUX_SYMBOL_STR(snd_hda_mixer_bind_switch_get) },
	{ 0x7b20b150, __VMLINUX_SYMBOL_STR(snd_hda_create_spdif_in_ctls) },
	{ 0x1fe555ce, __VMLINUX_SYMBOL_STR(snd_hda_codec_amp_init) },
	{ 0x8f3282f4, __VMLINUX_SYMBOL_STR(snd_hda_parse_pin_defcfg) },
	{ 0xe3a53f4c, __VMLINUX_SYMBOL_STR(sort) },
	{ 0x92cb7ab2, __VMLINUX_SYMBOL_STR(__hda_codec_driver_register) },
	{ 0x2e9bca16, __VMLINUX_SYMBOL_STR(snd_hda_get_int_hint) },
	{ 0x9ebddb2d, __VMLINUX_SYMBOL_STR(snd_hda_jack_detect_state) },
	{ 0x747aacef, __VMLINUX_SYMBOL_STR(snd_hda_jack_tbl_get) },
	{ 0x67b70b5c, __VMLINUX_SYMBOL_STR(snd_hda_find_mixer_ctl) },
	{ 0xb4e4fea0, __VMLINUX_SYMBOL_STR(snd_hda_create_spdif_share_sw) },
	{ 0x1c28065, __VMLINUX_SYMBOL_STR(snd_hda_get_bool_hint) },
	{ 0x37e78d2, __VMLINUX_SYMBOL_STR(snd_hda_multi_out_analog_open) },
	{ 0x586fc087, __VMLINUX_SYMBOL_STR(snd_hda_get_conn_index) },
	{ 0xf8a39c42, __VMLINUX_SYMBOL_STR(snd_hda_multi_out_dig_close) },
	{ 0xa470adba, __VMLINUX_SYMBOL_STR(snd_hda_create_dig_out_ctls) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0xf2f93a0a, __VMLINUX_SYMBOL_STR(_snd_hdac_read_parm) },
	{ 0x431a7154, __VMLINUX_SYMBOL_STR(snd_hda_correct_pin_ctl) },
	{ 0x1d01c029, __VMLINUX_SYMBOL_STR(snd_hda_add_imux_item) },
	{ 0x8a28f98, __VMLINUX_SYMBOL_STR(snd_hda_get_pin_label) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0xa1b87dca, __VMLINUX_SYMBOL_STR(snd_hda_multi_out_dig_cleanup) },
	{ 0xe69002d6, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x9948d78b, __VMLINUX_SYMBOL_STR(__dynamic_dev_dbg) },
	{ 0x3755ba07, __VMLINUX_SYMBOL_STR(snd_ctl_sync_vmaster) },
	{ 0xba387b39, __VMLINUX_SYMBOL_STR(__snd_hda_codec_cleanup_stream) },
	{ 0xeeee0ab6, __VMLINUX_SYMBOL_STR(snd_hda_codec_pcm_new) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0xa53c0c81, __VMLINUX_SYMBOL_STR(snd_hda_add_vmaster_hook) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x7baa537c, __VMLINUX_SYMBOL_STR(snd_hda_multi_out_dig_open) },
	{ 0x4ca9669f, __VMLINUX_SYMBOL_STR(scnprintf) },
	{ 0x7af215f6, __VMLINUX_SYMBOL_STR(snd_hdac_codec_write) },
	{ 0x74c134b9, __VMLINUX_SYMBOL_STR(__sw_hweight32) },
	{ 0x6f59dee1, __VMLINUX_SYMBOL_STR(snd_hda_codec_get_pincfg) },
	{ 0x8636f936, __VMLINUX_SYMBOL_STR(hda_codec_driver_unregister) },
	{ 0x38ced31, __VMLINUX_SYMBOL_STR(snd_hda_mixer_amp_switch_info) },
	{ 0x9b6d5e8a, __VMLINUX_SYMBOL_STR(snd_hda_codec_setup_stream) },
	{ 0x28318305, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0x30b9ff25, __VMLINUX_SYMBOL_STR(snd_hda_mixer_bind_switch_put) },
	{ 0xb0e602eb, __VMLINUX_SYMBOL_STR(memmove) },
	{ 0x7a94332a, __VMLINUX_SYMBOL_STR(snd_hda_mixer_amp_volume_info) },
	{ 0x5147a3a5, __VMLINUX_SYMBOL_STR(query_amp_caps) },
	{ 0x9e91de83, __VMLINUX_SYMBOL_STR(hda_get_autocfg_input_label) },
	{ 0xe37714c3, __VMLINUX_SYMBOL_STR(regcache_sync) },
	{ 0x7cc1f92c, __VMLINUX_SYMBOL_STR(snd_hda_set_vmaster_tlv) },
	{ 0xcf6f6b81, __VMLINUX_SYMBOL_STR(snd_hda_codec_amp_init_stereo) },
	{ 0x7a04983e, __VMLINUX_SYMBOL_STR(snd_hda_get_connections) },
	{ 0x7be2f997, __VMLINUX_SYMBOL_STR(snd_hda_add_new_ctls) },
	{ 0xe914e41e, __VMLINUX_SYMBOL_STR(strcpy) },
	{ 0x6d396d32, __VMLINUX_SYMBOL_STR(snd_hda_codec_amp_update) },
	{ 0x8dc4f53c, __VMLINUX_SYMBOL_STR(snd_hda_apply_verbs) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=snd-hda-codec,snd-hda-core,snd";

MODULE_ALIAS("hdaudio:v00000201r*a01*");
