#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

MODULE_INFO(staging, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x5e862211, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x1de72815, __VMLINUX_SYMBOL_STR(ptlrpc_lprocfs_unregister_obd) },
	{ 0x85135801, __VMLINUX_SYMBOL_STR(RMF_DLM_LVB) },
	{ 0x9aa527e4, __VMLINUX_SYMBOL_STR(lprocfs_rd_conn_uuid) },
	{ 0x2ca92fa8, __VMLINUX_SYMBOL_STR(ldlm_lock_decref) },
	{ 0x7e104a81, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xdf701ae7, __VMLINUX_SYMBOL_STR(lustre_swab_fid2path) },
	{ 0xa6b9dee6, __VMLINUX_SYMBOL_STR(libcfs_kkuc_group_rem) },
	{ 0x4c3259a9, __VMLINUX_SYMBOL_STR(ptlrpc_req_finished) },
	{ 0xaf50a0d6, __VMLINUX_SYMBOL_STR(RMF_HSM_STATE_SET) },
	{ 0xfc87cfc1, __VMLINUX_SYMBOL_STR(class_exp2obd) },
	{ 0x138be331, __VMLINUX_SYMBOL_STR(up_read) },
	{ 0xdae80100, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0x1ad6c330, __VMLINUX_SYMBOL_STR(RMF_EAVALS) },
	{ 0x3386efc1, __VMLINUX_SYMBOL_STR(single_open) },
	{ 0x7aa1756e, __VMLINUX_SYMBOL_STR(kvfree) },
	{ 0x301d4fcd, __VMLINUX_SYMBOL_STR(RQF_MDS_READPAGE) },
	{ 0x754d539c, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0x9798f2f1, __VMLINUX_SYMBOL_STR(RQF_MDS_GETATTR) },
	{ 0x653723dc, __VMLINUX_SYMBOL_STR(RMF_LOGCOOKIES) },
	{ 0x37fe4f20, __VMLINUX_SYMBOL_STR(lprocfs_rd_state) },
	{ 0x7417be7e, __VMLINUX_SYMBOL_STR(lprocfs_rd_connect_flags) },
	{ 0x25d0b3f9, __VMLINUX_SYMBOL_STR(ldlm_cli_enqueue_fini) },
	{ 0x9a258886, __VMLINUX_SYMBOL_STR(RQF_MDS_GETSTATUS) },
	{ 0x5ec3284d, __VMLINUX_SYMBOL_STR(RQF_MDS_HSM_CT_UNREGISTER) },
	{ 0xb61cb95a, __VMLINUX_SYMBOL_STR(RQF_MDS_GETXATTR) },
	{ 0xd95039, __VMLINUX_SYMBOL_STR(ptlrpcd_decref) },
	{ 0xbf57a58e, __VMLINUX_SYMBOL_STR(req_capsule_get_size) },
	{ 0xc2be922a, __VMLINUX_SYMBOL_STR(RMF_SYMTGT) },
	{ 0x19f462ab, __VMLINUX_SYMBOL_STR(kfree_call_rcu) },
	{ 0xdae6d4c5, __VMLINUX_SYMBOL_STR(client_connect_import) },
	{ 0xde12d36b, __VMLINUX_SYMBOL_STR(RMF_MDS_HSM_ARCHIVE) },
	{ 0x71f662a3, __VMLINUX_SYMBOL_STR(libcfs_debug) },
	{ 0x39f00a43, __VMLINUX_SYMBOL_STR(ptlrpc_recover_import) },
	{ 0x8526c35a, __VMLINUX_SYMBOL_STR(remove_wait_queue) },
	{ 0x9cfa9282, __VMLINUX_SYMBOL_STR(llog_init_handle) },
	{ 0xdf2789c0, __VMLINUX_SYMBOL_STR(cfs_curproc_cap_pack) },
	{ 0x1efc4112, __VMLINUX_SYMBOL_STR(do_set_info_async) },
	{ 0x69c9f04d, __VMLINUX_SYMBOL_STR(RQF_MDS_REINT_LINK) },
	{ 0xd9561861, __VMLINUX_SYMBOL_STR(RQF_LDLM_INTENT_OPEN) },
	{ 0x696ba811, __VMLINUX_SYMBOL_STR(lustre_msg_get_type) },
	{ 0x6ff462f8, __VMLINUX_SYMBOL_STR(lprocfs_rd_server_uuid) },
	{ 0xd18ff07b, __VMLINUX_SYMBOL_STR(_debug_req) },
	{ 0xbf98b86f, __VMLINUX_SYMBOL_STR(RQF_MDS_QUOTACHECK) },
	{ 0xd3dae408, __VMLINUX_SYMBOL_STR(ldlm_it2str) },
	{ 0x375da51, __VMLINUX_SYMBOL_STR(class_import_put) },
	{ 0x3c1285bd, __VMLINUX_SYMBOL_STR(libcfs_subsystem_debug) },
	{ 0x837efb00, __VMLINUX_SYMBOL_STR(RMF_NAME) },
	{ 0x604e2505, __VMLINUX_SYMBOL_STR(RMF_SWAP_LAYOUTS) },
	{ 0x80ecb4e3, __VMLINUX_SYMBOL_STR(RMF_MDS_HSM_CURRENT_ACTION) },
	{ 0x1aa73125, __VMLINUX_SYMBOL_STR(llog_setup) },
	{ 0xb1bf0e, __VMLINUX_SYMBOL_STR(init_user_ns) },
	{ 0xd3aac0f8, __VMLINUX_SYMBOL_STR(sptlrpc_cli_unwrap_bulk_read) },
	{ 0xb5f05fbc, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x4b19c529, __VMLINUX_SYMBOL_STR(ldlm_resource_putref) },
	{ 0x3f034caf, __VMLINUX_SYMBOL_STR(lustre_msg_get_status) },
	{ 0x729718e6, __VMLINUX_SYMBOL_STR(llog_initiator_connect) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0x953e1b9e, __VMLINUX_SYMBOL_STR(ktime_get_real_seconds) },
	{ 0xec939a00, __VMLINUX_SYMBOL_STR(RQF_MDS_REINT_UNLINK) },
	{ 0x8e9ddd80, __VMLINUX_SYMBOL_STR(seq_read) },
	{ 0xa3130b0, __VMLINUX_SYMBOL_STR(RMF_MDT_EPOCH) },
	{ 0xe4f890ca, __VMLINUX_SYMBOL_STR(lprocfs_obd_cleanup) },
	{ 0x328dc2d8, __VMLINUX_SYMBOL_STR(ldlm_namespace_cleanup) },
	{ 0x14be8ca9, __VMLINUX_SYMBOL_STR(lprocfs_wr_ping) },
	{ 0x9bcf62c3, __VMLINUX_SYMBOL_STR(kthread_create_on_node) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0xd2e0d4eb, __VMLINUX_SYMBOL_STR(lustre_msg_get_opc) },
	{ 0x6f6dc736, __VMLINUX_SYMBOL_STR(lustre_swab_mdt_remote_perm) },
	{ 0x72e426bc, __VMLINUX_SYMBOL_STR(down_read) },
	{ 0xf7ba40c0, __VMLINUX_SYMBOL_STR(RMF_MDS_HSM_PROGRESS) },
	{ 0x7bbf8001, __VMLINUX_SYMBOL_STR(RMF_MDT_BODY) },
	{ 0xd33ac3fd, __VMLINUX_SYMBOL_STR(req_capsule_server_sized_get) },
	{ 0xf3f0bebf, __VMLINUX_SYMBOL_STR(ptlrpc_request_committed) },
	{ 0xdd28041a, __VMLINUX_SYMBOL_STR(ptlrpc_request_set_replen) },
	{ 0x876c2551, __VMLINUX_SYMBOL_STR(RMF_GETINFO_KEY) },
	{ 0x7d1ecd7f, __VMLINUX_SYMBOL_STR(RQF_LDLM_INTENT_LAYOUT) },
	{ 0x2663147a, __VMLINUX_SYMBOL_STR(__cfs_fail_timeout_set) },
	{ 0x9e88526, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0x4f8b5ddb, __VMLINUX_SYMBOL_STR(_copy_to_user) },
	{ 0xffd5a395, __VMLINUX_SYMBOL_STR(default_wake_function) },
	{ 0x3858fb94, __VMLINUX_SYMBOL_STR(RMF_OBD_STATFS) },
	{ 0xc362a099, __VMLINUX_SYMBOL_STR(ptlrpc_request_alloc_pack) },
	{ 0x35f7a504, __VMLINUX_SYMBOL_STR(lprocfs_single_release) },
	{ 0x3c80c06c, __VMLINUX_SYMBOL_STR(kstrtoull) },
	{ 0x5c7759ae, __VMLINUX_SYMBOL_STR(client_fid_fini) },
	{ 0x6ed20499, __VMLINUX_SYMBOL_STR(ldlm_revalidate_lock_handle) },
	{ 0x7c726423, __VMLINUX_SYMBOL_STR(ldlm_cli_cancel_unused_resource) },
	{ 0x6a95060d, __VMLINUX_SYMBOL_STR(client_disconnect_export) },
	{ 0x29d8b45c, __VMLINUX_SYMBOL_STR(lock_res_and_lock) },
	{ 0xdc99d135, __VMLINUX_SYMBOL_STR(ptlrpc_at_set_req_timeout) },
	{ 0x596582bf, __VMLINUX_SYMBOL_STR(RMF_GETINFO_VALLEN) },
	{ 0xbcf9c794, __VMLINUX_SYMBOL_STR(current_task) },
	{ 0x47f5e903, __VMLINUX_SYMBOL_STR(RMF_MDS_HSM_REQUEST) },
	{ 0x1be1a4c9, __VMLINUX_SYMBOL_STR(ldlm_cli_enqueue) },
	{ 0xe88a24f9, __VMLINUX_SYMBOL_STR(unlock_res_and_lock) },
	{ 0x41f344f4, __VMLINUX_SYMBOL_STR(ldlm_resource_iterate) },
	{ 0x3d7149d9, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0xcfa1e794, __VMLINUX_SYMBOL_STR(llog_cat_process) },
	{ 0xa5458dad, __VMLINUX_SYMBOL_STR(ldlm_lock_decref_and_cancel) },
	{ 0x1250c7e1, __VMLINUX_SYMBOL_STR(_raw_spin_trylock) },
	{ 0x449ad0a7, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0x901edad7, __VMLINUX_SYMBOL_STR(req_capsule_server_get) },
	{ 0x865483a9, __VMLINUX_SYMBOL_STR(libcfs_kvzalloc) },
	{ 0xdd30d7bf, __VMLINUX_SYMBOL_STR(RMF_ACL) },
	{ 0x5fc9a455, __VMLINUX_SYMBOL_STR(RMF_CLOSE_DATA) },
	{ 0x54ae5021, __VMLINUX_SYMBOL_STR(ldlm_lock_addref) },
	{ 0x9033fcb2, __VMLINUX_SYMBOL_STR(client_import_add_conn) },
	{ 0x15a3e4db, __VMLINUX_SYMBOL_STR(RMF_GETINFO_VAL) },
	{ 0xa7d55cc3, __VMLINUX_SYMBOL_STR(RQF_MDS_REINT_CREATE_RMT_ACL) },
	{ 0x6042bc15, __VMLINUX_SYMBOL_STR(RQF_MDS_REINT_RENAME) },
	{ 0x2c18da05, __VMLINUX_SYMBOL_STR(ldlm_lock_put) },
	{ 0x1081a331, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x8d28c73, __VMLINUX_SYMBOL_STR(sptlrpc_cli_enlarge_reqbuf) },
	{ 0xfd148bf8, __VMLINUX_SYMBOL_STR(RMF_LDLM_INTENT) },
	{ 0xc0867da7, __VMLINUX_SYMBOL_STR(RMF_REC_REINT) },
	{ 0x218a36ce, __VMLINUX_SYMBOL_STR(ldlm_cli_cancel) },
	{ 0xa2e13c6a, __VMLINUX_SYMBOL_STR(lprocfs_obd_setup) },
	{ 0x570d09ae, __VMLINUX_SYMBOL_STR(lustre_swab_lu_fid) },
	{ 0xd7bd4c01, __VMLINUX_SYMBOL_STR(sptlrpc_import_flush_my_ctx) },
	{ 0x8e9abe4d, __VMLINUX_SYMBOL_STR(RMF_GENERIC_DATA) },
	{ 0xf440bb38, __VMLINUX_SYMBOL_STR(libcfs_kkuc_group_foreach) },
	{ 0x2cde5e39, __VMLINUX_SYMBOL_STR(up_write) },
	{ 0x38d068f0, __VMLINUX_SYMBOL_STR(lprocfs_rd_import) },
	{ 0xbfb6ce61, __VMLINUX_SYMBOL_STR(down_write) },
	{ 0xf5a3c7ce, __VMLINUX_SYMBOL_STR(fput) },
	{ 0xea411f63, __VMLINUX_SYMBOL_STR(cfs_block_sigsinv) },
	{ 0x6141e842, __VMLINUX_SYMBOL_STR(llog_cat_close) },
	{ 0x13bc3ae7, __VMLINUX_SYMBOL_STR(class_exp2cliimp) },
	{ 0x850ba305, __VMLINUX_SYMBOL_STR(seq_client_alloc_fid) },
	{ 0x1f1076ad, __VMLINUX_SYMBOL_STR(llog_client_ops) },
	{ 0x43168488, __VMLINUX_SYMBOL_STR(RQF_MDS_RELEASE_CLOSE) },
	{ 0x6b48b70c, __VMLINUX_SYMBOL_STR(ptlrpc_request_alloc) },
	{ 0x8a873e70, __VMLINUX_SYMBOL_STR(lprocfs_rd_timeouts) },
	{ 0x3ca50f33, __VMLINUX_SYMBOL_STR(RQF_MDS_HSM_CT_REGISTER) },
	{ 0x4c3effbc, __VMLINUX_SYMBOL_STR(ptlrpcd_add_req) },
	{ 0x13be5989, __VMLINUX_SYMBOL_STR(module_put) },
	{ 0x219391ec, __VMLINUX_SYMBOL_STR(RMF_EAVALS_LENS) },
	{ 0x14a71c05, __VMLINUX_SYMBOL_STR(ldlm_cli_cancel_list) },
	{ 0x9bb5198b, __VMLINUX_SYMBOL_STR(RQF_MDS_CLOSE) },
	{ 0xa2244636, __VMLINUX_SYMBOL_STR(RQF_MDS_GETATTR_NAME) },
	{ 0x8f0aceac, __VMLINUX_SYMBOL_STR(RQF_MDS_HSM_ACTION) },
	{ 0xd9466673, __VMLINUX_SYMBOL_STR(class_process_proc_param) },
	{ 0x27955fd7, __VMLINUX_SYMBOL_STR(__ldlm_handle2lock) },
	{ 0x53411557, __VMLINUX_SYMBOL_STR(RMF_DLM_REP) },
	{ 0x59363e5b, __VMLINUX_SYMBOL_STR(sptlrpc_conf_client_adapt) },
	{ 0x8d4d264a, __VMLINUX_SYMBOL_STR(ptlrpc_prep_bulk_imp) },
	{ 0xa916b694, __VMLINUX_SYMBOL_STR(strnlen) },
	{ 0xa0711b70, __VMLINUX_SYMBOL_STR(client_obd_cleanup) },
	{ 0xe9816a1d, __VMLINUX_SYMBOL_STR(__ptlrpc_prep_bulk_page) },
	{ 0x4a99af72, __VMLINUX_SYMBOL_STR(cfs_clear_sigpending) },
	{ 0x44036eda, __VMLINUX_SYMBOL_STR(RQF_MDS_GET_INFO) },
	{ 0x555eb7fe, __VMLINUX_SYMBOL_STR(RQF_MDS_HSM_STATE_SET) },
	{ 0x7add44b5, __VMLINUX_SYMBOL_STR(posix_acl_valid) },
	{ 0xa1e7ad44, __VMLINUX_SYMBOL_STR(seq_client_flush) },
	{ 0x8a257736, __VMLINUX_SYMBOL_STR(RQF_MDS_HSM_STATE_GET) },
	{ 0x35e07b63, __VMLINUX_SYMBOL_STR(ptlrpc_set_import_active) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0xc559a634, __VMLINUX_SYMBOL_STR(RMF_LAYOUT_INTENT) },
	{ 0x3ef0d90c, __VMLINUX_SYMBOL_STR(libcfs_kkuc_group_put) },
	{ 0xd62c833f, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0x620bb96d, __VMLINUX_SYMBOL_STR(posix_acl_from_xattr) },
	{ 0x2e465e78, __VMLINUX_SYMBOL_STR(ldlm_lock_match) },
	{ 0x2a7afa06, __VMLINUX_SYMBOL_STR(llog_cleanup) },
	{ 0x8b8059bd, __VMLINUX_SYMBOL_STR(in_group_p) },
	{ 0xd05772d0, __VMLINUX_SYMBOL_STR(ldlm_cancel_resource_local) },
	{ 0x6b2dc060, __VMLINUX_SYMBOL_STR(dump_stack) },
	{ 0xdb53e8e8, __VMLINUX_SYMBOL_STR(ldlm_prep_elc_req) },
	{ 0x5e95b1cd, __VMLINUX_SYMBOL_STR(current_umask) },
	{ 0x649f0016, __VMLINUX_SYMBOL_STR(ptlrpc_obd_ping) },
	{ 0xdf7ab975, __VMLINUX_SYMBOL_STR(client_fid_init) },
	{ 0x111c80d4, __VMLINUX_SYMBOL_STR(client_obd_setup) },
	{ 0xffe29c3f, __VMLINUX_SYMBOL_STR(RQF_LDLM_ENQUEUE) },
	{ 0xeca2ae2a, __VMLINUX_SYMBOL_STR(ldlm_completion_ast) },
	{ 0x3ecf2902, __VMLINUX_SYMBOL_STR(wake_up_process) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0x3af463cd, __VMLINUX_SYMBOL_STR(ptlrpc_invalidate_import) },
	{ 0xe69002d6, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xe259ae9e, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x8e836b37, __VMLINUX_SYMBOL_STR(libcfs_kkuc_msg_put) },
	{ 0x4e71d5bc, __VMLINUX_SYMBOL_STR(req_capsule_shrink) },
	{ 0xa6bbd805, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0x61646e1b, __VMLINUX_SYMBOL_STR(RQF_MDS_SWAP_LAYOUTS) },
	{ 0x3e19f06d, __VMLINUX_SYMBOL_STR(__llog_ctxt_put) },
	{ 0x6fcb7042, __VMLINUX_SYMBOL_STR(lprocfs_counter_add) },
	{ 0xc9fef317, __VMLINUX_SYMBOL_STR(add_wait_queue) },
	{ 0x8bf44218, __VMLINUX_SYMBOL_STR(class_import_get) },
	{ 0x723b74aa, __VMLINUX_SYMBOL_STR(seq_lseek) },
	{ 0xbf7a37f1, __VMLINUX_SYMBOL_STR(cfs_signal_pending) },
	{ 0xcf61bacb, __VMLINUX_SYMBOL_STR(__cfs_fail_check_set) },
	{ 0x1a9b76aa, __VMLINUX_SYMBOL_STR(RMF_OBD_QUOTACTL) },
	{ 0xe2f91ce3, __VMLINUX_SYMBOL_STR(libcfs_debug_msg) },
	{ 0xcae54a58, __VMLINUX_SYMBOL_STR(ptlrpc_request_addref) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0xc7ca8257, __VMLINUX_SYMBOL_STR(RQF_MDS_REINT_SETATTR) },
	{ 0x4a5a2416, __VMLINUX_SYMBOL_STR(RMF_DLM_REQ) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x76bba669, __VMLINUX_SYMBOL_STR(client_import_del_conn) },
	{ 0x62aaae3f, __VMLINUX_SYMBOL_STR(RQF_MDS_HSM_REQUEST) },
	{ 0x269554ce, __VMLINUX_SYMBOL_STR(RQF_LDLM_INTENT_GETATTR) },
	{ 0x89f9edf7, __VMLINUX_SYMBOL_STR(RQF_MDS_REINT_SETXATTR) },
	{ 0x52b9c7e9, __VMLINUX_SYMBOL_STR(lbug_with_loc) },
	{ 0x96756ad8, __VMLINUX_SYMBOL_STR(req_capsule_has_field) },
	{ 0x9e420643, __VMLINUX_SYMBOL_STR(cfs_restore_sigs) },
	{ 0x56dc60a7, __VMLINUX_SYMBOL_STR(sptlrpc_lprocfs_cliobd_attach) },
	{ 0xfb50d4da, __VMLINUX_SYMBOL_STR(ptlrpc_queue_wait) },
	{ 0xa9704f80, __VMLINUX_SYMBOL_STR(lustre_msg_get_last_committed) },
	{ 0xf3cfbc08, __VMLINUX_SYMBOL_STR(ptlrpc_request_free) },
	{ 0xcb99c1, __VMLINUX_SYMBOL_STR(RQF_LDLM_INTENT_GETXATTR) },
	{ 0xbcacb5d, __VMLINUX_SYMBOL_STR(RMF_MDS_HSM_USER_ITEM) },
	{ 0x97a1f2d2, __VMLINUX_SYMBOL_STR(fget) },
	{ 0xea3c823d, __VMLINUX_SYMBOL_STR(client_destroy_import) },
	{ 0x1ee9eb3c, __VMLINUX_SYMBOL_STR(RQF_MDS_QUOTACTL) },
	{ 0x7fda989d, __VMLINUX_SYMBOL_STR(cfs_fail_loc) },
	{ 0x863db6eb, __VMLINUX_SYMBOL_STR(RMF_HSM_USER_STATE) },
	{ 0x30b437f0, __VMLINUX_SYMBOL_STR(req_capsule_client_get) },
	{ 0x287aac9e, __VMLINUX_SYMBOL_STR(llog_open) },
	{ 0x2e4ca396, __VMLINUX_SYMBOL_STR(RQF_LDLM_INTENT_UNLINK) },
	{ 0xe7512278, __VMLINUX_SYMBOL_STR(ptlrpcd_addref) },
	{ 0x3f752e78, __VMLINUX_SYMBOL_STR(RQF_MDS_STATFS) },
	{ 0x4070d4dc, __VMLINUX_SYMBOL_STR(class_register_type) },
	{ 0xaf4e9658, __VMLINUX_SYMBOL_STR(RQF_MDS_SYNC) },
	{ 0x60f49e22, __VMLINUX_SYMBOL_STR(req_capsule_set_size) },
	{ 0x10984cbf, __VMLINUX_SYMBOL_STR(_ldlm_lock_debug) },
	{ 0xd7bc8654, __VMLINUX_SYMBOL_STR(obd_timeout) },
	{ 0xf1704f34, __VMLINUX_SYMBOL_STR(lprocfs_wr_pinger_recov) },
	{ 0xb7b38189, __VMLINUX_SYMBOL_STR(RMF_MDT_MD) },
	{ 0x6a3785c9, __VMLINUX_SYMBOL_STR(RMF_EADATA) },
	{ 0xd8f06300, __VMLINUX_SYMBOL_STR(RQF_MDS_HSM_PROGRESS) },
	{ 0xb7fbd065, __VMLINUX_SYMBOL_STR(req_capsule_server_swab_get) },
	{ 0xd69e0a27, __VMLINUX_SYMBOL_STR(RQF_MDS_IS_SUBDIR) },
	{ 0xd799214f, __VMLINUX_SYMBOL_STR(ptlrpc_lprocfs_register_obd) },
	{ 0x419d3f61, __VMLINUX_SYMBOL_STR(try_module_get) },
	{ 0x17425446, __VMLINUX_SYMBOL_STR(lprocfs_wr_import) },
	{ 0x79d6973e, __VMLINUX_SYMBOL_STR(ldlm_resource_get) },
	{ 0x97ecf3a9, __VMLINUX_SYMBOL_STR(lprocfs_rd_pinger_recov) },
	{ 0x278d9d17, __VMLINUX_SYMBOL_STR(ldlm_prep_enqueue_req) },
	{ 0x742559b1, __VMLINUX_SYMBOL_STR(class_unregister_type) },
	{ 0xb6aafd03, __VMLINUX_SYMBOL_STR(RQF_MDS_DONE_WRITING) },
	{ 0x6c804bb7, __VMLINUX_SYMBOL_STR(ptlrpc_request_pack) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=ptlrpc,obdclass,libcfs,fid";

