#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

MODULE_INFO(staging, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x5e862211, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x8b8a081e, __VMLINUX_SYMBOL_STR(alloc_pages_current) },
	{ 0x9c2c2519, __VMLINUX_SYMBOL_STR(class_config_llog_handler) },
	{ 0x85135801, __VMLINUX_SYMBOL_STR(RMF_DLM_LVB) },
	{ 0x9aa527e4, __VMLINUX_SYMBOL_STR(lprocfs_rd_conn_uuid) },
	{ 0x2ca92fa8, __VMLINUX_SYMBOL_STR(ldlm_lock_decref) },
	{ 0x7e104a81, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x4c3259a9, __VMLINUX_SYMBOL_STR(ptlrpc_req_finished) },
	{ 0x138be331, __VMLINUX_SYMBOL_STR(up_read) },
	{ 0xdae80100, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0x3386efc1, __VMLINUX_SYMBOL_STR(single_open) },
	{ 0x754d539c, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0x37fe4f20, __VMLINUX_SYMBOL_STR(lprocfs_rd_state) },
	{ 0x7417be7e, __VMLINUX_SYMBOL_STR(lprocfs_rd_connect_flags) },
	{ 0xd95039, __VMLINUX_SYMBOL_STR(ptlrpcd_decref) },
	{ 0xf43540b9, __VMLINUX_SYMBOL_STR(lustre_swab_mgs_nidtbl_entry) },
	{ 0xdae6d4c5, __VMLINUX_SYMBOL_STR(client_connect_import) },
	{ 0x71f662a3, __VMLINUX_SYMBOL_STR(libcfs_debug) },
	{ 0x8526c35a, __VMLINUX_SYMBOL_STR(remove_wait_queue) },
	{ 0x6ff462f8, __VMLINUX_SYMBOL_STR(lprocfs_rd_server_uuid) },
	{ 0x3c1285bd, __VMLINUX_SYMBOL_STR(libcfs_subsystem_debug) },
	{ 0x802bde1c, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0x1aa73125, __VMLINUX_SYMBOL_STR(llog_setup) },
	{ 0xc0cdf55e, __VMLINUX_SYMBOL_STR(RMF_MGS_SEND_PARAM) },
	{ 0x5dbe6542, __VMLINUX_SYMBOL_STR(client_import_find_conn) },
	{ 0xd3aac0f8, __VMLINUX_SYMBOL_STR(sptlrpc_cli_unwrap_bulk_read) },
	{ 0x24aafdba, __VMLINUX_SYMBOL_STR(RMF_MGS_TARGET_INFO) },
	{ 0xb5f05fbc, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x69c42114, __VMLINUX_SYMBOL_STR(at_min) },
	{ 0x50048ed1, __VMLINUX_SYMBOL_STR(class_name2obd) },
	{ 0x729718e6, __VMLINUX_SYMBOL_STR(llog_initiator_connect) },
	{ 0x7e93080c, __VMLINUX_SYMBOL_STR(libcfs_nid2str_r) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0xfd68d17a, __VMLINUX_SYMBOL_STR(class_notify_sptlrpc_conf) },
	{ 0x8e9ddd80, __VMLINUX_SYMBOL_STR(seq_read) },
	{ 0xdfa11974, __VMLINUX_SYMBOL_STR(class_export_get) },
	{ 0xe4f890ca, __VMLINUX_SYMBOL_STR(lprocfs_obd_cleanup) },
	{ 0x328dc2d8, __VMLINUX_SYMBOL_STR(ldlm_namespace_cleanup) },
	{ 0x14be8ca9, __VMLINUX_SYMBOL_STR(lprocfs_wr_ping) },
	{ 0x9bcf62c3, __VMLINUX_SYMBOL_STR(kthread_create_on_node) },
	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
	{ 0x72e426bc, __VMLINUX_SYMBOL_STR(down_read) },
	{ 0xdd28041a, __VMLINUX_SYMBOL_STR(ptlrpc_request_set_replen) },
	{ 0x2663147a, __VMLINUX_SYMBOL_STR(__cfs_fail_timeout_set) },
	{ 0x9878745c, __VMLINUX_SYMBOL_STR(_atomic_dec_and_lock) },
	{ 0x9e88526, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0xffd5a395, __VMLINUX_SYMBOL_STR(default_wake_function) },
	{ 0x64ab0e98, __VMLINUX_SYMBOL_STR(wait_for_completion) },
	{ 0x8fbd8d9e, __VMLINUX_SYMBOL_STR(ldlm_lock2handle) },
	{ 0xff02a0e9, __VMLINUX_SYMBOL_STR(ldlm_lock_set_data) },
	{ 0xc362a099, __VMLINUX_SYMBOL_STR(ptlrpc_request_alloc_pack) },
	{ 0x35f7a504, __VMLINUX_SYMBOL_STR(lprocfs_single_release) },
	{ 0x6a95060d, __VMLINUX_SYMBOL_STR(client_disconnect_export) },
	{ 0xbcf9c794, __VMLINUX_SYMBOL_STR(current_task) },
	{ 0xdee87192, __VMLINUX_SYMBOL_STR(sptlrpc_conf_log_update_begin) },
	{ 0x1be1a4c9, __VMLINUX_SYMBOL_STR(ldlm_cli_enqueue) },
	{ 0x3d7149d9, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x449ad0a7, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0x901edad7, __VMLINUX_SYMBOL_STR(req_capsule_server_get) },
	{ 0xdd0ffb04, __VMLINUX_SYMBOL_STR(sptlrpc_flavor2name) },
	{ 0x9033fcb2, __VMLINUX_SYMBOL_STR(client_import_add_conn) },
	{ 0x2d56f168, __VMLINUX_SYMBOL_STR(ptlrpc_pinger_ir_up) },
	{ 0x5792f848, __VMLINUX_SYMBOL_STR(strlcpy) },
	{ 0x1081a331, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x7c3c559d, __VMLINUX_SYMBOL_STR(class_config_parse_llog) },
	{ 0xf45085e1, __VMLINUX_SYMBOL_STR(sptlrpc_conf_log_stop) },
	{ 0x218a36ce, __VMLINUX_SYMBOL_STR(ldlm_cli_cancel) },
	{ 0xa2e13c6a, __VMLINUX_SYMBOL_STR(lprocfs_obd_setup) },
	{ 0x6efa82b0, __VMLINUX_SYMBOL_STR(RQF_MGS_TARGET_REG) },
	{ 0x2cde5e39, __VMLINUX_SYMBOL_STR(up_write) },
	{ 0x38d068f0, __VMLINUX_SYMBOL_STR(lprocfs_rd_import) },
	{ 0xbfb6ce61, __VMLINUX_SYMBOL_STR(down_write) },
	{ 0xea411f63, __VMLINUX_SYMBOL_STR(cfs_block_sigsinv) },
	{ 0x13bc3ae7, __VMLINUX_SYMBOL_STR(class_exp2cliimp) },
	{ 0xf55c033b, __VMLINUX_SYMBOL_STR(RMF_MGS_CONFIG_BODY) },
	{ 0xc763fabc, __VMLINUX_SYMBOL_STR(sptlrpc_process_config) },
	{ 0x1f1076ad, __VMLINUX_SYMBOL_STR(llog_client_ops) },
	{ 0x6b48b70c, __VMLINUX_SYMBOL_STR(ptlrpc_request_alloc) },
	{ 0x9f984513, __VMLINUX_SYMBOL_STR(strrchr) },
	{ 0x79df5377, __VMLINUX_SYMBOL_STR(__free_pages) },
	{ 0x8d4d264a, __VMLINUX_SYMBOL_STR(ptlrpc_prep_bulk_imp) },
	{ 0xb512ebc2, __VMLINUX_SYMBOL_STR(sptlrpc_parse_flavor) },
	{ 0xa0711b70, __VMLINUX_SYMBOL_STR(client_obd_cleanup) },
	{ 0xe9816a1d, __VMLINUX_SYMBOL_STR(__ptlrpc_prep_bulk_page) },
	{ 0x4a99af72, __VMLINUX_SYMBOL_STR(cfs_clear_sigpending) },
	{ 0x44839bbb, __VMLINUX_SYMBOL_STR(cfs_rand) },
	{ 0x2d798316, __VMLINUX_SYMBOL_STR(RMF_MGS_CONFIG_RES) },
	{ 0x831f656c, __VMLINUX_SYMBOL_STR(class_process_config) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0xb7192323, __VMLINUX_SYMBOL_STR(ptlrpc_reconnect_import) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0xd62c833f, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0xade657cc, __VMLINUX_SYMBOL_STR(libcfs_next_nidstring) },
	{ 0x2a7afa06, __VMLINUX_SYMBOL_STR(llog_cleanup) },
	{ 0x7b4fc57b, __VMLINUX_SYMBOL_STR(at_max) },
	{ 0xfb1d0efa, __VMLINUX_SYMBOL_STR(lu_env_fini) },
	{ 0x111c80d4, __VMLINUX_SYMBOL_STR(client_obd_setup) },
	{ 0xffe29c3f, __VMLINUX_SYMBOL_STR(RQF_LDLM_ENQUEUE) },
	{ 0x26f99d16, __VMLINUX_SYMBOL_STR(RQF_MGS_CONFIG_READ) },
	{ 0xeca2ae2a, __VMLINUX_SYMBOL_STR(ldlm_completion_ast) },
	{ 0x3ecf2902, __VMLINUX_SYMBOL_STR(wake_up_process) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0x3af463cd, __VMLINUX_SYMBOL_STR(ptlrpc_invalidate_import) },
	{ 0xe69002d6, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xe259ae9e, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0xa6bbd805, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0x3e19f06d, __VMLINUX_SYMBOL_STR(__llog_ctxt_put) },
	{ 0xc2b1af57, __VMLINUX_SYMBOL_STR(RQF_MGS_SET_INFO) },
	{ 0xc9fef317, __VMLINUX_SYMBOL_STR(add_wait_queue) },
	{ 0x723b74aa, __VMLINUX_SYMBOL_STR(seq_lseek) },
	{ 0xbf7a37f1, __VMLINUX_SYMBOL_STR(cfs_signal_pending) },
	{ 0xe2f91ce3, __VMLINUX_SYMBOL_STR(libcfs_debug_msg) },
	{ 0x6d72828c, __VMLINUX_SYMBOL_STR(sptlrpc_conf_log_update_end) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x76bba669, __VMLINUX_SYMBOL_STR(client_import_del_conn) },
	{ 0x9e420643, __VMLINUX_SYMBOL_STR(cfs_restore_sigs) },
	{ 0x56dc60a7, __VMLINUX_SYMBOL_STR(sptlrpc_lprocfs_cliobd_attach) },
	{ 0x52b9c7e9, __VMLINUX_SYMBOL_STR(lbug_with_loc) },
	{ 0xfb50d4da, __VMLINUX_SYMBOL_STR(ptlrpc_queue_wait) },
	{ 0x300c2dd5, __VMLINUX_SYMBOL_STR(lu_env_init) },
	{ 0xea3c823d, __VMLINUX_SYMBOL_STR(client_destroy_import) },
	{ 0x7fda989d, __VMLINUX_SYMBOL_STR(cfs_fail_loc) },
	{ 0x30b437f0, __VMLINUX_SYMBOL_STR(req_capsule_client_get) },
	{ 0xe7512278, __VMLINUX_SYMBOL_STR(ptlrpcd_addref) },
	{ 0x4070d4dc, __VMLINUX_SYMBOL_STR(class_register_type) },
	{ 0x60f49e22, __VMLINUX_SYMBOL_STR(req_capsule_set_size) },
	{ 0xb2d5a552, __VMLINUX_SYMBOL_STR(complete) },
	{ 0x28318305, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0xf596e9ae, __VMLINUX_SYMBOL_STR(sptlrpc_conf_log_start) },
	{ 0x10984cbf, __VMLINUX_SYMBOL_STR(_ldlm_lock_debug) },
	{ 0xd7bc8654, __VMLINUX_SYMBOL_STR(obd_timeout) },
	{ 0xf490d5f9, __VMLINUX_SYMBOL_STR(class_del_profiles) },
	{ 0xc508760e, __VMLINUX_SYMBOL_STR(class_export_put) },
	{ 0xca5a81ec, __VMLINUX_SYMBOL_STR(ptlrpc_pinger_ir_down) },
	{ 0x742559b1, __VMLINUX_SYMBOL_STR(class_unregister_type) },
	{ 0xe914e41e, __VMLINUX_SYMBOL_STR(strcpy) },
	{ 0x6c804bb7, __VMLINUX_SYMBOL_STR(ptlrpc_request_pack) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=obdclass,ptlrpc,libcfs,lnet";

