#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x5e862211, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xae405b5f, __VMLINUX_SYMBOL_STR(kmem_cache_destroy) },
	{ 0x7e104a81, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x1a08b98d, __VMLINUX_SYMBOL_STR(scsi_change_queue_depth) },
	{ 0x75f74986, __VMLINUX_SYMBOL_STR(iscsi_host_remove) },
	{ 0x616bf458, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0x429461f0, __VMLINUX_SYMBOL_STR(ib_fmr_pool_map_phys) },
	{ 0xd49308c5, __VMLINUX_SYMBOL_STR(ib_dealloc_pd) },
	{ 0x43a53735, __VMLINUX_SYMBOL_STR(__alloc_workqueue_key) },
	{ 0xd4047ee0, __VMLINUX_SYMBOL_STR(iscsi_queuecommand) },
	{ 0xf6d569e7, __VMLINUX_SYMBOL_STR(iscsi_conn_stop) },
	{ 0x3fec048f, __VMLINUX_SYMBOL_STR(sg_next) },
	{ 0xd5a7c003, __VMLINUX_SYMBOL_STR(iscsi_eh_recover_target) },
	{ 0x9f2af072, __VMLINUX_SYMBOL_STR(iscsi_unregister_transport) },
	{ 0xbf8c9136, __VMLINUX_SYMBOL_STR(iscsi_conn_get_addr_param) },
	{ 0x363f38eb, __VMLINUX_SYMBOL_STR(iscsi_session_teardown) },
	{ 0x491e3b4, __VMLINUX_SYMBOL_STR(rdma_destroy_id) },
	{ 0xf6e679b, __VMLINUX_SYMBOL_STR(param_ops_bool) },
	{ 0x76ddf1d9, __VMLINUX_SYMBOL_STR(ib_free_cq) },
	{ 0xb5f05fbc, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x86836355, __VMLINUX_SYMBOL_STR(iscsi_host_add) },
	{ 0xc32b59ff, __VMLINUX_SYMBOL_STR(ib_destroy_fmr_pool) },
	{ 0x4629334c, __VMLINUX_SYMBOL_STR(__preempt_count) },
	{ 0x24d2b40e, __VMLINUX_SYMBOL_STR(blk_queue_virt_boundary) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0x78ea4261, __VMLINUX_SYMBOL_STR(iscsi_host_alloc) },
	{ 0xe5840ec6, __VMLINUX_SYMBOL_STR(ib_wc_status_msg) },
	{ 0xb4eff19b, __VMLINUX_SYMBOL_STR(iscsi_lookup_endpoint) },
	{ 0xf6399282, __VMLINUX_SYMBOL_STR(rdma_connect) },
	{ 0xa7accb41, __VMLINUX_SYMBOL_STR(iscsi_itt_to_ctask) },
	{ 0x9e88526, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0x504757c5, __VMLINUX_SYMBOL_STR(ib_alloc_mr) },
	{ 0x64ab0e98, __VMLINUX_SYMBOL_STR(wait_for_completion) },
	{ 0x90652e96, __VMLINUX_SYMBOL_STR(scsi_is_host_device) },
	{ 0x758c31bf, __VMLINUX_SYMBOL_STR(ib_alloc_pd) },
	{ 0x1916e38c, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0xca0cf245, __VMLINUX_SYMBOL_STR(ib_get_dma_mr) },
	{ 0x3d7149d9, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x4a826ddc, __VMLINUX_SYMBOL_STR(iscsi_conn_start) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x20c55ae0, __VMLINUX_SYMBOL_STR(sscanf) },
	{ 0xadf7e47c, __VMLINUX_SYMBOL_STR(__cpu_online_mask) },
	{ 0xf0d9a0ae, __VMLINUX_SYMBOL_STR(ib_check_mr_status) },
	{ 0xf50760b5, __VMLINUX_SYMBOL_STR(rdma_destroy_qp) },
	{ 0x15204dac, __VMLINUX_SYMBOL_STR(iscsi_conn_send_pdu) },
	{ 0xaa88e751, __VMLINUX_SYMBOL_STR(iscsi_session_get_param) },
	{ 0x4c9d28b0, __VMLINUX_SYMBOL_STR(phys_base) },
	{ 0xdc41b5b5, __VMLINUX_SYMBOL_STR(iscsi_host_set_param) },
	{ 0x7d96cea3, __VMLINUX_SYMBOL_STR(wait_for_completion_interruptible) },
	{ 0xf7fa6630, __VMLINUX_SYMBOL_STR(iscsi_conn_teardown) },
	{ 0x41db3322, __VMLINUX_SYMBOL_STR(iscsi_put_task) },
	{ 0xafcc62b6, __VMLINUX_SYMBOL_STR(iscsi_host_free) },
	{ 0x90dd9dc6, __VMLINUX_SYMBOL_STR(iscsi_conn_get_param) },
	{ 0xe17f8bc8, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x1081a331, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x8c03d20c, __VMLINUX_SYMBOL_STR(destroy_workqueue) },
	{ 0x77728f6e, __VMLINUX_SYMBOL_STR(iscsi_destroy_endpoint) },
	{ 0x28af6928, __VMLINUX_SYMBOL_STR(init_net) },
	{ 0x32145b9b, __VMLINUX_SYMBOL_STR(rdma_create_id) },
	{ 0xd4b8f8f1, __VMLINUX_SYMBOL_STR(ib_map_mr_sg) },
	{ 0xbff6ad4c, __VMLINUX_SYMBOL_STR(rdma_create_qp) },
	{ 0xbdd49557, __VMLINUX_SYMBOL_STR(iscsi_set_param) },
	{ 0xb3f1cdd6, __VMLINUX_SYMBOL_STR(ib_unregister_event_handler) },
	{ 0x99ac035e, __VMLINUX_SYMBOL_STR(rdma_resolve_route) },
	{ 0xd189bba9, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0x7175d383, __VMLINUX_SYMBOL_STR(ib_register_event_handler) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0xa202a8e5, __VMLINUX_SYMBOL_STR(kmalloc_order_trace) },
	{ 0x29062889, __VMLINUX_SYMBOL_STR(iscsi_register_transport) },
	{ 0x8ec42f92, __VMLINUX_SYMBOL_STR(iscsi_eh_device_reset) },
	{ 0x878cd015, __VMLINUX_SYMBOL_STR(wait_for_completion_interruptible_timeout) },
	{ 0x6cb9b920, __VMLINUX_SYMBOL_STR(iscsi_prep_data_out_pdu) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0x95febc17, __VMLINUX_SYMBOL_STR(rdma_disconnect) },
	{ 0xe69002d6, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xe6b87494, __VMLINUX_SYMBOL_STR(iscsi_complete_pdu) },
	{ 0x680ec266, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0x54d3743a, __VMLINUX_SYMBOL_STR(iscsi_conn_failure) },
	{ 0xd936c8f3, __VMLINUX_SYMBOL_STR(ib_query_qp) },
	{ 0x92234a23, __VMLINUX_SYMBOL_STR(kmem_cache_create) },
	{ 0x2853f133, __VMLINUX_SYMBOL_STR(ib_dereg_mr) },
	{ 0xcfa2a09f, __VMLINUX_SYMBOL_STR(ib_event_msg) },
	{ 0x52019b63, __VMLINUX_SYMBOL_STR(iscsi_suspend_queue) },
	{ 0x34f700d5, __VMLINUX_SYMBOL_STR(iscsi_create_endpoint) },
	{ 0x5c12e8a0, __VMLINUX_SYMBOL_STR(iscsi_eh_abort) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x4bcc28cf, __VMLINUX_SYMBOL_STR(ib_sg_to_pages) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x1072bc6f, __VMLINUX_SYMBOL_STR(ib_create_fmr_pool) },
	{ 0x2424e715, __VMLINUX_SYMBOL_STR(rdma_resolve_addr) },
	{ 0xadbd63fa, __VMLINUX_SYMBOL_STR(iscsi_session_setup) },
	{ 0x2abb9f13, __VMLINUX_SYMBOL_STR(iscsi_host_get_param) },
	{ 0x63c4d61f, __VMLINUX_SYMBOL_STR(__bitmap_weight) },
	{ 0x31b2ee9a, __VMLINUX_SYMBOL_STR(iscsi_conn_bind) },
	{ 0x48c82973, __VMLINUX_SYMBOL_STR(iscsi_target_alloc) },
	{ 0x673fa63c, __VMLINUX_SYMBOL_STR(ib_fmr_pool_unmap) },
	{ 0x2e0d2f7f, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0xb2d5a552, __VMLINUX_SYMBOL_STR(complete) },
	{ 0x7f02188f, __VMLINUX_SYMBOL_STR(__msecs_to_jiffies) },
	{ 0x907df803, __VMLINUX_SYMBOL_STR(rdma_event_msg) },
	{ 0xa07bf9cb, __VMLINUX_SYMBOL_STR(iscsi_session_recovery_timedout) },
	{ 0xa587866e, __VMLINUX_SYMBOL_STR(iscsi_conn_setup) },
	{ 0x7b1c81bb, __VMLINUX_SYMBOL_STR(param_ops_uint) },
	{ 0x2b04fec, __VMLINUX_SYMBOL_STR(dma_ops) },
	{ 0xa948f9d4, __VMLINUX_SYMBOL_STR(ib_alloc_cq) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=scsi_mod,libiscsi,ib_core,scsi_transport_iscsi,rdma_cm";


MODULE_INFO(srcversion, "DC599742937CFC3141E6A77");
