#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x5e862211, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x42595e58, __VMLINUX_SYMBOL_STR(vgacon_text_force) },
	{ 0x8487a2b6, __VMLINUX_SYMBOL_STR(flush_work) },
	{ 0x2d3385d3, __VMLINUX_SYMBOL_STR(system_wq) },
	{ 0x2dcafc98, __VMLINUX_SYMBOL_STR(drm_gem_prime_export) },
	{ 0x91040120, __VMLINUX_SYMBOL_STR(drm_release) },
	{ 0xc6da18a8, __VMLINUX_SYMBOL_STR(drm_fb_helper_set_par) },
	{ 0x670a0972, __VMLINUX_SYMBOL_STR(ttm_pool_populate) },
	{ 0x7e104a81, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xb2d524ee, __VMLINUX_SYMBOL_STR(ttm_dma_tt_init) },
	{ 0x5aadc0dc, __VMLINUX_SYMBOL_STR(drm_dev_register) },
	{ 0x91c0e5ad, __VMLINUX_SYMBOL_STR(drm_compat_ioctl) },
	{ 0xe80c3a76, __VMLINUX_SYMBOL_STR(drm_atomic_helper_update_plane) },
	{ 0xdae80100, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0x2ee2a6bb, __VMLINUX_SYMBOL_STR(drm_atomic_helper_crtc_duplicate_state) },
	{ 0x1ed02f33, __VMLINUX_SYMBOL_STR(drm_dev_alloc) },
	{ 0x4f8a6161, __VMLINUX_SYMBOL_STR(drm_fb_helper_initial_config) },
	{ 0x7aa1756e, __VMLINUX_SYMBOL_STR(kvfree) },
	{ 0x616bf458, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0x7e9e62cb, __VMLINUX_SYMBOL_STR(drm_mode_config_cleanup) },
	{ 0x43dd11c, __VMLINUX_SYMBOL_STR(drm_mode_config_reset) },
	{ 0xd13aedd3, __VMLINUX_SYMBOL_STR(drm_atomic_helper_connector_reset) },
	{ 0xebdb1429, __VMLINUX_SYMBOL_STR(drm_set_preferred_mode) },
	{ 0x2471a95d, __VMLINUX_SYMBOL_STR(ttm_bo_validate) },
	{ 0x60600c23, __VMLINUX_SYMBOL_STR(ttm_bo_init) },
	{ 0x1f8d2ffb, __VMLINUX_SYMBOL_STR(drm_fb_helper_debug_leave) },
	{ 0xa2370afd, __VMLINUX_SYMBOL_STR(drm_cvt_mode) },
	{ 0x60660aa8, __VMLINUX_SYMBOL_STR(virtio_check_driver_offered_feature) },
	{ 0x6b06fdce, __VMLINUX_SYMBOL_STR(delayed_work_timer_fn) },
	{ 0xfab9603f, __VMLINUX_SYMBOL_STR(get_task_comm) },
	{ 0xee0ad904, __VMLINUX_SYMBOL_STR(drm_helper_probe_single_connector_modes) },
	{ 0x802bde1c, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0x5d7318dc, __VMLINUX_SYMBOL_STR(drm_global_item_ref) },
	{ 0x54f24d1a, __VMLINUX_SYMBOL_STR(fence_default_wait) },
	{ 0x3fec048f, __VMLINUX_SYMBOL_STR(sg_next) },
	{ 0x9580deb, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0x4318d5b4, __VMLINUX_SYMBOL_STR(drm_kms_helper_hotplug_event) },
	{ 0xb5f05fbc, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0xe31d9f2b, __VMLINUX_SYMBOL_STR(virtqueue_kick) },
	{ 0x27436bee, __VMLINUX_SYMBOL_STR(drm_dev_unref) },
	{ 0x6ba61e6a, __VMLINUX_SYMBOL_STR(drm_encoder_init) },
	{ 0x4629334c, __VMLINUX_SYMBOL_STR(__preempt_count) },
	{ 0x31cccaed, __VMLINUX_SYMBOL_STR(drm_atomic_helper_crtc_reset) },
	{ 0x96d4af68, __VMLINUX_SYMBOL_STR(drm_universal_plane_init) },
	{ 0x79bb0f5a, __VMLINUX_SYMBOL_STR(drm_pci_set_busid) },
	{ 0x75b156c, __VMLINUX_SYMBOL_STR(virtqueue_get_buf) },
	{ 0x702a6e64, __VMLINUX_SYMBOL_STR(drm_connector_cleanup) },
	{ 0x3dc7fac0, __VMLINUX_SYMBOL_STR(mutex_trylock) },
	{ 0xb1176e3b, __VMLINUX_SYMBOL_STR(drm_fb_helper_unregister_fbi) },
	{ 0x2536bc5a, __VMLINUX_SYMBOL_STR(drm_atomic_helper_connector_duplicate_state) },
	{ 0x9e88526, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0xfa22139c, __VMLINUX_SYMBOL_STR(drm_fb_helper_pan_display) },
	{ 0x4f8b5ddb, __VMLINUX_SYMBOL_STR(_copy_to_user) },
	{ 0x7539f0f6, __VMLINUX_SYMBOL_STR(ttm_mem_global_init) },
	{ 0x90fbca94, __VMLINUX_SYMBOL_STR(drm_atomic_helper_set_config) },
	{ 0x955a832f, __VMLINUX_SYMBOL_STR(___preempt_schedule) },
	{ 0xb607480f, __VMLINUX_SYMBOL_STR(ttm_mem_global_release) },
	{ 0x672f6cee, __VMLINUX_SYMBOL_STR(drm_mode_connector_attach_encoder) },
	{ 0x7fb8251a, __VMLINUX_SYMBOL_STR(ttm_bo_unref) },
	{ 0xe81ef1dd, __VMLINUX_SYMBOL_STR(remove_conflicting_framebuffers) },
	{ 0xc7e7eaa4, __VMLINUX_SYMBOL_STR(virtqueue_add_sgs) },
	{ 0x98782fd0, __VMLINUX_SYMBOL_STR(dev_err) },
	{ 0x1916e38c, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0xbcf9c794, __VMLINUX_SYMBOL_STR(current_task) },
	{ 0x4d73cd91, __VMLINUX_SYMBOL_STR(ttm_bo_add_to_lru) },
	{ 0xf1fa7158, __VMLINUX_SYMBOL_STR(mutex_lock_interruptible) },
	{ 0x4e0dca7a, __VMLINUX_SYMBOL_STR(drm_helper_mode_fill_fb_struct) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x33b13caa, __VMLINUX_SYMBOL_STR(drm_crtc_init_with_planes) },
	{ 0x3a5d0a75, __VMLINUX_SYMBOL_STR(drm_put_dev) },
	{ 0xf0ce1a2a, __VMLINUX_SYMBOL_STR(drm_atomic_helper_plane_reset) },
	{ 0xe35e888e, __VMLINUX_SYMBOL_STR(drm_gem_handle_create) },
	{ 0x30b42f69, __VMLINUX_SYMBOL_STR(ttm_bo_kmap) },
	{ 0x880db811, __VMLINUX_SYMBOL_STR(drm_fb_helper_fill_var) },
	{ 0x9166fada, __VMLINUX_SYMBOL_STR(strncpy) },
	{ 0xa29f0884, __VMLINUX_SYMBOL_STR(virtqueue_disable_cb) },
	{ 0xf709512e, __VMLINUX_SYMBOL_STR(drm_send_vblank_event) },
	{ 0x966792a2, __VMLINUX_SYMBOL_STR(ttm_eu_fence_buffer_objects) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x1081a331, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x84ffea8b, __VMLINUX_SYMBOL_STR(idr_preload) },
	{ 0x66b92003, __VMLINUX_SYMBOL_STR(drm_gem_object_release) },
	{ 0x9f8150cd, __VMLINUX_SYMBOL_STR(drm_read) },
	{ 0x841c79f8, __VMLINUX_SYMBOL_STR(ttm_bo_dma_acc_size) },
	{ 0x95ba9e29, __VMLINUX_SYMBOL_STR(noop_llseek) },
	{ 0xf1ec5cf6, __VMLINUX_SYMBOL_STR(ttm_bo_init_mm) },
	{ 0x169e9b8a, __VMLINUX_SYMBOL_STR(ttm_bo_wait) },
	{ 0xa4fde00, __VMLINUX_SYMBOL_STR(idr_alloc) },
	{ 0xe67e6b5c, __VMLINUX_SYMBOL_STR(ttm_bo_device_init) },
	{ 0x4ecb3123, __VMLINUX_SYMBOL_STR(drm_fb_helper_release_fbi) },
	{ 0x87bdd3c, __VMLINUX_SYMBOL_STR(drm_debugfs_create_files) },
	{ 0x1dd71f7a, __VMLINUX_SYMBOL_STR(drm_err) },
	{ 0x5c15bab1, __VMLINUX_SYMBOL_STR(drm_connector_init) },
	{ 0x9014e689, __VMLINUX_SYMBOL_STR(drm_fb_helper_prepare) },
	{ 0xdf1427e5, __VMLINUX_SYMBOL_STR(idr_remove) },
	{ 0x20645642, __VMLINUX_SYMBOL_STR(drm_debug) },
	{ 0xebff5cf5, __VMLINUX_SYMBOL_STR(fence_signal_locked) },
	{ 0x4ea1f5a2, __VMLINUX_SYMBOL_STR(drm_gem_object_free) },
	{ 0x6d8e90c4, __VMLINUX_SYMBOL_STR(ttm_eu_backoff_reservation) },
	{ 0xbaeaba0c, __VMLINUX_SYMBOL_STR(virtqueue_get_vring_size) },
	{ 0x61fc0ff1, __VMLINUX_SYMBOL_STR(drm_gem_prime_fd_to_handle) },
	{ 0x2f665a27, __VMLINUX_SYMBOL_STR(drm_ioctl) },
	{ 0x1825f583, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_imageblit) },
	{ 0xe0fe4b2a, __VMLINUX_SYMBOL_STR(drm_gem_prime_import) },
	{ 0x1dad9faf, __VMLINUX_SYMBOL_STR(drm_atomic_helper_plane_duplicate_state) },
	{ 0x6c3d728d, __VMLINUX_SYMBOL_STR(drm_atomic_helper_connector_destroy_state) },
	{ 0xcfc8af13, __VMLINUX_SYMBOL_STR(unregister_virtio_driver) },
	{ 0x78f65a4f, __VMLINUX_SYMBOL_STR(drm_atomic_helper_check) },
	{ 0xcd5fffd6, __VMLINUX_SYMBOL_STR(ttm_bo_del_sub_from_lru) },
	{ 0xe30bc69, __VMLINUX_SYMBOL_STR(drm_atomic_helper_commit) },
	{ 0x70cd1f, __VMLINUX_SYMBOL_STR(queue_delayed_work_on) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x9e728653, __VMLINUX_SYMBOL_STR(drm_fb_helper_check_var) },
	{ 0x59aa14cf, __VMLINUX_SYMBOL_STR(fence_release) },
	{ 0xe50becaf, __VMLINUX_SYMBOL_STR(drm_fb_helper_blank) },
	{ 0xd62c833f, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0xa202a8e5, __VMLINUX_SYMBOL_STR(kmalloc_order_trace) },
	{ 0xfe355749, __VMLINUX_SYMBOL_STR(drm_gem_object_lookup) },
	{ 0x483acda2, __VMLINUX_SYMBOL_STR(drm_gem_handle_delete) },
	{ 0x645ab792, __VMLINUX_SYMBOL_STR(drm_add_modes_noedid) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0xadc4320c, __VMLINUX_SYMBOL_STR(ttm_eu_reserve_buffers) },
	{ 0xe69002d6, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x7ba754c9, __VMLINUX_SYMBOL_STR(drm_fb_helper_alloc_fbi) },
	{ 0xe259ae9e, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x6134433f, __VMLINUX_SYMBOL_STR(reservation_object_add_excl_fence) },
	{ 0x680ec266, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0x23b5a32f, __VMLINUX_SYMBOL_STR(drm_atomic_helper_connector_dpms) },
	{ 0xddd1185e, __VMLINUX_SYMBOL_STR(drm_gem_prime_handle_to_fd) },
	{ 0xa6bbd805, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0x970c4501, __VMLINUX_SYMBOL_STR(drm_connector_unregister) },
	{ 0x2dc82fdc, __VMLINUX_SYMBOL_STR(drm_gem_object_init) },
	{ 0x60cd4b4f, __VMLINUX_SYMBOL_STR(drm_encoder_cleanup) },
	{ 0x2207a57f, __VMLINUX_SYMBOL_STR(prepare_to_wait_event) },
	{ 0x98352797, __VMLINUX_SYMBOL_STR(ttm_bo_device_release) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0x80807b5a, __VMLINUX_SYMBOL_STR(drm_crtc_cleanup) },
	{ 0xb6244511, __VMLINUX_SYMBOL_STR(sg_init_one) },
	{ 0xa9bd2676, __VMLINUX_SYMBOL_STR(__vmalloc) },
	{ 0x97c6652, __VMLINUX_SYMBOL_STR(drm_atomic_helper_crtc_destroy_state) },
	{ 0xdf08bef9, __VMLINUX_SYMBOL_STR(drm_mode_config_init) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x27b0bf12, __VMLINUX_SYMBOL_STR(ttm_dma_tt_fini) },
	{ 0xe6279dfd, __VMLINUX_SYMBOL_STR(drm_helper_hpd_irq_event) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x347c6bcf, __VMLINUX_SYMBOL_STR(ww_mutex_unlock) },
	{ 0x2c13cd7c, __VMLINUX_SYMBOL_STR(sg_alloc_table_from_pages) },
	{ 0xc401283, __VMLINUX_SYMBOL_STR(drm_debugfs_remove_files) },
	{ 0x34cecded, __VMLINUX_SYMBOL_STR(drm_fb_helper_fini) },
	{ 0xf08242c2, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0xb1645a2e, __VMLINUX_SYMBOL_STR(sg_free_table) },
	{ 0x7c327c39, __VMLINUX_SYMBOL_STR(drm_atomic_helper_disable_plane) },
	{ 0xd43c1660, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_fillrect) },
	{ 0x564e1aee, __VMLINUX_SYMBOL_STR(ttm_bo_global_init) },
	{ 0x3e2ffc78, __VMLINUX_SYMBOL_STR(drm_mode_probed_add) },
	{ 0x2e0d2f7f, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0x28318305, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0x97f3bb48, __VMLINUX_SYMBOL_STR(drm_fb_helper_setcmap) },
	{ 0x745b2bdc, __VMLINUX_SYMBOL_STR(drm_framebuffer_init) },
	{ 0x16dc4d1f, __VMLINUX_SYMBOL_STR(fence_init) },
	{ 0xc360e7e2, __VMLINUX_SYMBOL_STR(drm_ut_debug_printk) },
	{ 0x5fb2e8ef, __VMLINUX_SYMBOL_STR(idr_init) },
	{ 0xeb9cdaab, __VMLINUX_SYMBOL_STR(ttm_pool_unpopulate) },
	{ 0xfa87fe58, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_copyarea) },
	{ 0x4f6b400b, __VMLINUX_SYMBOL_STR(_copy_from_user) },
	{ 0x60f8d0bd, __VMLINUX_SYMBOL_STR(drm_fb_helper_fill_fix) },
	{ 0x3e4a4621, __VMLINUX_SYMBOL_STR(drm_connector_register) },
	{ 0x3ac1fef9, __VMLINUX_SYMBOL_STR(drm_mode_legacy_fb_format) },
	{ 0x98856bce, __VMLINUX_SYMBOL_STR(virtqueue_enable_cb) },
	{ 0xb5e1a8c5, __VMLINUX_SYMBOL_STR(drm_mode_crtc_set_gamma_size) },
	{ 0x4e8dd264, __VMLINUX_SYMBOL_STR(ttm_bo_global_release) },
	{ 0x49804bc4, __VMLINUX_SYMBOL_STR(drm_fb_helper_debug_enter) },
	{ 0x47c68e03, __VMLINUX_SYMBOL_STR(drm_poll) },
	{ 0x134a265d, __VMLINUX_SYMBOL_STR(drm_fb_helper_init) },
	{ 0x574907aa, __VMLINUX_SYMBOL_STR(drm_fb_helper_single_add_all_connectors) },
	{ 0x801fa0e0, __VMLINUX_SYMBOL_STR(drm_open) },
	{ 0xb5540008, __VMLINUX_SYMBOL_STR(drm_global_item_unref) },
	{ 0x70aa83b7, __VMLINUX_SYMBOL_STR(drm_atomic_helper_plane_destroy_state) },
	{ 0xdba36ed7, __VMLINUX_SYMBOL_STR(register_virtio_driver) },
	{ 0x7729dcad, __VMLINUX_SYMBOL_STR(drm_framebuffer_cleanup) },
	{ 0xd279edba, __VMLINUX_SYMBOL_STR(ttm_bo_mmap) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=drm,drm_kms_helper,ttm,virtio,virtio_ring";

MODULE_ALIAS("virtio:d00000010v*");
