#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x5e862211, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x88263d05, __VMLINUX_SYMBOL_STR(rdma_resolve_ip) },
	{ 0x7e104a81, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xb522ac5b, __VMLINUX_SYMBOL_STR(ib_send_cm_rej) },
	{ 0x3f154eb6, __VMLINUX_SYMBOL_STR(iw_cm_listen) },
	{ 0xa3e15b6, __VMLINUX_SYMBOL_STR(ib_attach_mcast) },
	{ 0xdae80100, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0xfaa31f1, __VMLINUX_SYMBOL_STR(ib_query_gid) },
	{ 0x8bbadd75, __VMLINUX_SYMBOL_STR(__fib_lookup) },
	{ 0x43a53735, __VMLINUX_SYMBOL_STR(__alloc_workqueue_key) },
	{ 0x52fbe530, __VMLINUX_SYMBOL_STR(rdma_port_get_link_layer) },
	{ 0x79aa04a2, __VMLINUX_SYMBOL_STR(get_random_bytes) },
	{ 0x32fe30d4, __VMLINUX_SYMBOL_STR(roce_gid_type_mask_support) },
	{ 0xae8d8108, __VMLINUX_SYMBOL_STR(ib_sa_join_multicast) },
	{ 0x41f2c5af, __VMLINUX_SYMBOL_STR(ib_send_cm_req) },
	{ 0x7a91f320, __VMLINUX_SYMBOL_STR(ib_send_cm_dreq) },
	{ 0xc7a4fbed, __VMLINUX_SYMBOL_STR(rtnl_lock) },
	{ 0xb5fbd4c5, __VMLINUX_SYMBOL_STR(ib_send_cm_rtu) },
	{ 0xa48703ac, __VMLINUX_SYMBOL_STR(dst_release) },
	{ 0xd45b5425, __VMLINUX_SYMBOL_STR(iw_cm_init_qp_attr) },
	{ 0x24e184cb, __VMLINUX_SYMBOL_STR(ib_destroy_qp) },
	{ 0xae11f5e2, __VMLINUX_SYMBOL_STR(ib_init_ah_from_path) },
	{ 0xd2da1048, __VMLINUX_SYMBOL_STR(register_netdevice_notifier) },
	{ 0x8369f987, __VMLINUX_SYMBOL_STR(iw_cm_reject) },
	{ 0x448eac3e, __VMLINUX_SYMBOL_STR(kmemdup) },
	{ 0xb5f05fbc, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x1a4bb4bb, __VMLINUX_SYMBOL_STR(iw_cm_accept) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0xcc642a4, __VMLINUX_SYMBOL_STR(__put_net) },
	{ 0x9d0d6206, __VMLINUX_SYMBOL_STR(unregister_netdevice_notifier) },
	{ 0x7de07d65, __VMLINUX_SYMBOL_STR(ib_get_cached_gid) },
	{ 0xef1627bb, __VMLINUX_SYMBOL_STR(ib_modify_qp) },
	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
	{ 0xac2d1ad9, __VMLINUX_SYMBOL_STR(ib_send_cm_mra) },
	{ 0x576fdbac, __VMLINUX_SYMBOL_STR(ib_sa_free_multicast) },
	{ 0xec69922c, __VMLINUX_SYMBOL_STR(rdma_copy_addr) },
	{ 0x9faa0c3c, __VMLINUX_SYMBOL_STR(ib_get_net_dev_by_params) },
	{ 0x9e88526, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0x2626ae42, __VMLINUX_SYMBOL_STR(ib_create_qp) },
	{ 0x64ab0e98, __VMLINUX_SYMBOL_STR(wait_for_completion) },
	{ 0xfdf7e4b, __VMLINUX_SYMBOL_STR(ib_send_cm_drep) },
	{ 0x2ec9dc75, __VMLINUX_SYMBOL_STR(ib_cm_init_qp_attr) },
	{ 0xdd727d5a, __VMLINUX_SYMBOL_STR(unregister_pernet_subsys) },
	{ 0x809388ca, __VMLINUX_SYMBOL_STR(idr_destroy) },
	{ 0x1916e38c, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0xbcf9c794, __VMLINUX_SYMBOL_STR(current_task) },
	{ 0x3d7149d9, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x25ea29c6, __VMLINUX_SYMBOL_STR(iw_cm_disconnect) },
	{ 0xe9b7da6a, __VMLINUX_SYMBOL_STR(ibnl_put_attr) },
	{ 0x449ad0a7, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0x30a0aaf1, __VMLINUX_SYMBOL_STR(__ethtool_get_settings) },
	{ 0x90e807c7, __VMLINUX_SYMBOL_STR(ib_cache_gid_parse_type_str) },
	{ 0x9166fada, __VMLINUX_SYMBOL_STR(strncpy) },
	{ 0x5a988e72, __VMLINUX_SYMBOL_STR(ib_send_cm_rep) },
	{ 0xbfe6f427, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irq) },
	{ 0xba377510, __VMLINUX_SYMBOL_STR(ib_query_port) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x1081a331, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x8c03d20c, __VMLINUX_SYMBOL_STR(destroy_workqueue) },
	{ 0x37c4dbce, __VMLINUX_SYMBOL_STR(iw_destroy_cm_id) },
	{ 0x47679b1c, __VMLINUX_SYMBOL_STR(dev_get_by_index) },
	{ 0x7eb6055d, __VMLINUX_SYMBOL_STR(config_group_init_type_name) },
	{ 0x2469810f, __VMLINUX_SYMBOL_STR(__rcu_read_unlock) },
	{ 0xa735db59, __VMLINUX_SYMBOL_STR(prandom_u32) },
	{ 0xa4fde00, __VMLINUX_SYMBOL_STR(idr_alloc) },
	{ 0x48bfbea1, __VMLINUX_SYMBOL_STR(configfs_register_subsystem) },
	{ 0x2208b97d, __VMLINUX_SYMBOL_STR(ib_get_cached_pkey) },
	{ 0x28af6928, __VMLINUX_SYMBOL_STR(init_net) },
	{ 0xcba15626, __VMLINUX_SYMBOL_STR(ib_set_client_data) },
	{ 0x2396d8ac, __VMLINUX_SYMBOL_STR(ib_init_ah_from_mcmember) },
	{ 0x287d1e73, __VMLINUX_SYMBOL_STR(ib_sa_unregister_client) },
	{ 0x9290b321, __VMLINUX_SYMBOL_STR(vlan_dev_real_dev) },
	{ 0xcd69507f, __VMLINUX_SYMBOL_STR(ib_create_cm_id) },
	{ 0x6bf124ff, __VMLINUX_SYMBOL_STR(ib_sa_path_rec_get) },
	{ 0xdf1427e5, __VMLINUX_SYMBOL_STR(idr_remove) },
	{ 0x6113ef14, __VMLINUX_SYMBOL_STR(ib_register_client) },
	{ 0xda0d50ec, __VMLINUX_SYMBOL_STR(ib_sa_cancel_query) },
	{ 0xc6cbbc89, __VMLINUX_SYMBOL_STR(capable) },
	{ 0x81144f9d, __VMLINUX_SYMBOL_STR(idr_find_slowpath) },
	{ 0x3d3ac5d7, __VMLINUX_SYMBOL_STR(ib_sa_get_mcmember_rec) },
	{ 0xa916b694, __VMLINUX_SYMBOL_STR(strnlen) },
	{ 0x624e880, __VMLINUX_SYMBOL_STR(ib_detach_mcast) },
	{ 0x61441b09, __VMLINUX_SYMBOL_STR(ib_cm_notify) },
	{ 0x1840dc34, __VMLINUX_SYMBOL_STR(rdma_addr_cancel) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x922f92d7, __VMLINUX_SYMBOL_STR(iw_cm_connect) },
	{ 0x1fbd16da, __VMLINUX_SYMBOL_STR(ip_tos2prio) },
	{ 0xe5815f8a, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irq) },
	{ 0xae6ecebd, __VMLINUX_SYMBOL_STR(ib_find_cached_pkey) },
	{ 0x9c4dc7a8, __VMLINUX_SYMBOL_STR(ip_mc_inc_group) },
	{ 0x34b50929, __VMLINUX_SYMBOL_STR(register_pernet_subsys) },
	{ 0x9d9cabc5, __VMLINUX_SYMBOL_STR(rdma_addr_register_client) },
	{ 0xcdea4d91, __VMLINUX_SYMBOL_STR(configfs_unregister_subsystem) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0x1edc4064, __VMLINUX_SYMBOL_STR(rdma_addr_unregister_client) },
	{ 0x5611cdea, __VMLINUX_SYMBOL_STR(rdma_node_get_transport) },
	{ 0xe69002d6, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xa8320354, __VMLINUX_SYMBOL_STR(ib_destroy_cm_id) },
	{ 0xe259ae9e, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x680ec266, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0x6e91ac42, __VMLINUX_SYMBOL_STR(ibnl_add_client) },
	{ 0x1c3c0ad3, __VMLINUX_SYMBOL_STR(rdma_addr_size) },
	{ 0xfb7aeb7a, __VMLINUX_SYMBOL_STR(fib_table_lookup) },
	{ 0xff0e1f1d, __VMLINUX_SYMBOL_STR(rdma_translate_ip) },
	{ 0xaa1a177f, __VMLINUX_SYMBOL_STR(rt6_lookup) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x5f51c4a, __VMLINUX_SYMBOL_STR(ib_sa_register_client) },
	{ 0xc67f14a5, __VMLINUX_SYMBOL_STR(ibnl_remove_client) },
	{ 0xb352177e, __VMLINUX_SYMBOL_STR(find_first_bit) },
	{ 0xf7152949, __VMLINUX_SYMBOL_STR(ib_cm_insert_listen) },
	{ 0x934d1dec, __VMLINUX_SYMBOL_STR(ib_find_cached_gid_by_port) },
	{ 0x2e0d2f7f, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0xb2d5a552, __VMLINUX_SYMBOL_STR(complete) },
	{ 0x28318305, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0x5fb2e8ef, __VMLINUX_SYMBOL_STR(idr_init) },
	{ 0x8d522714, __VMLINUX_SYMBOL_STR(__rcu_read_lock) },
	{ 0x3a7a2ec9, __VMLINUX_SYMBOL_STR(ibnl_put_msg) },
	{ 0x45384eaa, __VMLINUX_SYMBOL_STR(ip_mc_dec_group) },
	{ 0x230bc3df, __VMLINUX_SYMBOL_STR(config_group_init) },
	{ 0x2370eacf, __VMLINUX_SYMBOL_STR(ib_send_cm_sidr_rep) },
	{ 0xca83eb24, __VMLINUX_SYMBOL_STR(ib_unregister_client) },
	{ 0xd542439, __VMLINUX_SYMBOL_STR(__ipv6_addr_type) },
	{ 0xba50ad9e, __VMLINUX_SYMBOL_STR(inet_get_local_port_range) },
	{ 0xa75229e9, __VMLINUX_SYMBOL_STR(iw_create_cm_id) },
	{ 0x6e720ff2, __VMLINUX_SYMBOL_STR(rtnl_unlock) },
	{ 0x2a91bb33, __VMLINUX_SYMBOL_STR(ib_cache_gid_type_str) },
	{ 0x6306f64c, __VMLINUX_SYMBOL_STR(ib_send_cm_sidr_req) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=ib_addr,ib_cm,iw_cm,ib_core,ib_sa";

