#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x5e862211, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xae405b5f, __VMLINUX_SYMBOL_STR(kmem_cache_destroy) },
	{ 0x762485, __VMLINUX_SYMBOL_STR(iget_failed) },
	{ 0x7e104a81, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xcbcbfff2, __VMLINUX_SYMBOL_STR(drop_nlink) },
	{ 0x83d2be7b, __VMLINUX_SYMBOL_STR(mark_buffer_dirty_inode) },
	{ 0x138be331, __VMLINUX_SYMBOL_STR(up_read) },
	{ 0xb4e99a03, __VMLINUX_SYMBOL_STR(unload_nls) },
	{ 0xa659715d, __VMLINUX_SYMBOL_STR(make_bad_inode) },
	{ 0xdae80100, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0xb38cc013, __VMLINUX_SYMBOL_STR(generic_file_llseek) },
	{ 0x71d61c76, __VMLINUX_SYMBOL_STR(__mark_inode_dirty) },
	{ 0x7aa1756e, __VMLINUX_SYMBOL_STR(kvfree) },
	{ 0x704efadd, __VMLINUX_SYMBOL_STR(inode_permission) },
	{ 0xa68abd94, __VMLINUX_SYMBOL_STR(generic_write_checks) },
	{ 0x6d356209, __VMLINUX_SYMBOL_STR(crc_itu_t) },
	{ 0x60a13e90, __VMLINUX_SYMBOL_STR(rcu_barrier) },
	{ 0x7ce9bdab, __VMLINUX_SYMBOL_STR(__generic_file_write_iter) },
	{ 0xf1e3db94, __VMLINUX_SYMBOL_STR(simple_write_end) },
	{ 0x815b5dd4, __VMLINUX_SYMBOL_STR(match_octal) },
	{ 0x484ebce, __VMLINUX_SYMBOL_STR(block_write_begin) },
	{ 0x57000eee, __VMLINUX_SYMBOL_STR(seq_puts) },
	{ 0x23a9b726, __VMLINUX_SYMBOL_STR(is_bad_inode) },
	{ 0x67a0dbe9, __VMLINUX_SYMBOL_STR(pagecache_get_page) },
	{ 0xa18610e6, __VMLINUX_SYMBOL_STR(generic_file_open) },
	{ 0x179651ac, __VMLINUX_SYMBOL_STR(_raw_read_lock) },
	{ 0xa28e15de, __VMLINUX_SYMBOL_STR(__lock_page) },
	{ 0xdfd4dae0, __VMLINUX_SYMBOL_STR(ll_rw_block) },
	{ 0x69d409f7, __VMLINUX_SYMBOL_STR(__lock_buffer) },
	{ 0xc0a3d105, __VMLINUX_SYMBOL_STR(find_next_bit) },
	{ 0x802bde1c, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0x44e9a829, __VMLINUX_SYMBOL_STR(match_token) },
	{ 0xb502a63f, __VMLINUX_SYMBOL_STR(inc_nlink) },
	{ 0xb5f05fbc, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x58e79459, __VMLINUX_SYMBOL_STR(mount_bdev) },
	{ 0x85df9b6c, __VMLINUX_SYMBOL_STR(strsep) },
	{ 0xd371f36d, __VMLINUX_SYMBOL_STR(page_symlink_inode_operations) },
	{ 0xd21418f5, __VMLINUX_SYMBOL_STR(generic_read_dir) },
	{ 0x1ff5a88d, __VMLINUX_SYMBOL_STR(__getblk_gfp) },
	{ 0x28aa6a67, __VMLINUX_SYMBOL_STR(call_rcu) },
	{ 0x54460120, __VMLINUX_SYMBOL_STR(unlock_buffer) },
	{ 0x4b22bc76, __VMLINUX_SYMBOL_STR(truncate_setsize) },
	{ 0x72e426bc, __VMLINUX_SYMBOL_STR(down_read) },
	{ 0x4f8b5ddb, __VMLINUX_SYMBOL_STR(_copy_to_user) },
	{ 0xe8ef0ff0, __VMLINUX_SYMBOL_STR(current_kernel_time64) },
	{ 0xafee3ade, __VMLINUX_SYMBOL_STR(mpage_readpages) },
	{ 0xb8e7ce2c, __VMLINUX_SYMBOL_STR(__put_user_8) },
	{ 0xfb578fc5, __VMLINUX_SYMBOL_STR(memset) },
	{ 0x89d0fbb0, __VMLINUX_SYMBOL_STR(mpage_readpage) },
	{ 0x70113853, __VMLINUX_SYMBOL_STR(inode_add_bytes) },
	{ 0xf040800, __VMLINUX_SYMBOL_STR(__bread_gfp) },
	{ 0xfe61d985, __VMLINUX_SYMBOL_STR(current_fs_time) },
	{ 0x3d7149d9, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x3971cde6, __VMLINUX_SYMBOL_STR(d_obtain_alias) },
	{ 0x449ad0a7, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0x8fd1152e, __VMLINUX_SYMBOL_STR(_raw_write_unlock) },
	{ 0xb10820e4, __VMLINUX_SYMBOL_STR(_raw_read_unlock) },
	{ 0xee3079e2, __VMLINUX_SYMBOL_STR(mpage_writepages) },
	{ 0x9166fada, __VMLINUX_SYMBOL_STR(strncpy) },
	{ 0xe17f8bc8, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x1081a331, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x2eb9e2f6, __VMLINUX_SYMBOL_STR(set_nlink) },
	{ 0x1f3c6075, __VMLINUX_SYMBOL_STR(__wait_on_buffer) },
	{ 0xe8db8dd2, __VMLINUX_SYMBOL_STR(_raw_write_lock) },
	{ 0xde70caf8, __VMLINUX_SYMBOL_STR(setattr_copy) },
	{ 0xf5b9dbd2, __VMLINUX_SYMBOL_STR(insert_inode_locked) },
	{ 0xce980615, __VMLINUX_SYMBOL_STR(sync_dirty_buffer) },
	{ 0x8172db07, __VMLINUX_SYMBOL_STR(truncate_pagecache) },
	{ 0x4e3567f7, __VMLINUX_SYMBOL_STR(match_int) },
	{ 0xb126bc85, __VMLINUX_SYMBOL_STR(unlock_page) },
	{ 0xf4b3a868, __VMLINUX_SYMBOL_STR(generic_file_read_iter) },
	{ 0x2cde5e39, __VMLINUX_SYMBOL_STR(up_write) },
	{ 0xbfb6ce61, __VMLINUX_SYMBOL_STR(down_write) },
	{ 0x39a3dac0, __VMLINUX_SYMBOL_STR(inode_nohighmem) },
	{ 0x6916ba97, __VMLINUX_SYMBOL_STR(__brelse) },
	{ 0xfe5d4bb2, __VMLINUX_SYMBOL_STR(sys_tz) },
	{ 0x5ac05f76, __VMLINUX_SYMBOL_STR(inode_init_once) },
	{ 0xc6cbbc89, __VMLINUX_SYMBOL_STR(capable) },
	{ 0x9e05aed6, __VMLINUX_SYMBOL_STR(invalidate_inode_buffers) },
	{ 0x40a9b349, __VMLINUX_SYMBOL_STR(vzalloc) },
	{ 0xd189bba9, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0xb2fd5ceb, __VMLINUX_SYMBOL_STR(__put_user_4) },
	{ 0xb5a87016, __VMLINUX_SYMBOL_STR(generic_file_mmap) },
	{ 0x4acdfa31, __VMLINUX_SYMBOL_STR(block_write_full_page) },
	{ 0x2cded7a5, __VMLINUX_SYMBOL_STR(inode_sub_bytes) },
	{ 0x5ef4612d, __VMLINUX_SYMBOL_STR(truncate_inode_pages_final) },
	{ 0x4c08a09e, __VMLINUX_SYMBOL_STR(load_nls) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x6d334118, __VMLINUX_SYMBOL_STR(__get_user_8) },
	{ 0x9be1beda, __VMLINUX_SYMBOL_STR(generic_write_end) },
	{ 0x7cc4d08b, __VMLINUX_SYMBOL_STR(unlock_new_inode) },
	{ 0xb2998c7, __VMLINUX_SYMBOL_STR(kill_block_super) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0x263f355a, __VMLINUX_SYMBOL_STR(inode_change_ok) },
	{ 0xe69002d6, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xe259ae9e, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x92234a23, __VMLINUX_SYMBOL_STR(kmem_cache_create) },
	{ 0x9111e381, __VMLINUX_SYMBOL_STR(d_tmpfile) },
	{ 0x5595f1d4, __VMLINUX_SYMBOL_STR(register_filesystem) },
	{ 0xbe3c71b5, __VMLINUX_SYMBOL_STR(iput) },
	{ 0xcdd90b8a, __VMLINUX_SYMBOL_STR(generic_file_fsync) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x6a3ac611, __VMLINUX_SYMBOL_STR(ihold) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x50e3dab4, __VMLINUX_SYMBOL_STR(load_nls_default) },
	{ 0x4d7775a0, __VMLINUX_SYMBOL_STR(d_splice_alias) },
	{ 0x2af3c99f, __VMLINUX_SYMBOL_STR(sync_filesystem) },
	{ 0xbc0862c5, __VMLINUX_SYMBOL_STR(block_truncate_page) },
	{ 0x6447a6b, __VMLINUX_SYMBOL_STR(sb_set_blocksize) },
	{ 0x169b408a, __VMLINUX_SYMBOL_STR(d_make_root) },
	{ 0xbb448f0d, __VMLINUX_SYMBOL_STR(__blockdev_direct_IO) },
	{ 0x63c4d61f, __VMLINUX_SYMBOL_STR(__bitmap_weight) },
	{ 0x9195901b, __VMLINUX_SYMBOL_STR(mark_buffer_dirty) },
	{ 0xcc642ccf, __VMLINUX_SYMBOL_STR(ioctl_by_bdev) },
	{ 0x7fbb8490, __VMLINUX_SYMBOL_STR(unregister_filesystem) },
	{ 0x3cad0dce, __VMLINUX_SYMBOL_STR(init_special_inode) },
	{ 0x5db69c3d, __VMLINUX_SYMBOL_STR(new_inode) },
	{ 0xb0e602eb, __VMLINUX_SYMBOL_STR(memmove) },
	{ 0xa776cab7, __VMLINUX_SYMBOL_STR(generic_file_splice_read) },
	{ 0x8d73278e, __VMLINUX_SYMBOL_STR(hex_asc_upper) },
	{ 0x773b20d9, __VMLINUX_SYMBOL_STR(grab_cache_page_write_begin) },
	{ 0x3263cff5, __VMLINUX_SYMBOL_STR(clear_inode) },
	{ 0x411550a6, __VMLINUX_SYMBOL_STR(d_instantiate) },
	{ 0xb3372e39, __VMLINUX_SYMBOL_STR(__init_rwsem) },
	{ 0x748f1df7, __VMLINUX_SYMBOL_STR(__put_page) },
	{ 0x5f76d3b7, __VMLINUX_SYMBOL_STR(generic_block_bmap) },
	{ 0x36b61118, __VMLINUX_SYMBOL_STR(clear_nlink) },
	{ 0x8e8e1bc1, __VMLINUX_SYMBOL_STR(iget_locked) },
	{ 0xf812cff6, __VMLINUX_SYMBOL_STR(memscan) },
	{ 0x96c78fad, __VMLINUX_SYMBOL_STR(vfs_fsync_range) },
	{ 0x19186a0e, __VMLINUX_SYMBOL_STR(inode_init_owner) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=crc-itu-t";

