#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x5e862211, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x2d3385d3, __VMLINUX_SYMBOL_STR(system_wq) },
	{ 0x7e104a81, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x80f9913a, __VMLINUX_SYMBOL_STR(perf_tp_event) },
	{ 0xf9a482f9, __VMLINUX_SYMBOL_STR(msleep) },
	{ 0x4f6f6ff2, __VMLINUX_SYMBOL_STR(__pm_runtime_idle) },
	{ 0x4fd859b3, __VMLINUX_SYMBOL_STR(sst_module_new) },
	{ 0xdae80100, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0x973f51f5, __VMLINUX_SYMBOL_STR(sst_dsp_reset) },
	{ 0xbdf58c59, __VMLINUX_SYMBOL_STR(__pm_runtime_disable) },
	{ 0x8b60ef4d, __VMLINUX_SYMBOL_STR(sst_mem_block_register) },
	{ 0x6df8fd73, __VMLINUX_SYMBOL_STR(sst_dsp_wake) },
	{ 0xb9f3a641, __VMLINUX_SYMBOL_STR(snd_soc_unregister_platform) },
	{ 0x4a045773, __VMLINUX_SYMBOL_STR(sst_shim32_write) },
	{ 0x6859bd4e, __VMLINUX_SYMBOL_STR(__pm_runtime_use_autosuspend) },
	{ 0x754d539c, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0xa92efa86, __VMLINUX_SYMBOL_STR(sst_dsp_get_offset) },
	{ 0x5e7f4920, __VMLINUX_SYMBOL_STR(snd_pcm_format_set_silence) },
	{ 0xc48a3366, __VMLINUX_SYMBOL_STR(__pm_runtime_suspend) },
	{ 0x62d0edee, __VMLINUX_SYMBOL_STR(snd_pcm_period_elapsed) },
	{ 0xa0c6960, __VMLINUX_SYMBOL_STR(sst_dsp_shim_write) },
	{ 0xf2b0a830, __VMLINUX_SYMBOL_STR(snd_dma_alloc_pages) },
	{ 0x74603c96, __VMLINUX_SYMBOL_STR(sst_module_get_from_id) },
	{ 0xcc03f190, __VMLINUX_SYMBOL_STR(sst_dsp_outbox_read) },
	{ 0x714f44b0, __VMLINUX_SYMBOL_STR(snd_soc_set_runtime_hwparams) },
	{ 0xe6e52f04, __VMLINUX_SYMBOL_STR(sst_fw_new) },
	{ 0x96350cbd, __VMLINUX_SYMBOL_STR(sst_dsp_dma_get_channel) },
	{ 0xe0c22eb8, __VMLINUX_SYMBOL_STR(sst_dsp_dma_put_channel) },
	{ 0x88bfa7e, __VMLINUX_SYMBOL_STR(cancel_work_sync) },
	{ 0xeae3dfd6, __VMLINUX_SYMBOL_STR(__const_udelay) },
	{ 0x4d90281d, __VMLINUX_SYMBOL_STR(sst_memcpy_toio_32) },
	{ 0xee032ea3, __VMLINUX_SYMBOL_STR(sst_dsp_inbox_read) },
	{ 0xb5f05fbc, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x85df9b6c, __VMLINUX_SYMBOL_STR(strsep) },
	{ 0xd679af25, __VMLINUX_SYMBOL_STR(__pm_runtime_resume) },
	{ 0x8bec995b, __VMLINUX_SYMBOL_STR(trace_event_buffer_reserve) },
	{ 0x24f92812, __VMLINUX_SYMBOL_STR(sst_dsp_outbox_write) },
	{ 0x4d3c493c, __VMLINUX_SYMBOL_STR(snd_soc_register_component) },
	{ 0x4629334c, __VMLINUX_SYMBOL_STR(__preempt_count) },
	{ 0x7a2af7b4, __VMLINUX_SYMBOL_STR(cpu_number) },
	{ 0x22ba2c0d, __VMLINUX_SYMBOL_STR(sst_dsp_shim_update_bits) },
	{ 0xbbb9dbe7, __VMLINUX_SYMBOL_STR(__platform_driver_register) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0x929009f3, __VMLINUX_SYMBOL_STR(sst_dsp_dma_copyfrom) },
	{ 0x9e23160a, __VMLINUX_SYMBOL_STR(snd_pcm_suspend_all) },
	{ 0xc21fdcca, __VMLINUX_SYMBOL_STR(sst_ipc_tx_msg_reply_complete) },
	{ 0xb691e662, __VMLINUX_SYMBOL_STR(sst_ipc_reply_find_msg) },
	{ 0x9e88526, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0x8ddaab0d, __VMLINUX_SYMBOL_STR(sst_dsp_mailbox_init) },
	{ 0x6162b21c, __VMLINUX_SYMBOL_STR(sst_module_runtime_restore) },
	{ 0xfea42a91, __VMLINUX_SYMBOL_STR(sst_dsp_stall) },
	{ 0xea6abd20, __VMLINUX_SYMBOL_STR(sst_module_runtime_new) },
	{ 0x1b5e8b82, __VMLINUX_SYMBOL_STR(sst_shim32_read) },
	{ 0x45bd495e, __VMLINUX_SYMBOL_STR(trace_define_field) },
	{ 0xf64097ac, __VMLINUX_SYMBOL_STR(snd_soc_poweroff) },
	{ 0xd288d901, __VMLINUX_SYMBOL_STR(snd_pcm_sgbuf_ops_page) },
	{ 0xfb578fc5, __VMLINUX_SYMBOL_STR(memset) },
	{ 0x51f070df, __VMLINUX_SYMBOL_STR(sst_dsp_dma_copyto) },
	{ 0x98782fd0, __VMLINUX_SYMBOL_STR(dev_err) },
	{ 0x1916e38c, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0x3d7149d9, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0xadf7e47c, __VMLINUX_SYMBOL_STR(__cpu_online_mask) },
	{ 0x35555942, __VMLINUX_SYMBOL_STR(sst_dsp_sleep) },
	{ 0xc0a667f4, __VMLINUX_SYMBOL_STR(sst_ipc_init) },
	{ 0xd7ee3a56, __VMLINUX_SYMBOL_STR(trace_event_reg) },
	{ 0xea15597e, __VMLINUX_SYMBOL_STR(sst_dsp_shim_update_bits_unlocked) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x1081a331, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0xc9629d0d, __VMLINUX_SYMBOL_STR(snd_pcm_lib_free_pages) },
	{ 0x72839fea, __VMLINUX_SYMBOL_STR(sst_ipc_fini) },
	{ 0xe7bc1ba5, __VMLINUX_SYMBOL_STR(sst_mem_block_unregister_all) },
	{ 0x21ae2afb, __VMLINUX_SYMBOL_STR(sst_dsp_ipc_msg_tx) },
	{ 0x69d7dd8a, __VMLINUX_SYMBOL_STR(snd_pcm_lib_ioctl) },
	{ 0xbcec5387, __VMLINUX_SYMBOL_STR(sst_shim32_read64) },
	{ 0x2b4c06fe, __VMLINUX_SYMBOL_STR(snd_soc_unregister_component) },
	{ 0x277aecfc, __VMLINUX_SYMBOL_STR(sst_dsp_shim_read_unlocked) },
	{ 0x4078d4c0, __VMLINUX_SYMBOL_STR(snd_ctl_boolean_mono_info) },
	{ 0x609c4bcd, __VMLINUX_SYMBOL_STR(snd_pcm_lib_malloc_pages) },
	{ 0x1a235328, __VMLINUX_SYMBOL_STR(snd_soc_info_volsw) },
	{ 0xd9a2c94c, __VMLINUX_SYMBOL_STR(sst_shim32_write64) },
	{ 0xe6a9fa13, __VMLINUX_SYMBOL_STR(arch_dma_alloc_attrs) },
	{ 0x7260e249, __VMLINUX_SYMBOL_STR(___preempt_schedule_notrace) },
	{ 0x273df792, __VMLINUX_SYMBOL_STR(sst_block_alloc_scratch) },
	{ 0x483fe73d, __VMLINUX_SYMBOL_STR(queue_kthread_work) },
	{ 0xaa2b37d9, __VMLINUX_SYMBOL_STR(sst_dsp_ipc_msg_rx) },
	{ 0xa805454d, __VMLINUX_SYMBOL_STR(_dev_info) },
	{ 0x78764f4e, __VMLINUX_SYMBOL_STR(pv_irq_ops) },
	{ 0x526ba89a, __VMLINUX_SYMBOL_STR(sst_module_runtime_alloc_blocks) },
	{ 0x42c8de35, __VMLINUX_SYMBOL_STR(ioremap_nocache) },
	{ 0xa309e623, __VMLINUX_SYMBOL_STR(sst_fw_reload) },
	{ 0x79fc2151, __VMLINUX_SYMBOL_STR(pm_runtime_enable) },
	{ 0xe5df83fe, __VMLINUX_SYMBOL_STR(trace_event_ignore_this_pid) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0xd62c833f, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0x352defe2, __VMLINUX_SYMBOL_STR(snd_soc_register_platform) },
	{ 0xad90dfc6, __VMLINUX_SYMBOL_STR(sst_fw_unload) },
	{ 0xf62d6f60, __VMLINUX_SYMBOL_STR(sst_module_alloc_blocks) },
	{ 0xac077ece, __VMLINUX_SYMBOL_STR(sst_module_free) },
	{ 0x610e9c8c, __VMLINUX_SYMBOL_STR(snd_dma_free_pages) },
	{ 0x1e71352f, __VMLINUX_SYMBOL_STR(sst_ipc_tx_message_nowait) },
	{ 0xfe93d6e9, __VMLINUX_SYMBOL_STR(snd_soc_suspend) },
	{ 0x860012ca, __VMLINUX_SYMBOL_STR(trace_event_buffer_commit) },
	{ 0x37402e54, __VMLINUX_SYMBOL_STR(sst_module_runtime_save) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0xe69002d6, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xe259ae9e, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x9948d78b, __VMLINUX_SYMBOL_STR(__dynamic_dev_dbg) },
	{ 0x680ec266, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0x87242ab7, __VMLINUX_SYMBOL_STR(sst_ipc_drop_all) },
	{ 0xa6bbd805, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0xe388ece7, __VMLINUX_SYMBOL_STR(event_triggers_call) },
	{ 0xa7f18e42, __VMLINUX_SYMBOL_STR(sst_dsp_free) },
	{ 0x2207a57f, __VMLINUX_SYMBOL_STR(prepare_to_wait_event) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0xe1096f6a, __VMLINUX_SYMBOL_STR(trace_event_raw_init) },
	{ 0xcc403ef2, __VMLINUX_SYMBOL_STR(dma_supported) },
	{ 0xedc03953, __VMLINUX_SYMBOL_STR(iounmap) },
	{ 0x42bb8d80, __VMLINUX_SYMBOL_STR(perf_trace_buf_prepare) },
	{ 0x1757e9d4, __VMLINUX_SYMBOL_STR(sst_memcpy_fromio_32) },
	{ 0x9efd3948, __VMLINUX_SYMBOL_STR(sst_fw_free_all) },
	{ 0x99e94c3, __VMLINUX_SYMBOL_STR(sst_dsp_boot) },
	{ 0x2361cca, __VMLINUX_SYMBOL_STR(sst_module_runtime_free) },
	{ 0x53569707, __VMLINUX_SYMBOL_STR(this_cpu_off) },
	{ 0xcf14c2f, __VMLINUX_SYMBOL_STR(request_firmware) },
	{ 0xf08242c2, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0x7e77e84d, __VMLINUX_SYMBOL_STR(snd_pcm_lib_preallocate_pages_for_all) },
	{ 0xafa0835e, __VMLINUX_SYMBOL_STR(pm_runtime_set_autosuspend_delay) },
	{ 0x9b645614, __VMLINUX_SYMBOL_STR(dev_warn) },
	{ 0xe9c6b4b4, __VMLINUX_SYMBOL_STR(snd_soc_resume) },
	{ 0x1e2bff52, __VMLINUX_SYMBOL_STR(sst_module_runtime_get_from_id) },
	{ 0xaa973d1a, __VMLINUX_SYMBOL_STR(trace_raw_output_prep) },
	{ 0x2e0d2f7f, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0x11caddc7, __VMLINUX_SYMBOL_STR(trace_seq_printf) },
	{ 0x1c5796ff, __VMLINUX_SYMBOL_STR(sst_ipc_tx_message_wait) },
	{ 0x1d681509, __VMLINUX_SYMBOL_STR(platform_driver_unregister) },
	{ 0x1a81453f, __VMLINUX_SYMBOL_STR(sst_block_free_scratch) },
	{ 0x955cc1a0, __VMLINUX_SYMBOL_STR(snd_soc_bytes_info_ext) },
	{ 0x1f4d0db, __VMLINUX_SYMBOL_STR(sst_dsp_new) },
	{ 0x2a86697b, __VMLINUX_SYMBOL_STR(devm_kmalloc) },
	{ 0x173ad2ac, __VMLINUX_SYMBOL_STR(release_firmware) },
	{ 0x5dda57b9, __VMLINUX_SYMBOL_STR(sst_module_runtime_free_blocks) },
	{ 0x2b04fec, __VMLINUX_SYMBOL_STR(dma_ops) },
	{ 0xe914e41e, __VMLINUX_SYMBOL_STR(strcpy) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=snd-soc-sst-dsp,snd-soc-core,snd-pcm,snd-soc-sst-ipc,snd";

