#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x5e862211, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x91040120, __VMLINUX_SYMBOL_STR(drm_release) },
	{ 0xc6da18a8, __VMLINUX_SYMBOL_STR(drm_fb_helper_set_par) },
	{ 0x670a0972, __VMLINUX_SYMBOL_STR(ttm_pool_populate) },
	{ 0x1fedf0f4, __VMLINUX_SYMBOL_STR(__request_region) },
	{ 0x7e104a81, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xf81e44ba, __VMLINUX_SYMBOL_STR(drm_vma_offset_remove) },
	{ 0x8e7675cb, __VMLINUX_SYMBOL_STR(ttm_tt_fini) },
	{ 0x548cc033, __VMLINUX_SYMBOL_STR(ttm_fbdev_mmap) },
	{ 0x4e8ce12f, __VMLINUX_SYMBOL_STR(drm_crtc_helper_set_config) },
	{ 0x91c0e5ad, __VMLINUX_SYMBOL_STR(drm_compat_ioctl) },
	{ 0x172fddd1, __VMLINUX_SYMBOL_STR(drm_helper_resume_force_mode) },
	{ 0xdae80100, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0xf8d3446d, __VMLINUX_SYMBOL_STR(ttm_bo_move_memcpy) },
	{ 0x4f8a6161, __VMLINUX_SYMBOL_STR(drm_fb_helper_initial_config) },
	{ 0x616bf458, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0x7e9e62cb, __VMLINUX_SYMBOL_STR(drm_mode_config_cleanup) },
	{ 0x74c7662e, __VMLINUX_SYMBOL_STR(drm_pci_exit) },
	{ 0xebdb1429, __VMLINUX_SYMBOL_STR(drm_set_preferred_mode) },
	{ 0x2471a95d, __VMLINUX_SYMBOL_STR(ttm_bo_validate) },
	{ 0x60600c23, __VMLINUX_SYMBOL_STR(ttm_bo_init) },
	{ 0x7cb1c2a3, __VMLINUX_SYMBOL_STR(no_llseek) },
	{ 0xee0ad904, __VMLINUX_SYMBOL_STR(drm_helper_probe_single_connector_modes) },
	{ 0x5d7318dc, __VMLINUX_SYMBOL_STR(drm_global_item_ref) },
	{ 0x9cfae1a5, __VMLINUX_SYMBOL_STR(pci_release_regions) },
	{ 0xf6e679b, __VMLINUX_SYMBOL_STR(param_ops_bool) },
	{ 0xb5f05fbc, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x6ba61e6a, __VMLINUX_SYMBOL_STR(drm_encoder_init) },
	{ 0x79bb0f5a, __VMLINUX_SYMBOL_STR(drm_pci_set_busid) },
	{ 0x702a6e64, __VMLINUX_SYMBOL_STR(drm_connector_cleanup) },
	{ 0xb1176e3b, __VMLINUX_SYMBOL_STR(drm_fb_helper_unregister_fbi) },
	{ 0xc631580a, __VMLINUX_SYMBOL_STR(console_unlock) },
	{ 0xfa22139c, __VMLINUX_SYMBOL_STR(drm_fb_helper_pan_display) },
	{ 0x7539f0f6, __VMLINUX_SYMBOL_STR(ttm_mem_global_init) },
	{ 0x1beb4114, __VMLINUX_SYMBOL_STR(drm_helper_connector_dpms) },
	{ 0x6671cba6, __VMLINUX_SYMBOL_STR(drm_fb_helper_set_suspend) },
	{ 0xb607480f, __VMLINUX_SYMBOL_STR(ttm_mem_global_release) },
	{ 0x672f6cee, __VMLINUX_SYMBOL_STR(drm_mode_connector_attach_encoder) },
	{ 0xff7559e4, __VMLINUX_SYMBOL_STR(ioport_resource) },
	{ 0x7fb8251a, __VMLINUX_SYMBOL_STR(ttm_bo_unref) },
	{ 0xe81ef1dd, __VMLINUX_SYMBOL_STR(remove_conflicting_framebuffers) },
	{ 0x1916e38c, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0x4d73cd91, __VMLINUX_SYMBOL_STR(ttm_bo_add_to_lru) },
	{ 0xf1fa7158, __VMLINUX_SYMBOL_STR(mutex_lock_interruptible) },
	{ 0x4e0dca7a, __VMLINUX_SYMBOL_STR(drm_helper_mode_fill_fb_struct) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x3a5d0a75, __VMLINUX_SYMBOL_STR(drm_put_dev) },
	{ 0xe35e888e, __VMLINUX_SYMBOL_STR(drm_gem_handle_create) },
	{ 0xf940ec6, __VMLINUX_SYMBOL_STR(drm_gem_dumb_destroy) },
	{ 0x30b42f69, __VMLINUX_SYMBOL_STR(ttm_bo_kmap) },
	{ 0x880db811, __VMLINUX_SYMBOL_STR(drm_fb_helper_fill_var) },
	{ 0x742620dc, __VMLINUX_SYMBOL_STR(ttm_tt_init) },
	{ 0xfbaaf01e, __VMLINUX_SYMBOL_STR(console_lock) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x1081a331, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x66b92003, __VMLINUX_SYMBOL_STR(drm_gem_object_release) },
	{ 0x9f8150cd, __VMLINUX_SYMBOL_STR(drm_read) },
	{ 0x841c79f8, __VMLINUX_SYMBOL_STR(ttm_bo_dma_acc_size) },
	{ 0xf1ec5cf6, __VMLINUX_SYMBOL_STR(ttm_bo_init_mm) },
	{ 0xe67e6b5c, __VMLINUX_SYMBOL_STR(ttm_bo_device_init) },
	{ 0x4ecb3123, __VMLINUX_SYMBOL_STR(drm_fb_helper_release_fbi) },
	{ 0x1dd71f7a, __VMLINUX_SYMBOL_STR(drm_err) },
	{ 0x5c15bab1, __VMLINUX_SYMBOL_STR(drm_connector_init) },
	{ 0xb017683d, __VMLINUX_SYMBOL_STR(drm_kms_helper_poll_enable) },
	{ 0x9014e689, __VMLINUX_SYMBOL_STR(drm_fb_helper_prepare) },
	{ 0x20645642, __VMLINUX_SYMBOL_STR(drm_debug) },
	{ 0x4ea1f5a2, __VMLINUX_SYMBOL_STR(drm_gem_object_free) },
	{ 0x2f665a27, __VMLINUX_SYMBOL_STR(drm_ioctl) },
	{ 0x1825f583, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_imageblit) },
	{ 0x42c8de35, __VMLINUX_SYMBOL_STR(ioremap_nocache) },
	{ 0xeb740b72, __VMLINUX_SYMBOL_STR(drm_framebuffer_unregister_private) },
	{ 0xcd5fffd6, __VMLINUX_SYMBOL_STR(ttm_bo_del_sub_from_lru) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x9e728653, __VMLINUX_SYMBOL_STR(drm_fb_helper_check_var) },
	{ 0xe50becaf, __VMLINUX_SYMBOL_STR(drm_fb_helper_blank) },
	{ 0x318e6ce8, __VMLINUX_SYMBOL_STR(drm_get_pci_dev) },
	{ 0xd71e0d4a, __VMLINUX_SYMBOL_STR(drm_crtc_send_vblank_event) },
	{ 0xfe355749, __VMLINUX_SYMBOL_STR(drm_gem_object_lookup) },
	{ 0x645ab792, __VMLINUX_SYMBOL_STR(drm_add_modes_noedid) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0x7c61340c, __VMLINUX_SYMBOL_STR(__release_region) },
	{ 0xe69002d6, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x7ba754c9, __VMLINUX_SYMBOL_STR(drm_fb_helper_alloc_fbi) },
	{ 0xe259ae9e, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x2e6aaeec, __VMLINUX_SYMBOL_STR(drm_crtc_init) },
	{ 0x680ec266, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0x2dc82fdc, __VMLINUX_SYMBOL_STR(drm_gem_object_init) },
	{ 0x60cd4b4f, __VMLINUX_SYMBOL_STR(drm_encoder_cleanup) },
	{ 0x98352797, __VMLINUX_SYMBOL_STR(ttm_bo_device_release) },
	{ 0x80807b5a, __VMLINUX_SYMBOL_STR(drm_crtc_cleanup) },
	{ 0xdf08bef9, __VMLINUX_SYMBOL_STR(drm_mode_config_init) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0xedc03953, __VMLINUX_SYMBOL_STR(iounmap) },
	{ 0x347c6bcf, __VMLINUX_SYMBOL_STR(ww_mutex_unlock) },
	{ 0x34cecded, __VMLINUX_SYMBOL_STR(drm_fb_helper_fini) },
	{ 0xd43c1660, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_fillrect) },
	{ 0x564e1aee, __VMLINUX_SYMBOL_STR(ttm_bo_global_init) },
	{ 0x289c6ba0, __VMLINUX_SYMBOL_STR(ttm_bo_manager_func) },
	{ 0xd9646c61, __VMLINUX_SYMBOL_STR(drm_helper_disable_unused_functions) },
	{ 0x97f3bb48, __VMLINUX_SYMBOL_STR(drm_fb_helper_setcmap) },
	{ 0xa8ab39a3, __VMLINUX_SYMBOL_STR(drm_pci_init) },
	{ 0x745b2bdc, __VMLINUX_SYMBOL_STR(drm_framebuffer_init) },
	{ 0xc360e7e2, __VMLINUX_SYMBOL_STR(drm_ut_debug_printk) },
	{ 0x26aad287, __VMLINUX_SYMBOL_STR(drm_vma_node_is_allowed) },
	{ 0xeb9cdaab, __VMLINUX_SYMBOL_STR(ttm_pool_unpopulate) },
	{ 0xfa87fe58, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_copyarea) },
	{ 0x60f8d0bd, __VMLINUX_SYMBOL_STR(drm_fb_helper_fill_fix) },
	{ 0x3e4a4621, __VMLINUX_SYMBOL_STR(drm_connector_register) },
	{ 0x3ac1fef9, __VMLINUX_SYMBOL_STR(drm_mode_legacy_fb_format) },
	{ 0xb5e1a8c5, __VMLINUX_SYMBOL_STR(drm_mode_crtc_set_gamma_size) },
	{ 0xa109c5ff, __VMLINUX_SYMBOL_STR(drm_kms_helper_poll_disable) },
	{ 0x4e8dd264, __VMLINUX_SYMBOL_STR(ttm_bo_global_release) },
	{ 0x680fdd20, __VMLINUX_SYMBOL_STR(drm_mode_object_find) },
	{ 0x47c68e03, __VMLINUX_SYMBOL_STR(drm_poll) },
	{ 0xab397e67, __VMLINUX_SYMBOL_STR(pci_request_region) },
	{ 0x134a265d, __VMLINUX_SYMBOL_STR(drm_fb_helper_init) },
	{ 0x574907aa, __VMLINUX_SYMBOL_STR(drm_fb_helper_single_add_all_connectors) },
	{ 0x801fa0e0, __VMLINUX_SYMBOL_STR(drm_open) },
	{ 0xb5540008, __VMLINUX_SYMBOL_STR(drm_global_item_unref) },
	{ 0x7729dcad, __VMLINUX_SYMBOL_STR(drm_framebuffer_cleanup) },
	{ 0xd279edba, __VMLINUX_SYMBOL_STR(ttm_bo_mmap) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=drm,drm_kms_helper,ttm";

MODULE_ALIAS("pci:v00001234d00001111sv00001AF4sd00001100bc*sc*i*");
MODULE_ALIAS("pci:v00001234d00001111sv*sd*bc*sc*i*");
