#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x5e862211, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x61b7b126, __VMLINUX_SYMBOL_STR(simple_strtoull) },
	{ 0x65bcd022, __VMLINUX_SYMBOL_STR(kobject_put) },
	{ 0x45be7858, __VMLINUX_SYMBOL_STR(kset_create_and_add) },
	{ 0x82658ed5, __VMLINUX_SYMBOL_STR(ore_get_io_state) },
	{ 0xae405b5f, __VMLINUX_SYMBOL_STR(kmem_cache_destroy) },
	{ 0x762485, __VMLINUX_SYMBOL_STR(iget_failed) },
	{ 0x7e104a81, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xcbcbfff2, __VMLINUX_SYMBOL_STR(drop_nlink) },
	{ 0x4353925b, __VMLINUX_SYMBOL_STR(osduld_device_same) },
	{ 0xdae80100, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0xb38cc013, __VMLINUX_SYMBOL_STR(generic_file_llseek) },
	{ 0xfbedcc9, __VMLINUX_SYMBOL_STR(ore_read) },
	{ 0x71d61c76, __VMLINUX_SYMBOL_STR(__mark_inode_dirty) },
	{ 0xbb37ee1b, __VMLINUX_SYMBOL_STR(__set_page_dirty_nobuffers) },
	{ 0x369b55d0, __VMLINUX_SYMBOL_STR(extract_attr_from_ios) },
	{ 0x754d539c, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0x60a13e90, __VMLINUX_SYMBOL_STR(rcu_barrier) },
	{ 0xb53c4429, __VMLINUX_SYMBOL_STR(filemap_write_and_wait_range) },
	{ 0xc17edb1, __VMLINUX_SYMBOL_STR(osd_sec_init_nosec_doall_caps) },
	{ 0xf1e3db94, __VMLINUX_SYMBOL_STR(simple_write_end) },
	{ 0x77653d24, __VMLINUX_SYMBOL_STR(generic_fh_to_parent) },
	{ 0x79aa04a2, __VMLINUX_SYMBOL_STR(get_random_bytes) },
	{ 0x23a9b726, __VMLINUX_SYMBOL_STR(is_bad_inode) },
	{ 0x67a0dbe9, __VMLINUX_SYMBOL_STR(pagecache_get_page) },
	{ 0xa18610e6, __VMLINUX_SYMBOL_STR(generic_file_open) },
	{ 0xacf4d843, __VMLINUX_SYMBOL_STR(match_strdup) },
	{ 0xa28e15de, __VMLINUX_SYMBOL_STR(__lock_page) },
	{ 0x77ae63d7, __VMLINUX_SYMBOL_STR(osd_req_read_kern) },
	{ 0x6f77ea85, __VMLINUX_SYMBOL_STR(dput) },
	{ 0x44e9a829, __VMLINUX_SYMBOL_STR(match_token) },
	{ 0xb502a63f, __VMLINUX_SYMBOL_STR(inc_nlink) },
	{ 0xec5c62d7, __VMLINUX_SYMBOL_STR(osduld_path_lookup) },
	{ 0xb5f05fbc, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x85df9b6c, __VMLINUX_SYMBOL_STR(strsep) },
	{ 0xe9e27675, __VMLINUX_SYMBOL_STR(vfs_fsync) },
	{ 0x767f7138, __VMLINUX_SYMBOL_STR(ore_put_io_state) },
	{ 0xd371f36d, __VMLINUX_SYMBOL_STR(page_symlink_inode_operations) },
	{ 0xd21418f5, __VMLINUX_SYMBOL_STR(generic_read_dir) },
	{ 0x4629334c, __VMLINUX_SYMBOL_STR(__preempt_count) },
	{ 0x28aa6a67, __VMLINUX_SYMBOL_STR(call_rcu) },
	{ 0x2c247c59, __VMLINUX_SYMBOL_STR(mount_nodev) },
	{ 0x45d5cac4, __VMLINUX_SYMBOL_STR(set_page_dirty) },
	{ 0x67883edb, __VMLINUX_SYMBOL_STR(ore_write) },
	{ 0x4b22bc76, __VMLINUX_SYMBOL_STR(truncate_setsize) },
	{ 0x405f6a4, __VMLINUX_SYMBOL_STR(end_page_writeback) },
	{ 0x9e88526, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0x6bda64f0, __VMLINUX_SYMBOL_STR(osduld_info_lookup) },
	{ 0x954648ec, __VMLINUX_SYMBOL_STR(__insert_inode_hash) },
	{ 0xe8ef0ff0, __VMLINUX_SYMBOL_STR(current_kernel_time64) },
	{ 0x955a832f, __VMLINUX_SYMBOL_STR(___preempt_schedule) },
	{ 0xbcf9c794, __VMLINUX_SYMBOL_STR(current_task) },
	{ 0x33467999, __VMLINUX_SYMBOL_STR(simple_write_begin) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x3971cde6, __VMLINUX_SYMBOL_STR(d_obtain_alias) },
	{ 0x449ad0a7, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0x7a9bdd3b, __VMLINUX_SYMBOL_STR(kobject_init_and_add) },
	{ 0x4c9d28b0, __VMLINUX_SYMBOL_STR(phys_base) },
	{ 0x4e000115, __VMLINUX_SYMBOL_STR(ore_check_io) },
	{ 0x9166fada, __VMLINUX_SYMBOL_STR(strncpy) },
	{ 0xe17f8bc8, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x2eb9e2f6, __VMLINUX_SYMBOL_STR(set_nlink) },
	{ 0x1081a331, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x7453e1b3, __VMLINUX_SYMBOL_STR(write_cache_pages) },
	{ 0xa8fe3038, __VMLINUX_SYMBOL_STR(osd_finalize_request) },
	{ 0xde70caf8, __VMLINUX_SYMBOL_STR(setattr_copy) },
	{ 0x7c0cc1ea, __VMLINUX_SYMBOL_STR(page_symlink) },
	{ 0x8172db07, __VMLINUX_SYMBOL_STR(truncate_pagecache) },
	{ 0x4e3567f7, __VMLINUX_SYMBOL_STR(match_int) },
	{ 0xb09abbe7, __VMLINUX_SYMBOL_STR(simple_symlink_inode_operations) },
	{ 0xb126bc85, __VMLINUX_SYMBOL_STR(unlock_page) },
	{ 0xf4b3a868, __VMLINUX_SYMBOL_STR(generic_file_read_iter) },
	{ 0x39a3dac0, __VMLINUX_SYMBOL_STR(inode_nohighmem) },
	{ 0x28806871, __VMLINUX_SYMBOL_STR(ore_verify_layout) },
	{ 0x5ac05f76, __VMLINUX_SYMBOL_STR(inode_init_once) },
	{ 0xd189bba9, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0xb5a87016, __VMLINUX_SYMBOL_STR(generic_file_mmap) },
	{ 0x6341aa0a, __VMLINUX_SYMBOL_STR(fs_kobj) },
	{ 0x5ef4612d, __VMLINUX_SYMBOL_STR(truncate_inode_pages_final) },
	{ 0x1fbc1f3, __VMLINUX_SYMBOL_STR(osduld_put_device) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x8095a12e, __VMLINUX_SYMBOL_STR(osd_start_request) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0xd62c833f, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0xbe7993ff, __VMLINUX_SYMBOL_STR(osd_end_request) },
	{ 0x3d9ee9f0, __VMLINUX_SYMBOL_STR(clear_page) },
	{ 0x7cc4d08b, __VMLINUX_SYMBOL_STR(unlock_new_inode) },
	{ 0x815f2897, __VMLINUX_SYMBOL_STR(empty_zero_page) },
	{ 0xddfd2ee1, __VMLINUX_SYMBOL_STR(bdi_setup_and_register) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0x263f355a, __VMLINUX_SYMBOL_STR(inode_change_ok) },
	{ 0xe69002d6, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xe259ae9e, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x3539f11b, __VMLINUX_SYMBOL_STR(match_strlcpy) },
	{ 0x757cff4f, __VMLINUX_SYMBOL_STR(read_cache_pages) },
	{ 0x7e9627d5, __VMLINUX_SYMBOL_STR(sync_inode_metadata) },
	{ 0x92234a23, __VMLINUX_SYMBOL_STR(kmem_cache_create) },
	{ 0x5595f1d4, __VMLINUX_SYMBOL_STR(register_filesystem) },
	{ 0xa6bbd805, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0xba0312fb, __VMLINUX_SYMBOL_STR(generic_file_write_iter) },
	{ 0x2207a57f, __VMLINUX_SYMBOL_STR(prepare_to_wait_event) },
	{ 0xfb629d7d, __VMLINUX_SYMBOL_STR(__test_set_page_writeback) },
	{ 0x1fd317c9, __VMLINUX_SYMBOL_STR(iter_file_splice_write) },
	{ 0xb2653640, __VMLINUX_SYMBOL_STR(kset_unregister) },
	{ 0x6d9c553c, __VMLINUX_SYMBOL_STR(ore_get_rw_state) },
	{ 0xbe3c71b5, __VMLINUX_SYMBOL_STR(iput) },
	{ 0x3e0106d4, __VMLINUX_SYMBOL_STR(read_cache_page) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x6a3ac611, __VMLINUX_SYMBOL_STR(ihold) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x4d7775a0, __VMLINUX_SYMBOL_STR(d_splice_alias) },
	{ 0x7ad3a1e9, __VMLINUX_SYMBOL_STR(ore_create) },
	{ 0x169b408a, __VMLINUX_SYMBOL_STR(d_make_root) },
	{ 0xf08242c2, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0xfa9fb7fd, __VMLINUX_SYMBOL_STR(bdi_destroy) },
	{ 0x7fbb8490, __VMLINUX_SYMBOL_STR(unregister_filesystem) },
	{ 0x920cf8c5, __VMLINUX_SYMBOL_STR(ore_truncate) },
	{ 0x84fe22ce, __VMLINUX_SYMBOL_STR(write_one_page) },
	{ 0x3cad0dce, __VMLINUX_SYMBOL_STR(init_special_inode) },
	{ 0x3e4184e5, __VMLINUX_SYMBOL_STR(ore_remove) },
	{ 0x28318305, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0x5db69c3d, __VMLINUX_SYMBOL_STR(new_inode) },
	{ 0xa776cab7, __VMLINUX_SYMBOL_STR(generic_file_splice_read) },
	{ 0xd703451d, __VMLINUX_SYMBOL_STR(generic_fh_to_dentry) },
	{ 0x6e574c0e, __VMLINUX_SYMBOL_STR(osduld_device_info) },
	{ 0x3263cff5, __VMLINUX_SYMBOL_STR(clear_inode) },
	{ 0x411550a6, __VMLINUX_SYMBOL_STR(d_instantiate) },
	{ 0xca2e77dd, __VMLINUX_SYMBOL_STR(osd_execute_request) },
	{ 0x748f1df7, __VMLINUX_SYMBOL_STR(__put_page) },
	{ 0x8e8e1bc1, __VMLINUX_SYMBOL_STR(iget_locked) },
	{ 0x7c2d098f, __VMLINUX_SYMBOL_STR(krealloc) },
	{ 0x19186a0e, __VMLINUX_SYMBOL_STR(inode_init_owner) },
	{ 0xea649269, __VMLINUX_SYMBOL_STR(generic_shutdown_super) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=libore,osd,libosd";

