#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x5e862211, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x42595e58, __VMLINUX_SYMBOL_STR(vgacon_text_force) },
	{ 0x8487a2b6, __VMLINUX_SYMBOL_STR(flush_work) },
	{ 0x2d3385d3, __VMLINUX_SYMBOL_STR(system_wq) },
	{ 0x2dcafc98, __VMLINUX_SYMBOL_STR(drm_gem_prime_export) },
	{ 0x91040120, __VMLINUX_SYMBOL_STR(drm_release) },
	{ 0xc6da18a8, __VMLINUX_SYMBOL_STR(drm_fb_helper_set_par) },
	{ 0x670a0972, __VMLINUX_SYMBOL_STR(ttm_pool_populate) },
	{ 0x3356b90b, __VMLINUX_SYMBOL_STR(cpu_tss) },
	{ 0x7e104a81, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xb2d524ee, __VMLINUX_SYMBOL_STR(ttm_dma_tt_init) },
	{ 0x4e8ce12f, __VMLINUX_SYMBOL_STR(drm_crtc_helper_set_config) },
	{ 0x172fddd1, __VMLINUX_SYMBOL_STR(drm_helper_resume_force_mode) },
	{ 0xdae80100, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0x2bd8b163, __VMLINUX_SYMBOL_STR(ttm_mem_io_reserve) },
	{ 0xd6ee688f, __VMLINUX_SYMBOL_STR(vmalloc) },
	{ 0x1e0c2be4, __VMLINUX_SYMBOL_STR(ioremap_wc) },
	{ 0xf8d3446d, __VMLINUX_SYMBOL_STR(ttm_bo_move_memcpy) },
	{ 0x4f8a6161, __VMLINUX_SYMBOL_STR(drm_fb_helper_initial_config) },
	{ 0x616bf458, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0x43a53735, __VMLINUX_SYMBOL_STR(__alloc_workqueue_key) },
	{ 0x7e9e62cb, __VMLINUX_SYMBOL_STR(drm_mode_config_cleanup) },
	{ 0x74c7662e, __VMLINUX_SYMBOL_STR(drm_pci_exit) },
	{ 0x1db7706b, __VMLINUX_SYMBOL_STR(__copy_user_nocache) },
	{ 0x2ec4577a, __VMLINUX_SYMBOL_STR(pci_disable_device) },
	{ 0x2471a95d, __VMLINUX_SYMBOL_STR(ttm_bo_validate) },
	{ 0x4e1ae247, __VMLINUX_SYMBOL_STR(drm_property_create_range) },
	{ 0x60600c23, __VMLINUX_SYMBOL_STR(ttm_bo_init) },
	{ 0x1f8d2ffb, __VMLINUX_SYMBOL_STR(drm_fb_helper_debug_leave) },
	{ 0xa2370afd, __VMLINUX_SYMBOL_STR(drm_cvt_mode) },
	{ 0xee0ad904, __VMLINUX_SYMBOL_STR(drm_helper_probe_single_connector_modes) },
	{ 0x802bde1c, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0x5d7318dc, __VMLINUX_SYMBOL_STR(drm_global_item_ref) },
	{ 0xe3b436fd, __VMLINUX_SYMBOL_STR(drm_vblank_cleanup) },
	{ 0xeae3dfd6, __VMLINUX_SYMBOL_STR(__const_udelay) },
	{ 0x4318d5b4, __VMLINUX_SYMBOL_STR(drm_kms_helper_hotplug_event) },
	{ 0xb5f05fbc, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x999e8297, __VMLINUX_SYMBOL_STR(vfree) },
	{ 0x2300953f, __VMLINUX_SYMBOL_STR(drm_vblank_init) },
	{ 0x21a701fe, __VMLINUX_SYMBOL_STR(fence_signal) },
	{ 0x6ba61e6a, __VMLINUX_SYMBOL_STR(drm_encoder_init) },
	{ 0xf66ecfa3, __VMLINUX_SYMBOL_STR(drm_object_property_set_value) },
	{ 0x4629334c, __VMLINUX_SYMBOL_STR(__preempt_count) },
	{ 0x7a2af7b4, __VMLINUX_SYMBOL_STR(cpu_number) },
	{ 0x61ef6170, __VMLINUX_SYMBOL_STR(__tracepoint_fence_emit) },
	{ 0x79bb0f5a, __VMLINUX_SYMBOL_STR(drm_pci_set_busid) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0x702a6e64, __VMLINUX_SYMBOL_STR(drm_connector_cleanup) },
	{ 0xb1176e3b, __VMLINUX_SYMBOL_STR(drm_fb_helper_unregister_fbi) },
	{ 0xcb238026, __VMLINUX_SYMBOL_STR(reservation_object_add_shared_fence) },
	{ 0xc631580a, __VMLINUX_SYMBOL_STR(console_unlock) },
	{ 0x9e88526, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0xfa22139c, __VMLINUX_SYMBOL_STR(drm_fb_helper_pan_display) },
	{ 0x7539f0f6, __VMLINUX_SYMBOL_STR(ttm_mem_global_init) },
	{ 0xd2335101, __VMLINUX_SYMBOL_STR(drm_fb_get_bpp_depth) },
	{ 0x955a832f, __VMLINUX_SYMBOL_STR(___preempt_schedule) },
	{ 0x1beb4114, __VMLINUX_SYMBOL_STR(drm_helper_connector_dpms) },
	{ 0x6671cba6, __VMLINUX_SYMBOL_STR(drm_fb_helper_set_suspend) },
	{ 0xfb578fc5, __VMLINUX_SYMBOL_STR(memset) },
	{ 0xb9724150, __VMLINUX_SYMBOL_STR(ttm_mem_io_lock) },
	{ 0xb607480f, __VMLINUX_SYMBOL_STR(ttm_mem_global_release) },
	{ 0x672f6cee, __VMLINUX_SYMBOL_STR(drm_mode_connector_attach_encoder) },
	{ 0xaea814bd, __VMLINUX_SYMBOL_STR(drm_irq_install) },
	{ 0x20900af5, __VMLINUX_SYMBOL_STR(ttm_mem_io_unlock) },
	{ 0x7fb8251a, __VMLINUX_SYMBOL_STR(ttm_bo_unref) },
	{ 0x49581969, __VMLINUX_SYMBOL_STR(pci_restore_state) },
	{ 0x98782fd0, __VMLINUX_SYMBOL_STR(dev_err) },
	{ 0x1916e38c, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0xbcf9c794, __VMLINUX_SYMBOL_STR(current_task) },
	{ 0x4d73cd91, __VMLINUX_SYMBOL_STR(ttm_bo_add_to_lru) },
	{ 0xf1fa7158, __VMLINUX_SYMBOL_STR(mutex_lock_interruptible) },
	{ 0x3d7149d9, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x4e0dca7a, __VMLINUX_SYMBOL_STR(drm_helper_mode_fill_fb_struct) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0xae21cc14, __VMLINUX_SYMBOL_STR(drm_object_attach_property) },
	{ 0xadf7e47c, __VMLINUX_SYMBOL_STR(__cpu_online_mask) },
	{ 0x3a5d0a75, __VMLINUX_SYMBOL_STR(drm_put_dev) },
	{ 0xe35e888e, __VMLINUX_SYMBOL_STR(drm_gem_handle_create) },
	{ 0xf940ec6, __VMLINUX_SYMBOL_STR(drm_gem_dumb_destroy) },
	{ 0x30b42f69, __VMLINUX_SYMBOL_STR(ttm_bo_kmap) },
	{ 0x880db811, __VMLINUX_SYMBOL_STR(drm_fb_helper_fill_var) },
	{ 0x225b8099, __VMLINUX_SYMBOL_STR(ttm_bo_evict_mm) },
	{ 0xfbaaf01e, __VMLINUX_SYMBOL_STR(console_lock) },
	{ 0xf709512e, __VMLINUX_SYMBOL_STR(drm_send_vblank_event) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x1081a331, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x393d4de9, __VMLINUX_SYMBOL_STR(crc32_le) },
	{ 0x8c03d20c, __VMLINUX_SYMBOL_STR(destroy_workqueue) },
	{ 0x84ffea8b, __VMLINUX_SYMBOL_STR(idr_preload) },
	{ 0x66b92003, __VMLINUX_SYMBOL_STR(drm_gem_object_release) },
	{ 0x9f8150cd, __VMLINUX_SYMBOL_STR(drm_read) },
	{ 0x2469810f, __VMLINUX_SYMBOL_STR(__rcu_read_unlock) },
	{ 0xf1ec5cf6, __VMLINUX_SYMBOL_STR(ttm_bo_init_mm) },
	{ 0x169e9b8a, __VMLINUX_SYMBOL_STR(ttm_bo_wait) },
	{ 0xa4fde00, __VMLINUX_SYMBOL_STR(idr_alloc) },
	{ 0xe67e6b5c, __VMLINUX_SYMBOL_STR(ttm_bo_device_init) },
	{ 0x4ecb3123, __VMLINUX_SYMBOL_STR(drm_fb_helper_release_fbi) },
	{ 0x87bdd3c, __VMLINUX_SYMBOL_STR(drm_debugfs_create_files) },
	{ 0x1dd71f7a, __VMLINUX_SYMBOL_STR(drm_err) },
	{ 0x5c15bab1, __VMLINUX_SYMBOL_STR(drm_connector_init) },
	{ 0xb017683d, __VMLINUX_SYMBOL_STR(drm_kms_helper_poll_enable) },
	{ 0x42160169, __VMLINUX_SYMBOL_STR(flush_workqueue) },
	{ 0x9014e689, __VMLINUX_SYMBOL_STR(drm_fb_helper_prepare) },
	{ 0xdf1427e5, __VMLINUX_SYMBOL_STR(idr_remove) },
	{ 0x20645642, __VMLINUX_SYMBOL_STR(drm_debug) },
	{ 0x7260e249, __VMLINUX_SYMBOL_STR(___preempt_schedule_notrace) },
	{ 0x4ea1f5a2, __VMLINUX_SYMBOL_STR(drm_gem_object_free) },
	{ 0x6d8e90c4, __VMLINUX_SYMBOL_STR(ttm_eu_backoff_reservation) },
	{ 0x61fc0ff1, __VMLINUX_SYMBOL_STR(drm_gem_prime_fd_to_handle) },
	{ 0x2f665a27, __VMLINUX_SYMBOL_STR(drm_ioctl) },
	{ 0x1825f583, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_imageblit) },
	{ 0xe0fe4b2a, __VMLINUX_SYMBOL_STR(drm_gem_prime_import) },
	{ 0x78764f4e, __VMLINUX_SYMBOL_STR(pv_irq_ops) },
	{ 0x81144f9d, __VMLINUX_SYMBOL_STR(idr_find_slowpath) },
	{ 0x42c8de35, __VMLINUX_SYMBOL_STR(ioremap_nocache) },
	{ 0x12a38747, __VMLINUX_SYMBOL_STR(usleep_range) },
	{ 0xcd5fffd6, __VMLINUX_SYMBOL_STR(ttm_bo_del_sub_from_lru) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x9e728653, __VMLINUX_SYMBOL_STR(drm_fb_helper_check_var) },
	{ 0x59aa14cf, __VMLINUX_SYMBOL_STR(fence_release) },
	{ 0xe50becaf, __VMLINUX_SYMBOL_STR(drm_fb_helper_blank) },
	{ 0xd62c833f, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0x489083ea, __VMLINUX_SYMBOL_STR(ttm_bo_kunmap) },
	{ 0x318e6ce8, __VMLINUX_SYMBOL_STR(drm_get_pci_dev) },
	{ 0xc7eb0ac3, __VMLINUX_SYMBOL_STR(drm_vblank_get) },
	{ 0xfe355749, __VMLINUX_SYMBOL_STR(drm_gem_object_lookup) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0xadc4320c, __VMLINUX_SYMBOL_STR(ttm_eu_reserve_buffers) },
	{ 0xe69002d6, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x7ba754c9, __VMLINUX_SYMBOL_STR(drm_fb_helper_alloc_fbi) },
	{ 0xe259ae9e, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x2e6aaeec, __VMLINUX_SYMBOL_STR(drm_crtc_init) },
	{ 0x680ec266, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0xddd1185e, __VMLINUX_SYMBOL_STR(drm_gem_prime_handle_to_fd) },
	{ 0xee9aae49, __VMLINUX_SYMBOL_STR(ttm_mem_io_free) },
	{ 0x99195078, __VMLINUX_SYMBOL_STR(vsnprintf) },
	{ 0xa6bbd805, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0x970c4501, __VMLINUX_SYMBOL_STR(drm_connector_unregister) },
	{ 0x2dc82fdc, __VMLINUX_SYMBOL_STR(drm_gem_object_init) },
	{ 0x60cd4b4f, __VMLINUX_SYMBOL_STR(drm_encoder_cleanup) },
	{ 0xf6a9feb8, __VMLINUX_SYMBOL_STR(pci_set_power_state) },
	{ 0x2207a57f, __VMLINUX_SYMBOL_STR(prepare_to_wait_event) },
	{ 0x6fd3e55e, __VMLINUX_SYMBOL_STR(fb_deferred_io_init) },
	{ 0x98352797, __VMLINUX_SYMBOL_STR(ttm_bo_device_release) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0x80807b5a, __VMLINUX_SYMBOL_STR(drm_crtc_cleanup) },
	{ 0xdf08bef9, __VMLINUX_SYMBOL_STR(drm_mode_config_init) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x89ae49f8, __VMLINUX_SYMBOL_STR(drm_mode_create_suggested_offset_properties) },
	{ 0x27b0bf12, __VMLINUX_SYMBOL_STR(ttm_dma_tt_fini) },
	{ 0xe6279dfd, __VMLINUX_SYMBOL_STR(drm_helper_hpd_irq_event) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0xedc03953, __VMLINUX_SYMBOL_STR(iounmap) },
	{ 0x347c6bcf, __VMLINUX_SYMBOL_STR(ww_mutex_unlock) },
	{ 0xd2064e2f, __VMLINUX_SYMBOL_STR(idr_replace) },
	{ 0xc401283, __VMLINUX_SYMBOL_STR(drm_debugfs_remove_files) },
	{ 0x34cecded, __VMLINUX_SYMBOL_STR(drm_fb_helper_fini) },
	{ 0x873c28b1, __VMLINUX_SYMBOL_STR(drm_modeset_lock_all) },
	{ 0xf08242c2, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0x9b645614, __VMLINUX_SYMBOL_STR(dev_warn) },
	{ 0xd43c1660, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_fillrect) },
	{ 0x564e1aee, __VMLINUX_SYMBOL_STR(ttm_bo_global_init) },
	{ 0x3e2ffc78, __VMLINUX_SYMBOL_STR(drm_mode_probed_add) },
	{ 0x2e0d2f7f, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0x289c6ba0, __VMLINUX_SYMBOL_STR(ttm_bo_manager_func) },
	{ 0xb97c60f9, __VMLINUX_SYMBOL_STR(drm_modeset_unlock_all) },
	{ 0x97f3bb48, __VMLINUX_SYMBOL_STR(drm_fb_helper_setcmap) },
	{ 0xa8ab39a3, __VMLINUX_SYMBOL_STR(drm_pci_init) },
	{ 0xa7281554, __VMLINUX_SYMBOL_STR(reservation_object_reserve_shared) },
	{ 0x745b2bdc, __VMLINUX_SYMBOL_STR(drm_framebuffer_init) },
	{ 0x16dc4d1f, __VMLINUX_SYMBOL_STR(fence_init) },
	{ 0xc360e7e2, __VMLINUX_SYMBOL_STR(drm_ut_debug_printk) },
	{ 0x454eb7c7, __VMLINUX_SYMBOL_STR(drm_kms_helper_poll_init) },
	{ 0x26aad287, __VMLINUX_SYMBOL_STR(drm_vma_node_is_allowed) },
	{ 0x5fb2e8ef, __VMLINUX_SYMBOL_STR(idr_init) },
	{ 0x8d522714, __VMLINUX_SYMBOL_STR(__rcu_read_lock) },
	{ 0xeb9cdaab, __VMLINUX_SYMBOL_STR(ttm_pool_unpopulate) },
	{ 0xb37e1ee6, __VMLINUX_SYMBOL_STR(pci_enable_device) },
	{ 0xfa87fe58, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_copyarea) },
	{ 0x4f6b400b, __VMLINUX_SYMBOL_STR(_copy_from_user) },
	{ 0x60f8d0bd, __VMLINUX_SYMBOL_STR(drm_fb_helper_fill_fix) },
	{ 0x3e4a4621, __VMLINUX_SYMBOL_STR(drm_connector_register) },
	{ 0x3ac1fef9, __VMLINUX_SYMBOL_STR(drm_mode_legacy_fb_format) },
	{ 0xd5ee2b9f, __VMLINUX_SYMBOL_STR(ttm_bo_clean_mm) },
	{ 0xb5e1a8c5, __VMLINUX_SYMBOL_STR(drm_mode_crtc_set_gamma_size) },
	{ 0xa109c5ff, __VMLINUX_SYMBOL_STR(drm_kms_helper_poll_disable) },
	{ 0x565f2e1f, __VMLINUX_SYMBOL_STR(drm_vblank_put) },
	{ 0x4e8dd264, __VMLINUX_SYMBOL_STR(ttm_bo_global_release) },
	{ 0x49804bc4, __VMLINUX_SYMBOL_STR(drm_fb_helper_debug_enter) },
	{ 0x47c68e03, __VMLINUX_SYMBOL_STR(drm_poll) },
	{ 0xd38de907, __VMLINUX_SYMBOL_STR(drm_mm_dump_table) },
	{ 0x134a265d, __VMLINUX_SYMBOL_STR(drm_fb_helper_init) },
	{ 0x574907aa, __VMLINUX_SYMBOL_STR(drm_fb_helper_single_add_all_connectors) },
	{ 0x801fa0e0, __VMLINUX_SYMBOL_STR(drm_open) },
	{ 0xf9a516bb, __VMLINUX_SYMBOL_STR(pci_save_state) },
	{ 0xb5540008, __VMLINUX_SYMBOL_STR(drm_global_item_unref) },
	{ 0x7729dcad, __VMLINUX_SYMBOL_STR(drm_framebuffer_cleanup) },
	{ 0xd279edba, __VMLINUX_SYMBOL_STR(ttm_bo_mmap) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=drm,drm_kms_helper,ttm";

MODULE_ALIAS("pci:v00001B36d00000100sv*sd*bc03sc00i*");
MODULE_ALIAS("pci:v00001B36d00000100sv*sd*bc03sc80i*");
