#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x5e862211, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x91040120, __VMLINUX_SYMBOL_STR(drm_release) },
	{ 0xdb5f6987, __VMLINUX_SYMBOL_STR(drm_prime_gem_destroy) },
	{ 0xc6da18a8, __VMLINUX_SYMBOL_STR(drm_fb_helper_set_par) },
	{ 0x7e104a81, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x4e8ce12f, __VMLINUX_SYMBOL_STR(drm_crtc_helper_set_config) },
	{ 0x5aadc0dc, __VMLINUX_SYMBOL_STR(drm_dev_register) },
	{ 0x91c0e5ad, __VMLINUX_SYMBOL_STR(drm_compat_ioctl) },
	{ 0xfaa42c5b, __VMLINUX_SYMBOL_STR(drm_connector_unplug_all) },
	{ 0x510394e2, __VMLINUX_SYMBOL_STR(drm_gem_put_pages) },
	{ 0x1ed02f33, __VMLINUX_SYMBOL_STR(drm_dev_alloc) },
	{ 0x4f8a6161, __VMLINUX_SYMBOL_STR(drm_fb_helper_initial_config) },
	{ 0x7aa1756e, __VMLINUX_SYMBOL_STR(kvfree) },
	{ 0x616bf458, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0x62b3b5ce, __VMLINUX_SYMBOL_STR(drm_gem_dmabuf_release) },
	{ 0x7e9e62cb, __VMLINUX_SYMBOL_STR(drm_mode_config_cleanup) },
	{ 0x56b731eb, __VMLINUX_SYMBOL_STR(drm_unplug_dev) },
	{ 0x2a9d94cf, __VMLINUX_SYMBOL_STR(drm_fb_helper_unlink_fbi) },
	{ 0x6b9bda7f, __VMLINUX_SYMBOL_STR(boot_cpu_data) },
	{ 0x15601f89, __VMLINUX_SYMBOL_STR(dma_buf_detach) },
	{ 0x1f8d2ffb, __VMLINUX_SYMBOL_STR(drm_fb_helper_debug_leave) },
	{ 0x6b06fdce, __VMLINUX_SYMBOL_STR(delayed_work_timer_fn) },
	{ 0x6dc0c9dc, __VMLINUX_SYMBOL_STR(down_interruptible) },
	{ 0xee0ad904, __VMLINUX_SYMBOL_STR(drm_helper_probe_single_connector_modes) },
	{ 0x3fec048f, __VMLINUX_SYMBOL_STR(sg_next) },
	{ 0x91cf5c2d, __VMLINUX_SYMBOL_STR(drm_gem_free_mmap_offset) },
	{ 0xe3b436fd, __VMLINUX_SYMBOL_STR(drm_vblank_cleanup) },
	{ 0x9580deb, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0xb5f05fbc, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x27436bee, __VMLINUX_SYMBOL_STR(drm_dev_unref) },
	{ 0x2300953f, __VMLINUX_SYMBOL_STR(drm_vblank_init) },
	{ 0x6ba61e6a, __VMLINUX_SYMBOL_STR(drm_encoder_init) },
	{ 0x4629334c, __VMLINUX_SYMBOL_STR(__preempt_count) },
	{ 0x702a6e64, __VMLINUX_SYMBOL_STR(drm_connector_cleanup) },
	{ 0xb1176e3b, __VMLINUX_SYMBOL_STR(drm_fb_helper_unregister_fbi) },
	{ 0xd703e0b4, __VMLINUX_SYMBOL_STR(dma_buf_vunmap) },
	{ 0xe9acd29e, __VMLINUX_SYMBOL_STR(usb_get_descriptor) },
	{ 0xfa22139c, __VMLINUX_SYMBOL_STR(drm_fb_helper_pan_display) },
	{ 0x50d1f870, __VMLINUX_SYMBOL_STR(pgprot_writecombine) },
	{ 0x1beb4114, __VMLINUX_SYMBOL_STR(drm_helper_connector_dpms) },
	{ 0xfb578fc5, __VMLINUX_SYMBOL_STR(memset) },
	{ 0x672f6cee, __VMLINUX_SYMBOL_STR(drm_mode_connector_attach_encoder) },
	{ 0x3744cf36, __VMLINUX_SYMBOL_STR(vmalloc_to_pfn) },
	{ 0x1916e38c, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0xe2904ae, __VMLINUX_SYMBOL_STR(drm_prime_pages_to_sg) },
	{ 0x43ebfc0b, __VMLINUX_SYMBOL_STR(usb_deregister) },
	{ 0x4e0dca7a, __VMLINUX_SYMBOL_STR(drm_helper_mode_fill_fb_struct) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0xae21cc14, __VMLINUX_SYMBOL_STR(drm_object_attach_property) },
	{ 0xe35e888e, __VMLINUX_SYMBOL_STR(drm_gem_handle_create) },
	{ 0xf940ec6, __VMLINUX_SYMBOL_STR(drm_gem_dumb_destroy) },
	{ 0x9ea6c46c, __VMLINUX_SYMBOL_STR(vmap) },
	{ 0x7d81d2de, __VMLINUX_SYMBOL_STR(dma_buf_put) },
	{ 0x880db811, __VMLINUX_SYMBOL_STR(drm_fb_helper_fill_var) },
	{ 0x5c97b352, __VMLINUX_SYMBOL_STR(usb_control_msg) },
	{ 0xf709512e, __VMLINUX_SYMBOL_STR(drm_send_vblank_event) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x1081a331, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x66b92003, __VMLINUX_SYMBOL_STR(drm_gem_object_release) },
	{ 0x9f8150cd, __VMLINUX_SYMBOL_STR(drm_read) },
	{ 0x95ba9e29, __VMLINUX_SYMBOL_STR(noop_llseek) },
	{ 0x8aa778d0, __VMLINUX_SYMBOL_STR(drm_add_edid_modes) },
	{ 0x4ecb3123, __VMLINUX_SYMBOL_STR(drm_fb_helper_release_fbi) },
	{ 0x84a1beb0, __VMLINUX_SYMBOL_STR(dma_buf_unmap_attachment) },
	{ 0x519b3309, __VMLINUX_SYMBOL_STR(usb_free_coherent) },
	{ 0x1dd71f7a, __VMLINUX_SYMBOL_STR(drm_err) },
	{ 0x5c15bab1, __VMLINUX_SYMBOL_STR(drm_connector_init) },
	{ 0x9014e689, __VMLINUX_SYMBOL_STR(drm_fb_helper_prepare) },
	{ 0xe35252f5, __VMLINUX_SYMBOL_STR(drm_gem_vm_open) },
	{ 0x47dc8aa8, __VMLINUX_SYMBOL_STR(drm_mode_connector_update_edid_property) },
	{ 0xd786f5e8, __VMLINUX_SYMBOL_STR(vm_insert_page) },
	{ 0x3ca0957, __VMLINUX_SYMBOL_STR(drm_gem_vm_close) },
	{ 0x20645642, __VMLINUX_SYMBOL_STR(drm_debug) },
	{ 0x4ea1f5a2, __VMLINUX_SYMBOL_STR(drm_gem_object_free) },
	{ 0x9c491f60, __VMLINUX_SYMBOL_STR(sg_alloc_table) },
	{ 0x61fc0ff1, __VMLINUX_SYMBOL_STR(drm_gem_prime_fd_to_handle) },
	{ 0x2941b6ec, __VMLINUX_SYMBOL_STR(dma_buf_begin_cpu_access) },
	{ 0x2f665a27, __VMLINUX_SYMBOL_STR(drm_ioctl) },
	{ 0x1825f583, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_imageblit) },
	{ 0x84e80a1e, __VMLINUX_SYMBOL_STR(usb_submit_urb) },
	{ 0x5f561843, __VMLINUX_SYMBOL_STR(drm_gem_mmap) },
	{ 0x246b8af5, __VMLINUX_SYMBOL_STR(dma_buf_map_attachment) },
	{ 0x7f5ed45f, __VMLINUX_SYMBOL_STR(dma_buf_export) },
	{ 0x5944d015, __VMLINUX_SYMBOL_STR(__cachemode2pte_tbl) },
	{ 0xeb740b72, __VMLINUX_SYMBOL_STR(drm_framebuffer_unregister_private) },
	{ 0x4fb9f94, __VMLINUX_SYMBOL_STR(put_device) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x9e728653, __VMLINUX_SYMBOL_STR(drm_fb_helper_check_var) },
	{ 0xe50becaf, __VMLINUX_SYMBOL_STR(drm_fb_helper_blank) },
	{ 0xfe355749, __VMLINUX_SYMBOL_STR(drm_gem_object_lookup) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0xe69002d6, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x7ba754c9, __VMLINUX_SYMBOL_STR(drm_fb_helper_alloc_fbi) },
	{ 0x2e6aaeec, __VMLINUX_SYMBOL_STR(drm_crtc_init) },
	{ 0x680ec266, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0x4ef1f3e, __VMLINUX_SYMBOL_STR(dma_buf_attach) },
	{ 0xddd1185e, __VMLINUX_SYMBOL_STR(drm_gem_prime_handle_to_fd) },
	{ 0x8dfc89f0, __VMLINUX_SYMBOL_STR(get_device) },
	{ 0x970c4501, __VMLINUX_SYMBOL_STR(drm_connector_unregister) },
	{ 0x2dc82fdc, __VMLINUX_SYMBOL_STR(drm_gem_object_init) },
	{ 0x60cd4b4f, __VMLINUX_SYMBOL_STR(drm_encoder_cleanup) },
	{ 0x8b65b399, __VMLINUX_SYMBOL_STR(fb_deferred_io_cleanup) },
	{ 0x6fd3e55e, __VMLINUX_SYMBOL_STR(fb_deferred_io_init) },
	{ 0xe403b468, __VMLINUX_SYMBOL_STR(drm_gem_create_mmap_offset) },
	{ 0x4d3e6112, __VMLINUX_SYMBOL_STR(drm_mode_create_dirty_info_property) },
	{ 0x80807b5a, __VMLINUX_SYMBOL_STR(drm_crtc_cleanup) },
	{ 0xa9bd2676, __VMLINUX_SYMBOL_STR(__vmalloc) },
	{ 0xdf08bef9, __VMLINUX_SYMBOL_STR(drm_mode_config_init) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x94961283, __VMLINUX_SYMBOL_STR(vunmap) },
	{ 0x37176ede, __VMLINUX_SYMBOL_STR(remap_pfn_range) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x78e739aa, __VMLINUX_SYMBOL_STR(up) },
	{ 0x552ae03a, __VMLINUX_SYMBOL_STR(usb_register_driver) },
	{ 0x34cecded, __VMLINUX_SYMBOL_STR(drm_fb_helper_fini) },
	{ 0x873c28b1, __VMLINUX_SYMBOL_STR(drm_modeset_lock_all) },
	{ 0xb1645a2e, __VMLINUX_SYMBOL_STR(sg_free_table) },
	{ 0x494e3393, __VMLINUX_SYMBOL_STR(vm_get_page_prot) },
	{ 0xb69751a5, __VMLINUX_SYMBOL_STR(drm_prime_sg_to_page_addr_arrays) },
	{ 0xd43c1660, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_fillrect) },
	{ 0xb97c60f9, __VMLINUX_SYMBOL_STR(drm_modeset_unlock_all) },
	{ 0xd9646c61, __VMLINUX_SYMBOL_STR(drm_helper_disable_unused_functions) },
	{ 0x98ee2266, __VMLINUX_SYMBOL_STR(dma_buf_end_cpu_access) },
	{ 0x97f3bb48, __VMLINUX_SYMBOL_STR(drm_fb_helper_setcmap) },
	{ 0xc3f61831, __VMLINUX_SYMBOL_STR(usb_alloc_coherent) },
	{ 0x745b2bdc, __VMLINUX_SYMBOL_STR(drm_framebuffer_init) },
	{ 0xc360e7e2, __VMLINUX_SYMBOL_STR(drm_ut_debug_printk) },
	{ 0xf7b36c8a, __VMLINUX_SYMBOL_STR(dma_buf_vmap) },
	{ 0xfa87fe58, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_copyarea) },
	{ 0xd9af73a6, __VMLINUX_SYMBOL_STR(drm_gem_get_pages) },
	{ 0x60f8d0bd, __VMLINUX_SYMBOL_STR(drm_fb_helper_fill_fix) },
	{ 0x3e4a4621, __VMLINUX_SYMBOL_STR(drm_connector_register) },
	{ 0x3ac1fef9, __VMLINUX_SYMBOL_STR(drm_mode_legacy_fb_format) },
	{ 0xd70a2bf5, __VMLINUX_SYMBOL_STR(usb_free_urb) },
	{ 0x6388591c, __VMLINUX_SYMBOL_STR(down_timeout) },
	{ 0xa109c5ff, __VMLINUX_SYMBOL_STR(drm_kms_helper_poll_disable) },
	{ 0x680fdd20, __VMLINUX_SYMBOL_STR(drm_mode_object_find) },
	{ 0x49804bc4, __VMLINUX_SYMBOL_STR(drm_fb_helper_debug_enter) },
	{ 0x47c68e03, __VMLINUX_SYMBOL_STR(drm_poll) },
	{ 0x2b04fec, __VMLINUX_SYMBOL_STR(dma_ops) },
	{ 0x134a265d, __VMLINUX_SYMBOL_STR(drm_fb_helper_init) },
	{ 0x574907aa, __VMLINUX_SYMBOL_STR(drm_fb_helper_single_add_all_connectors) },
	{ 0x25a4dd41, __VMLINUX_SYMBOL_STR(usb_alloc_urb) },
	{ 0x801fa0e0, __VMLINUX_SYMBOL_STR(drm_open) },
	{ 0x7729dcad, __VMLINUX_SYMBOL_STR(drm_framebuffer_cleanup) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=drm,drm_kms_helper,usbcore";

MODULE_ALIAS("usb:v17E9p*d*dc*dsc*dp*icFFisc00ip00in*");
