#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x5e862211, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x8487a2b6, __VMLINUX_SYMBOL_STR(flush_work) },
	{ 0x2d3385d3, __VMLINUX_SYMBOL_STR(system_wq) },
	{ 0x68f3a30f, __VMLINUX_SYMBOL_STR(drm_atomic_get_connector_state) },
	{ 0x7e104a81, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xd1a70d1a, __VMLINUX_SYMBOL_STR(drm_atomic_legacy_backoff) },
	{ 0xfd60df2, __VMLINUX_SYMBOL_STR(drm_get_connector_status_name) },
	{ 0xb98563c, __VMLINUX_SYMBOL_STR(drm_calc_timestamping_constants) },
	{ 0xde5d0cb5, __VMLINUX_SYMBOL_STR(drm_get_edid) },
	{ 0x55709b41, __VMLINUX_SYMBOL_STR(drm_crtc_index) },
	{ 0x91fec1cc, __VMLINUX_SYMBOL_STR(drm_rect_calc_vscale) },
	{ 0x349cba85, __VMLINUX_SYMBOL_STR(strchr) },
	{ 0x2ca2a501, __VMLINUX_SYMBOL_STR(drm_framebuffer_reference) },
	{ 0x616bf458, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0xdd3d0bac, __VMLINUX_SYMBOL_STR(drm_bridge_disable) },
	{ 0xc78bba75, __VMLINUX_SYMBOL_STR(drm_edid_to_eld) },
	{ 0x12602e55, __VMLINUX_SYMBOL_STR(drm_mode_create_from_cmdline_mode) },
	{ 0x754d539c, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0xdeae2349, __VMLINUX_SYMBOL_STR(framebuffer_release) },
	{ 0x477c807c, __VMLINUX_SYMBOL_STR(drm_modeset_drop_locks) },
	{ 0xad992359, __VMLINUX_SYMBOL_STR(drm_bridge_pre_enable) },
	{ 0x7705c3cd, __VMLINUX_SYMBOL_STR(unlink_framebuffer) },
	{ 0x43dd11c, __VMLINUX_SYMBOL_STR(drm_mode_config_reset) },
	{ 0x2f117c55, __VMLINUX_SYMBOL_STR(drm_atomic_state_clear) },
	{ 0xa95d4dee, __VMLINUX_SYMBOL_STR(drm_mode_destroy) },
	{ 0x4d974b9c, __VMLINUX_SYMBOL_STR(register_sysrq_key) },
	{ 0x24fe7e30, __VMLINUX_SYMBOL_STR(drm_atomic_get_plane_state) },
	{ 0xe8101219, __VMLINUX_SYMBOL_STR(fb_sys_read) },
	{ 0xf1421d13, __VMLINUX_SYMBOL_STR(drm_mode_sort) },
	{ 0x50e86dcd, __VMLINUX_SYMBOL_STR(drm_modeset_backoff) },
	{ 0x6b06fdce, __VMLINUX_SYMBOL_STR(delayed_work_timer_fn) },
	{ 0x57ba72ab, __VMLINUX_SYMBOL_STR(fence_wait_timeout) },
	{ 0x802bde1c, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0x448eac3e, __VMLINUX_SYMBOL_STR(kmemdup) },
	{ 0xeae3dfd6, __VMLINUX_SYMBOL_STR(__const_udelay) },
	{ 0x1b63457e, __VMLINUX_SYMBOL_STR(cfb_fillrect) },
	{ 0xf6e679b, __VMLINUX_SYMBOL_STR(param_ops_bool) },
	{ 0x9580deb, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0xa57863e, __VMLINUX_SYMBOL_STR(cancel_delayed_work_sync) },
	{ 0xb5f05fbc, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x85df9b6c, __VMLINUX_SYMBOL_STR(strsep) },
	{ 0xee642c0c, __VMLINUX_SYMBOL_STR(drm_plane_force_disable) },
	{ 0x8074028d, __VMLINUX_SYMBOL_STR(platform_device_register_full) },
	{ 0x75bb0ccb, __VMLINUX_SYMBOL_STR(drm_modeset_acquire_fini) },
	{ 0xf66ecfa3, __VMLINUX_SYMBOL_STR(drm_object_property_set_value) },
	{ 0x8348eb15, __VMLINUX_SYMBOL_STR(sys_copyarea) },
	{ 0xcf18a8b2, __VMLINUX_SYMBOL_STR(drm_mode_validate_basic) },
	{ 0xffc6c87a, __VMLINUX_SYMBOL_STR(drm_detect_monitor_audio) },
	{ 0xc499ae1e, __VMLINUX_SYMBOL_STR(kstrdup) },
	{ 0x96d4af68, __VMLINUX_SYMBOL_STR(drm_universal_plane_init) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0x722e1fd8, __VMLINUX_SYMBOL_STR(drm_atomic_set_mode_prop_for_crtc) },
	{ 0xb9f9ae95, __VMLINUX_SYMBOL_STR(i2c_add_adapter) },
	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
	{ 0x131db64a, __VMLINUX_SYMBOL_STR(system_long_wq) },
	{ 0x6c7a01fa, __VMLINUX_SYMBOL_STR(param_ops_string) },
	{ 0xe5e6fb2a, __VMLINUX_SYMBOL_STR(drm_atomic_set_mode_for_crtc) },
	{ 0x71c48bd9, __VMLINUX_SYMBOL_STR(fb_set_suspend) },
	{ 0x9e88526, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0xcb2340b8, __VMLINUX_SYMBOL_STR(drm_rect_debug_print) },
	{ 0xd2335101, __VMLINUX_SYMBOL_STR(drm_fb_get_bpp_depth) },
	{ 0x59ef50f0, __VMLINUX_SYMBOL_STR(drm_edid_block_valid) },
	{ 0xf9c0b663, __VMLINUX_SYMBOL_STR(strlcat) },
	{ 0xfcac73a8, __VMLINUX_SYMBOL_STR(drm_bridge_post_disable) },
	{ 0x3549b02e, __VMLINUX_SYMBOL_STR(drm_atomic_crtc_set_property) },
	{ 0xfb578fc5, __VMLINUX_SYMBOL_STR(memset) },
	{ 0xfb22186b, __VMLINUX_SYMBOL_STR(drm_atomic_state_alloc) },
	{ 0xbb2fea9b, __VMLINUX_SYMBOL_STR(drm_mode_copy) },
	{ 0x99a1afa, __VMLINUX_SYMBOL_STR(drm_atomic_commit) },
	{ 0xff1a73cf, __VMLINUX_SYMBOL_STR(drm_mode_find_dmt) },
	{ 0xb020c345, __VMLINUX_SYMBOL_STR(drm_plane_index) },
	{ 0x72a711e7, __VMLINUX_SYMBOL_STR(cfb_imageblit) },
	{ 0x86486639, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_put) },
	{ 0x9e3a0fbe, __VMLINUX_SYMBOL_STR(drm_bridge_enable) },
	{ 0x3d7149d9, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x88084f49, __VMLINUX_SYMBOL_STR(drm_mode_duplicate) },
	{ 0x7a890c8, __VMLINUX_SYMBOL_STR(fb_alloc_cmap) },
	{ 0x33b13caa, __VMLINUX_SYMBOL_STR(drm_crtc_init_with_planes) },
	{ 0x449ad0a7, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0x1be3ff68, __VMLINUX_SYMBOL_STR(drm_atomic_set_crtc_for_connector) },
	{ 0x9f547fae, __VMLINUX_SYMBOL_STR(drm_atomic_state_free) },
	{ 0x4effdf22, __VMLINUX_SYMBOL_STR(drm_atomic_plane_set_property) },
	{ 0x63ab7685, __VMLINUX_SYMBOL_STR(drm_property_unreference_blob) },
	{ 0x8ac9bd71, __VMLINUX_SYMBOL_STR(register_framebuffer) },
	{ 0x5a921311, __VMLINUX_SYMBOL_STR(strncmp) },
	{ 0x5792f848, __VMLINUX_SYMBOL_STR(strlcpy) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x1081a331, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x677a971d, __VMLINUX_SYMBOL_STR(drm_framebuffer_unreference) },
	{ 0xcd08cc9a, __VMLINUX_SYMBOL_STR(drm_modeset_legacy_acquire_ctx) },
	{ 0x8aa778d0, __VMLINUX_SYMBOL_STR(drm_add_edid_modes) },
	{ 0x14a4e0b4, __VMLINUX_SYMBOL_STR(platform_device_unregister) },
	{ 0x58b8a2b9, __VMLINUX_SYMBOL_STR(drm_atomic_set_fb_for_plane) },
	{ 0xc184b315, __VMLINUX_SYMBOL_STR(drm_modeset_lock_all_ctx) },
	{ 0x1dd71f7a, __VMLINUX_SYMBOL_STR(drm_err) },
	{ 0x47dc8aa8, __VMLINUX_SYMBOL_STR(drm_mode_connector_update_edid_property) },
	{ 0x5b88811, __VMLINUX_SYMBOL_STR(drm_modeset_lock) },
	{ 0xf11543ff, __VMLINUX_SYMBOL_STR(find_first_zero_bit) },
	{ 0x20645642, __VMLINUX_SYMBOL_STR(drm_debug) },
	{ 0x66f4fd1b, __VMLINUX_SYMBOL_STR(drm_mode_validate_size) },
	{ 0x6fc4dd8e, __VMLINUX_SYMBOL_STR(drm_crtc_wait_one_vblank) },
	{ 0xe5c08ddc, __VMLINUX_SYMBOL_STR(drm_crtc_get_hv_timing) },
	{ 0xebe0b240, __VMLINUX_SYMBOL_STR(drm_mode_connector_list_update) },
	{ 0x4c78fdde, __VMLINUX_SYMBOL_STR(drm_atomic_get_crtc_state) },
	{ 0x98b71c6, __VMLINUX_SYMBOL_STR(fb_dealloc_cmap) },
	{ 0x167c5967, __VMLINUX_SYMBOL_STR(print_hex_dump) },
	{ 0x2e6e5c27, __VMLINUX_SYMBOL_STR(i2c_del_adapter) },
	{ 0xa647bb87, __VMLINUX_SYMBOL_STR(drm_mode_set_crtcinfo) },
	{ 0x6a11da3a, __VMLINUX_SYMBOL_STR(drm_plane_cleanup) },
	{ 0xb1c3a01a, __VMLINUX_SYMBOL_STR(oops_in_progress) },
	{ 0xa805454d, __VMLINUX_SYMBOL_STR(_dev_info) },
	{ 0x2dd89cb3, __VMLINUX_SYMBOL_STR(drm_mode_prune_invalid) },
	{ 0xb98f829, __VMLINUX_SYMBOL_STR(drm_atomic_set_crtc_for_plane) },
	{ 0x12a38747, __VMLINUX_SYMBOL_STR(usleep_range) },
	{ 0xc16b4743, __VMLINUX_SYMBOL_STR(sys_fillrect) },
	{ 0x70cd1f, __VMLINUX_SYMBOL_STR(queue_delayed_work_on) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x59aa14cf, __VMLINUX_SYMBOL_STR(fence_release) },
	{ 0xd62c833f, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0x15f98235, __VMLINUX_SYMBOL_STR(sys_imageblit) },
	{ 0xceee4cc1, __VMLINUX_SYMBOL_STR(drm_sysfs_hotplug_event) },
	{ 0xa31c26f4, __VMLINUX_SYMBOL_STR(fb_sys_write) },
	{ 0x96e14d49, __VMLINUX_SYMBOL_STR(drm_mode_debug_printmodeline) },
	{ 0xa86f882f, __VMLINUX_SYMBOL_STR(drm_bridge_mode_fixup) },
	{ 0x30b64a74, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_get) },
	{ 0x645ab792, __VMLINUX_SYMBOL_STR(drm_add_modes_noedid) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0xdf52a8a9, __VMLINUX_SYMBOL_STR(drm_atomic_connector_set_property) },
	{ 0xe69002d6, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xaa59d22, __VMLINUX_SYMBOL_STR(drm_warn_on_modeset_not_all_locked) },
	{ 0x7d47705c, __VMLINUX_SYMBOL_STR(drm_atomic_clean_old_fb) },
	{ 0xf67b8d56, __VMLINUX_SYMBOL_STR(drm_modeset_acquire_init) },
	{ 0xa6bbd805, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0x846a4eda, __VMLINUX_SYMBOL_STR(framebuffer_alloc) },
	{ 0x2207a57f, __VMLINUX_SYMBOL_STR(prepare_to_wait_event) },
	{ 0xfac54807, __VMLINUX_SYMBOL_STR(drm_mode_set_config_internal) },
	{ 0xa28078b2, __VMLINUX_SYMBOL_STR(drm_edid_duplicate) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x6900d335, __VMLINUX_SYMBOL_STR(drm_rect_clip_scaled) },
	{ 0x4bee86f5, __VMLINUX_SYMBOL_STR(drm_mode_equal) },
	{ 0xcf14c2f, __VMLINUX_SYMBOL_STR(request_firmware) },
	{ 0x873c28b1, __VMLINUX_SYMBOL_STR(drm_modeset_lock_all) },
	{ 0xf08242c2, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0xff79a1e, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_count) },
	{ 0x2d50570f, __VMLINUX_SYMBOL_STR(drm_rect_calc_hscale) },
	{ 0x5940e928, __VMLINUX_SYMBOL_STR(cfb_copyarea) },
	{ 0x8633ef8, __VMLINUX_SYMBOL_STR(drm_atomic_add_affected_connectors) },
	{ 0x3e2ffc78, __VMLINUX_SYMBOL_STR(drm_mode_probed_add) },
	{ 0x2e0d2f7f, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0x28318305, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0xb97c60f9, __VMLINUX_SYMBOL_STR(drm_modeset_unlock_all) },
	{ 0x86d162ba, __VMLINUX_SYMBOL_STR(drm_bridge_mode_set) },
	{ 0x59e0cddf, __VMLINUX_SYMBOL_STR(drm_mode_plane_set_obj_prop) },
	{ 0x24b1af85, __VMLINUX_SYMBOL_STR(drm_atomic_add_affected_planes) },
	{ 0x1ea0082b, __VMLINUX_SYMBOL_STR(drm_mode_connector_set_tile_property) },
	{ 0xc360e7e2, __VMLINUX_SYMBOL_STR(drm_ut_debug_printk) },
	{ 0xcbc9557f, __VMLINUX_SYMBOL_STR(unregister_sysrq_key) },
	{ 0x173ad2ac, __VMLINUX_SYMBOL_STR(release_firmware) },
	{ 0x7c2d098f, __VMLINUX_SYMBOL_STR(krealloc) },
	{ 0x452cf44e, __VMLINUX_SYMBOL_STR(drm_mode_vrefresh) },
	{ 0x4eb66e79, __VMLINUX_SYMBOL_STR(drm_property_reference_blob) },
	{ 0x5a222ab0, __VMLINUX_SYMBOL_STR(drm_atomic_async_commit) },
	{ 0x1bb67b39, __VMLINUX_SYMBOL_STR(unregister_framebuffer) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=drm,fb_sys_fops,syscopyarea,sysfillrect,sysimgblt";

