#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x5e862211, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xae405b5f, __VMLINUX_SYMBOL_STR(kmem_cache_destroy) },
	{ 0x762485, __VMLINUX_SYMBOL_STR(iget_failed) },
	{ 0x7e104a81, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x405c1144, __VMLINUX_SYMBOL_STR(get_seconds) },
	{ 0xcbcbfff2, __VMLINUX_SYMBOL_STR(drop_nlink) },
	{ 0xa659715d, __VMLINUX_SYMBOL_STR(make_bad_inode) },
	{ 0xdae80100, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0xb38cc013, __VMLINUX_SYMBOL_STR(generic_file_llseek) },
	{ 0x71d61c76, __VMLINUX_SYMBOL_STR(__mark_inode_dirty) },
	{ 0x754d539c, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0x60a13e90, __VMLINUX_SYMBOL_STR(rcu_barrier) },
	{ 0x77653d24, __VMLINUX_SYMBOL_STR(generic_fh_to_parent) },
	{ 0x484ebce, __VMLINUX_SYMBOL_STR(block_write_begin) },
	{ 0x23a9b726, __VMLINUX_SYMBOL_STR(is_bad_inode) },
	{ 0x67a0dbe9, __VMLINUX_SYMBOL_STR(pagecache_get_page) },
	{ 0xa18610e6, __VMLINUX_SYMBOL_STR(generic_file_open) },
	{ 0xa28e15de, __VMLINUX_SYMBOL_STR(__lock_page) },
	{ 0xdfd4dae0, __VMLINUX_SYMBOL_STR(ll_rw_block) },
	{ 0x69d409f7, __VMLINUX_SYMBOL_STR(__lock_buffer) },
	{ 0x6b06fdce, __VMLINUX_SYMBOL_STR(delayed_work_timer_fn) },
	{ 0x802bde1c, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0x44e9a829, __VMLINUX_SYMBOL_STR(match_token) },
	{ 0xb502a63f, __VMLINUX_SYMBOL_STR(inc_nlink) },
	{ 0x8bf12b3b, __VMLINUX_SYMBOL_STR(block_read_full_page) },
	{ 0x9580deb, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0xa57863e, __VMLINUX_SYMBOL_STR(cancel_delayed_work_sync) },
	{ 0xb5f05fbc, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x58e79459, __VMLINUX_SYMBOL_STR(mount_bdev) },
	{ 0x85df9b6c, __VMLINUX_SYMBOL_STR(strsep) },
	{ 0xd371f36d, __VMLINUX_SYMBOL_STR(page_symlink_inode_operations) },
	{ 0xd21418f5, __VMLINUX_SYMBOL_STR(generic_read_dir) },
	{ 0x1ff5a88d, __VMLINUX_SYMBOL_STR(__getblk_gfp) },
	{ 0x28aa6a67, __VMLINUX_SYMBOL_STR(call_rcu) },
	{ 0x54460120, __VMLINUX_SYMBOL_STR(unlock_buffer) },
	{ 0x45d5cac4, __VMLINUX_SYMBOL_STR(set_page_dirty) },
	{ 0x4b22bc76, __VMLINUX_SYMBOL_STR(truncate_setsize) },
	{ 0x131db64a, __VMLINUX_SYMBOL_STR(system_long_wq) },
	{ 0xe8ef0ff0, __VMLINUX_SYMBOL_STR(current_kernel_time64) },
	{ 0xfb578fc5, __VMLINUX_SYMBOL_STR(memset) },
	{ 0xf040800, __VMLINUX_SYMBOL_STR(__bread_gfp) },
	{ 0x3d7149d9, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x3971cde6, __VMLINUX_SYMBOL_STR(d_obtain_alias) },
	{ 0x449ad0a7, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0x7c1372e8, __VMLINUX_SYMBOL_STR(panic) },
	{ 0x479c3c86, __VMLINUX_SYMBOL_STR(find_next_zero_bit) },
	{ 0xe17f8bc8, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x1081a331, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x2eb9e2f6, __VMLINUX_SYMBOL_STR(set_nlink) },
	{ 0x1f3c6075, __VMLINUX_SYMBOL_STR(__wait_on_buffer) },
	{ 0xde70caf8, __VMLINUX_SYMBOL_STR(setattr_copy) },
	{ 0x7c0cc1ea, __VMLINUX_SYMBOL_STR(page_symlink) },
	{ 0xf5b9dbd2, __VMLINUX_SYMBOL_STR(insert_inode_locked) },
	{ 0xce980615, __VMLINUX_SYMBOL_STR(sync_dirty_buffer) },
	{ 0x8172db07, __VMLINUX_SYMBOL_STR(truncate_pagecache) },
	{ 0xb09abbe7, __VMLINUX_SYMBOL_STR(simple_symlink_inode_operations) },
	{ 0xb126bc85, __VMLINUX_SYMBOL_STR(unlock_page) },
	{ 0xf4b3a868, __VMLINUX_SYMBOL_STR(generic_file_read_iter) },
	{ 0x39a3dac0, __VMLINUX_SYMBOL_STR(inode_nohighmem) },
	{ 0x6916ba97, __VMLINUX_SYMBOL_STR(__brelse) },
	{ 0x5ac05f76, __VMLINUX_SYMBOL_STR(inode_init_once) },
	{ 0xc6cbbc89, __VMLINUX_SYMBOL_STR(capable) },
	{ 0x9e05aed6, __VMLINUX_SYMBOL_STR(invalidate_inode_buffers) },
	{ 0xd189bba9, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0xb5a87016, __VMLINUX_SYMBOL_STR(generic_file_mmap) },
	{ 0x4acdfa31, __VMLINUX_SYMBOL_STR(block_write_full_page) },
	{ 0x40b2a425, __VMLINUX_SYMBOL_STR(block_write_end) },
	{ 0x5ef4612d, __VMLINUX_SYMBOL_STR(truncate_inode_pages_final) },
	{ 0x70cd1f, __VMLINUX_SYMBOL_STR(queue_delayed_work_on) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x9be1beda, __VMLINUX_SYMBOL_STR(generic_write_end) },
	{ 0x7cc4d08b, __VMLINUX_SYMBOL_STR(unlock_new_inode) },
	{ 0xb2998c7, __VMLINUX_SYMBOL_STR(kill_block_super) },
	{ 0x22064bd1, __VMLINUX_SYMBOL_STR(unmap_underlying_metadata) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0x263f355a, __VMLINUX_SYMBOL_STR(inode_change_ok) },
	{ 0xe69002d6, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xe259ae9e, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x41814cb8, __VMLINUX_SYMBOL_STR(dirty_writeback_interval) },
	{ 0x92234a23, __VMLINUX_SYMBOL_STR(kmem_cache_create) },
	{ 0x5595f1d4, __VMLINUX_SYMBOL_STR(register_filesystem) },
	{ 0xba0312fb, __VMLINUX_SYMBOL_STR(generic_file_write_iter) },
	{ 0xbe3c71b5, __VMLINUX_SYMBOL_STR(iput) },
	{ 0x3e0106d4, __VMLINUX_SYMBOL_STR(read_cache_page) },
	{ 0xcdd90b8a, __VMLINUX_SYMBOL_STR(generic_file_fsync) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x6a3ac611, __VMLINUX_SYMBOL_STR(ihold) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x4d7775a0, __VMLINUX_SYMBOL_STR(d_splice_alias) },
	{ 0x2af3c99f, __VMLINUX_SYMBOL_STR(sync_filesystem) },
	{ 0x35f791c3, __VMLINUX_SYMBOL_STR(write_dirty_buffer) },
	{ 0xbc0862c5, __VMLINUX_SYMBOL_STR(block_truncate_page) },
	{ 0x6447a6b, __VMLINUX_SYMBOL_STR(sb_set_blocksize) },
	{ 0x5f560ef7, __VMLINUX_SYMBOL_STR(__bforget) },
	{ 0x169b408a, __VMLINUX_SYMBOL_STR(d_make_root) },
	{ 0xf0813e41, __VMLINUX_SYMBOL_STR(__block_write_begin) },
	{ 0x9195901b, __VMLINUX_SYMBOL_STR(mark_buffer_dirty) },
	{ 0x7fbb8490, __VMLINUX_SYMBOL_STR(unregister_filesystem) },
	{ 0x84fe22ce, __VMLINUX_SYMBOL_STR(write_one_page) },
	{ 0x3cad0dce, __VMLINUX_SYMBOL_STR(init_special_inode) },
	{ 0x5db69c3d, __VMLINUX_SYMBOL_STR(new_inode) },
	{ 0xa776cab7, __VMLINUX_SYMBOL_STR(generic_file_splice_read) },
	{ 0x7f02188f, __VMLINUX_SYMBOL_STR(__msecs_to_jiffies) },
	{ 0xd703451d, __VMLINUX_SYMBOL_STR(generic_fh_to_dentry) },
	{ 0x3263cff5, __VMLINUX_SYMBOL_STR(clear_inode) },
	{ 0x411550a6, __VMLINUX_SYMBOL_STR(d_instantiate) },
	{ 0x748f1df7, __VMLINUX_SYMBOL_STR(__put_page) },
	{ 0x5f76d3b7, __VMLINUX_SYMBOL_STR(generic_block_bmap) },
	{ 0x36b61118, __VMLINUX_SYMBOL_STR(clear_nlink) },
	{ 0x8e8e1bc1, __VMLINUX_SYMBOL_STR(iget_locked) },
	{ 0x19186a0e, __VMLINUX_SYMBOL_STR(inode_init_owner) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=";

