#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x5e862211, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x42595e58, __VMLINUX_SYMBOL_STR(vgacon_text_force) },
	{ 0x80d86f0e, __VMLINUX_SYMBOL_STR(ttm_object_device_release) },
	{ 0x931f05d3, __VMLINUX_SYMBOL_STR(ktime_get_raw) },
	{ 0x2d3385d3, __VMLINUX_SYMBOL_STR(system_wq) },
	{ 0x6adf436b, __VMLINUX_SYMBOL_STR(ttm_prime_fd_to_handle) },
	{ 0x91040120, __VMLINUX_SYMBOL_STR(drm_release) },
	{ 0x670a0972, __VMLINUX_SYMBOL_STR(ttm_pool_populate) },
	{ 0x485a5bc0, __VMLINUX_SYMBOL_STR(ttm_ref_object_add) },
	{ 0xce6e43a8, __VMLINUX_SYMBOL_STR(ttm_base_object_lookup_for_ref) },
	{ 0x7e104a81, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x8e7675cb, __VMLINUX_SYMBOL_STR(ttm_tt_fini) },
	{ 0xb2d524ee, __VMLINUX_SYMBOL_STR(ttm_dma_tt_init) },
	{ 0x91c0e5ad, __VMLINUX_SYMBOL_STR(drm_compat_ioctl) },
	{ 0x138be331, __VMLINUX_SYMBOL_STR(up_read) },
	{ 0xaab1dd99, __VMLINUX_SYMBOL_STR(pci_release_region) },
	{ 0xdae80100, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0xdcb9f128, __VMLINUX_SYMBOL_STR(ttm_bo_create) },
	{ 0xd6ee688f, __VMLINUX_SYMBOL_STR(vmalloc) },
	{ 0x76fb6e3e, __VMLINUX_SYMBOL_STR(ttm_bo_swapout_all) },
	{ 0x616bf458, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0xdeae2349, __VMLINUX_SYMBOL_STR(framebuffer_release) },
	{ 0xcf67c299, __VMLINUX_SYMBOL_STR(ttm_ref_object_exists) },
	{ 0x7e9e62cb, __VMLINUX_SYMBOL_STR(drm_mode_config_cleanup) },
	{ 0x51ffcfbf, __VMLINUX_SYMBOL_STR(reservation_object_wait_timeout_rcu) },
	{ 0xc8b57c27, __VMLINUX_SYMBOL_STR(autoremove_wake_function) },
	{ 0x74c7662e, __VMLINUX_SYMBOL_STR(drm_pci_exit) },
	{ 0x19f462ab, __VMLINUX_SYMBOL_STR(kfree_call_rcu) },
	{ 0xdbbdca85, __VMLINUX_SYMBOL_STR(drm_master_get) },
	{ 0x2b54aa9a, __VMLINUX_SYMBOL_STR(ttm_object_file_init) },
	{ 0xa95d4dee, __VMLINUX_SYMBOL_STR(drm_mode_destroy) },
	{ 0x836d8fd0, __VMLINUX_SYMBOL_STR(ttm_suspend_unlock) },
	{ 0x9ad9d632, __VMLINUX_SYMBOL_STR(drm_ioctl_permit) },
	{ 0x24765c33, __VMLINUX_SYMBOL_STR(ttm_read_unlock) },
	{ 0x2ec4577a, __VMLINUX_SYMBOL_STR(pci_disable_device) },
	{ 0x2471a95d, __VMLINUX_SYMBOL_STR(ttm_bo_validate) },
	{ 0x60600c23, __VMLINUX_SYMBOL_STR(ttm_bo_init) },
	{ 0x70579f91, __VMLINUX_SYMBOL_STR(ttm_bo_synccpu_write_release) },
	{ 0x179651ac, __VMLINUX_SYMBOL_STR(_raw_read_lock) },
	{ 0x96d68a10, __VMLINUX_SYMBOL_STR(ttm_dma_unpopulate) },
	{ 0xd9d3bcd3, __VMLINUX_SYMBOL_STR(_raw_spin_lock_bh) },
	{ 0xf1421d13, __VMLINUX_SYMBOL_STR(drm_mode_sort) },
	{ 0xc0a3d105, __VMLINUX_SYMBOL_STR(find_next_bit) },
	{ 0x6b06fdce, __VMLINUX_SYMBOL_STR(delayed_work_timer_fn) },
	{ 0x57ba72ab, __VMLINUX_SYMBOL_STR(fence_wait_timeout) },
	{ 0xd09b0199, __VMLINUX_SYMBOL_STR(fence_context_alloc) },
	{ 0xbab7f47, __VMLINUX_SYMBOL_STR(ttm_read_lock) },
	{ 0x88bfa7e, __VMLINUX_SYMBOL_STR(cancel_work_sync) },
	{ 0x5d7318dc, __VMLINUX_SYMBOL_STR(drm_global_item_ref) },
	{ 0xf68687be, __VMLINUX_SYMBOL_STR(__sg_page_iter_start) },
	{ 0x3fec048f, __VMLINUX_SYMBOL_STR(sg_next) },
	{ 0xe3b436fd, __VMLINUX_SYMBOL_STR(drm_vblank_cleanup) },
	{ 0x9cfae1a5, __VMLINUX_SYMBOL_STR(pci_release_regions) },
	{ 0x1b63457e, __VMLINUX_SYMBOL_STR(cfb_fillrect) },
	{ 0x9580deb, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0xa57863e, __VMLINUX_SYMBOL_STR(cancel_delayed_work_sync) },
	{ 0xb5f05fbc, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x999e8297, __VMLINUX_SYMBOL_STR(vfree) },
	{ 0x946d9ea3, __VMLINUX_SYMBOL_STR(ttm_write_unlock) },
	{ 0x2300953f, __VMLINUX_SYMBOL_STR(drm_vblank_init) },
	{ 0x21a701fe, __VMLINUX_SYMBOL_STR(fence_signal) },
	{ 0x6ba61e6a, __VMLINUX_SYMBOL_STR(drm_encoder_init) },
	{ 0xdbb5a9f5, __VMLINUX_SYMBOL_STR(drm_ht_remove_item) },
	{ 0x4629334c, __VMLINUX_SYMBOL_STR(__preempt_count) },
	{ 0xb5aa7165, __VMLINUX_SYMBOL_STR(dma_pool_destroy) },
	{ 0xda184a7, __VMLINUX_SYMBOL_STR(ttm_prime_object_init) },
	{ 0x79bb0f5a, __VMLINUX_SYMBOL_STR(drm_pci_set_busid) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0x702a6e64, __VMLINUX_SYMBOL_STR(drm_connector_cleanup) },
	{ 0x3dc7fac0, __VMLINUX_SYMBOL_STR(mutex_trylock) },
	{ 0x72e426bc, __VMLINUX_SYMBOL_STR(down_read) },
	{ 0xde8a932b, __VMLINUX_SYMBOL_STR(ttm_bo_synccpu_write_grab) },
	{ 0xac2c3dcb, __VMLINUX_SYMBOL_STR(ttm_dma_populate) },
	{ 0x9e88526, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0x4f8b5ddb, __VMLINUX_SYMBOL_STR(_copy_to_user) },
	{ 0x7539f0f6, __VMLINUX_SYMBOL_STR(ttm_mem_global_init) },
	{ 0xd2335101, __VMLINUX_SYMBOL_STR(drm_fb_get_bpp_depth) },
	{ 0x26bdfd02, __VMLINUX_SYMBOL_STR(pci_set_master) },
	{ 0x955a832f, __VMLINUX_SYMBOL_STR(___preempt_schedule) },
	{ 0x1a546ddd, __VMLINUX_SYMBOL_STR(drm_mm_init) },
	{ 0xfb578fc5, __VMLINUX_SYMBOL_STR(memset) },
	{ 0xcf49f835, __VMLINUX_SYMBOL_STR(ttm_suspend_lock) },
	{ 0xb607480f, __VMLINUX_SYMBOL_STR(ttm_mem_global_release) },
	{ 0x672f6cee, __VMLINUX_SYMBOL_STR(drm_mode_connector_attach_encoder) },
	{ 0xaea814bd, __VMLINUX_SYMBOL_STR(drm_irq_install) },
	{ 0x7fb8251a, __VMLINUX_SYMBOL_STR(ttm_bo_unref) },
	{ 0xdb3bcca6, __VMLINUX_SYMBOL_STR(cancel_delayed_work) },
	{ 0x809388ca, __VMLINUX_SYMBOL_STR(idr_destroy) },
	{ 0x49581969, __VMLINUX_SYMBOL_STR(pci_restore_state) },
	{ 0x72a711e7, __VMLINUX_SYMBOL_STR(cfb_imageblit) },
	{ 0x6c8dc6bf, __VMLINUX_SYMBOL_STR(ttm_vt_unlock) },
	{ 0x1916e38c, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0xbcf9c794, __VMLINUX_SYMBOL_STR(current_task) },
	{ 0x4d73cd91, __VMLINUX_SYMBOL_STR(ttm_bo_add_to_lru) },
	{ 0xf1fa7158, __VMLINUX_SYMBOL_STR(mutex_lock_interruptible) },
	{ 0x3d7149d9, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0xae21cc14, __VMLINUX_SYMBOL_STR(drm_object_attach_property) },
	{ 0x88084f49, __VMLINUX_SYMBOL_STR(drm_mode_duplicate) },
	{ 0x3a5d0a75, __VMLINUX_SYMBOL_STR(drm_put_dev) },
	{ 0x8fd1152e, __VMLINUX_SYMBOL_STR(_raw_write_unlock) },
	{ 0xb10820e4, __VMLINUX_SYMBOL_STR(_raw_read_unlock) },
	{ 0x30b42f69, __VMLINUX_SYMBOL_STR(ttm_bo_kmap) },
	{ 0xfaef0ed, __VMLINUX_SYMBOL_STR(__tasklet_schedule) },
	{ 0x8ac9bd71, __VMLINUX_SYMBOL_STR(register_framebuffer) },
	{ 0x742620dc, __VMLINUX_SYMBOL_STR(ttm_tt_init) },
	{ 0x3eb37b9d, __VMLINUX_SYMBOL_STR(drm_ht_create) },
	{ 0x225b8099, __VMLINUX_SYMBOL_STR(ttm_bo_evict_mm) },
	{ 0xbfe6f427, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irq) },
	{ 0x9cc4f70a, __VMLINUX_SYMBOL_STR(register_pm_notifier) },
	{ 0x9e9fdd9d, __VMLINUX_SYMBOL_STR(memunmap) },
	{ 0x5e51cd74, __VMLINUX_SYMBOL_STR(swiotlb_nr_tbl) },
	{ 0x966792a2, __VMLINUX_SYMBOL_STR(ttm_eu_fence_buffer_objects) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x1081a331, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x1940e4cd, __VMLINUX_SYMBOL_STR(ttm_write_lock) },
	{ 0xd8edb115, __VMLINUX_SYMBOL_STR(ttm_base_object_unref) },
	{ 0xe8db8dd2, __VMLINUX_SYMBOL_STR(_raw_write_lock) },
	{ 0xf0187927, __VMLINUX_SYMBOL_STR(__sg_page_iter_next) },
	{ 0x84ffea8b, __VMLINUX_SYMBOL_STR(idr_preload) },
	{ 0x677a971d, __VMLINUX_SYMBOL_STR(drm_framebuffer_unreference) },
	{ 0x22ec80fe, __VMLINUX_SYMBOL_STR(ttm_vt_lock) },
	{ 0x9f8150cd, __VMLINUX_SYMBOL_STR(drm_read) },
	{ 0x67633846, __VMLINUX_SYMBOL_STR(drm_mm_insert_node_generic) },
	{ 0x95ba9e29, __VMLINUX_SYMBOL_STR(noop_llseek) },
	{ 0x9545af6d, __VMLINUX_SYMBOL_STR(tasklet_init) },
	{ 0x2a37d074, __VMLINUX_SYMBOL_STR(dma_pool_free) },
	{ 0x36b5497e, __VMLINUX_SYMBOL_STR(intel_iommu_enabled) },
	{ 0xf1ec5cf6, __VMLINUX_SYMBOL_STR(ttm_bo_init_mm) },
	{ 0x9b7f61ce, __VMLINUX_SYMBOL_STR(ttm_mem_global_free) },
	{ 0x169e9b8a, __VMLINUX_SYMBOL_STR(ttm_bo_wait) },
	{ 0xa4fde00, __VMLINUX_SYMBOL_STR(idr_alloc) },
	{ 0x880a15ad, __VMLINUX_SYMBOL_STR(ttm_base_object_lookup) },
	{ 0xe67e6b5c, __VMLINUX_SYMBOL_STR(ttm_bo_device_init) },
	{ 0xce36343e, __VMLINUX_SYMBOL_STR(ttm_prime_handle_to_fd) },
	{ 0x2cde5e39, __VMLINUX_SYMBOL_STR(up_write) },
	{ 0xe7197773, __VMLINUX_SYMBOL_STR(drm_ht_insert_item) },
	{ 0xbfb6ce61, __VMLINUX_SYMBOL_STR(down_write) },
	{ 0x1dd71f7a, __VMLINUX_SYMBOL_STR(drm_err) },
	{ 0x5c15bab1, __VMLINUX_SYMBOL_STR(drm_connector_init) },
	{ 0x526bf37, __VMLINUX_SYMBOL_STR(ttm_object_device_init) },
	{ 0xdf1427e5, __VMLINUX_SYMBOL_STR(idr_remove) },
	{ 0x82072614, __VMLINUX_SYMBOL_STR(tasklet_kill) },
	{ 0x20645642, __VMLINUX_SYMBOL_STR(drm_debug) },
	{ 0xe6a9fa13, __VMLINUX_SYMBOL_STR(arch_dma_alloc_attrs) },
	{ 0xebff5cf5, __VMLINUX_SYMBOL_STR(fence_signal_locked) },
	{ 0x6d8e90c4, __VMLINUX_SYMBOL_STR(ttm_eu_backoff_reservation) },
	{ 0xebe0b240, __VMLINUX_SYMBOL_STR(drm_mode_connector_list_update) },
	{ 0xc6cbbc89, __VMLINUX_SYMBOL_STR(capable) },
	{ 0x2f665a27, __VMLINUX_SYMBOL_STR(drm_ioctl) },
	{ 0x40a9b349, __VMLINUX_SYMBOL_STR(vzalloc) },
	{ 0xae4b94c, __VMLINUX_SYMBOL_STR(drm_ht_remove) },
	{ 0x78764f4e, __VMLINUX_SYMBOL_STR(pv_irq_ops) },
	{ 0x998e45c0, __VMLINUX_SYMBOL_STR(ttm_ref_object_base_unref) },
	{ 0x81144f9d, __VMLINUX_SYMBOL_STR(idr_find_slowpath) },
	{ 0xcd5fffd6, __VMLINUX_SYMBOL_STR(ttm_bo_del_sub_from_lru) },
	{ 0xb2a596d8, __VMLINUX_SYMBOL_STR(ttm_mem_global_alloc) },
	{ 0xbba70a2d, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_bh) },
	{ 0x70cd1f, __VMLINUX_SYMBOL_STR(queue_delayed_work_on) },
	{ 0xeabe68ec, __VMLINUX_SYMBOL_STR(reservation_object_test_signaled_rcu) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x59aa14cf, __VMLINUX_SYMBOL_STR(fence_release) },
	{ 0xd62c833f, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0xa202a8e5, __VMLINUX_SYMBOL_STR(kmalloc_order_trace) },
	{ 0x489083ea, __VMLINUX_SYMBOL_STR(ttm_bo_kunmap) },
	{ 0xc3971a29, __VMLINUX_SYMBOL_STR(drm_irq_uninstall) },
	{ 0xe5815f8a, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irq) },
	{ 0x318e6ce8, __VMLINUX_SYMBOL_STR(drm_get_pci_dev) },
	{ 0xc21d019, __VMLINUX_SYMBOL_STR(flush_delayed_work) },
	{ 0x6b2dc060, __VMLINUX_SYMBOL_STR(dump_stack) },
	{ 0x105e8f74, __VMLINUX_SYMBOL_STR(drm_master_put) },
	{ 0xcf6c92de, __VMLINUX_SYMBOL_STR(drm_modeset_unlock_crtc) },
	{ 0x771cf835, __VMLINUX_SYMBOL_STR(dma_pool_alloc) },
	{ 0x3ecf2902, __VMLINUX_SYMBOL_STR(wake_up_process) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0x57b6efe3, __VMLINUX_SYMBOL_STR(drm_ioctl_flags) },
	{ 0xadc4320c, __VMLINUX_SYMBOL_STR(ttm_eu_reserve_buffers) },
	{ 0x8eff9111, __VMLINUX_SYMBOL_STR(drm_ht_find_item) },
	{ 0xe69002d6, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xe259ae9e, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x2e6aaeec, __VMLINUX_SYMBOL_STR(drm_crtc_init) },
	{ 0x6134433f, __VMLINUX_SYMBOL_STR(reservation_object_add_excl_fence) },
	{ 0x6e875de9, __VMLINUX_SYMBOL_STR(ttm_lock_init) },
	{ 0x680ec266, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0x310f02ec, __VMLINUX_SYMBOL_STR(memremap) },
	{ 0xa6bbd805, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0x970c4501, __VMLINUX_SYMBOL_STR(drm_connector_unregister) },
	{ 0x60cd4b4f, __VMLINUX_SYMBOL_STR(drm_encoder_cleanup) },
	{ 0xf6a9feb8, __VMLINUX_SYMBOL_STR(pci_set_power_state) },
	{ 0x846a4eda, __VMLINUX_SYMBOL_STR(framebuffer_alloc) },
	{ 0x2207a57f, __VMLINUX_SYMBOL_STR(prepare_to_wait_event) },
	{ 0x8b65b399, __VMLINUX_SYMBOL_STR(fb_deferred_io_cleanup) },
	{ 0xfac54807, __VMLINUX_SYMBOL_STR(drm_mode_set_config_internal) },
	{ 0x6fd3e55e, __VMLINUX_SYMBOL_STR(fb_deferred_io_init) },
	{ 0x4f68e5c9, __VMLINUX_SYMBOL_STR(do_gettimeofday) },
	{ 0x98352797, __VMLINUX_SYMBOL_STR(ttm_bo_device_release) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0x4d3e6112, __VMLINUX_SYMBOL_STR(drm_mode_create_dirty_info_property) },
	{ 0x80807b5a, __VMLINUX_SYMBOL_STR(drm_crtc_cleanup) },
	{ 0x8d838d91, __VMLINUX_SYMBOL_STR(ida_remove) },
	{ 0xdf08bef9, __VMLINUX_SYMBOL_STR(drm_mode_config_init) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x27b0bf12, __VMLINUX_SYMBOL_STR(ttm_dma_tt_fini) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x1729abed, __VMLINUX_SYMBOL_STR(pci_request_regions) },
	{ 0x3bb5114a, __VMLINUX_SYMBOL_STR(prepare_to_wait) },
	{ 0x6052860c, __VMLINUX_SYMBOL_STR(ttm_round_pot) },
	{ 0xcc403ef2, __VMLINUX_SYMBOL_STR(dma_supported) },
	{ 0x738714db, __VMLINUX_SYMBOL_STR(ida_pre_get) },
	{ 0x347c6bcf, __VMLINUX_SYMBOL_STR(ww_mutex_unlock) },
	{ 0x94894449, __VMLINUX_SYMBOL_STR(ttm_base_object_init) },
	{ 0x4bee86f5, __VMLINUX_SYMBOL_STR(drm_mode_equal) },
	{ 0x7681946c, __VMLINUX_SYMBOL_STR(unregister_pm_notifier) },
	{ 0x21217f60, __VMLINUX_SYMBOL_STR(drm_framebuffer_lookup) },
	{ 0x2c13cd7c, __VMLINUX_SYMBOL_STR(sg_alloc_table_from_pages) },
	{ 0xb352177e, __VMLINUX_SYMBOL_STR(find_first_bit) },
	{ 0x873c28b1, __VMLINUX_SYMBOL_STR(drm_modeset_lock_all) },
	{ 0xf08242c2, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0x5940e928, __VMLINUX_SYMBOL_STR(cfb_copyarea) },
	{ 0xb1645a2e, __VMLINUX_SYMBOL_STR(sg_free_table) },
	{ 0x564e1aee, __VMLINUX_SYMBOL_STR(ttm_bo_global_init) },
	{ 0x3e2ffc78, __VMLINUX_SYMBOL_STR(drm_mode_probed_add) },
	{ 0x2e0d2f7f, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0x289c6ba0, __VMLINUX_SYMBOL_STR(ttm_bo_manager_func) },
	{ 0xb97c60f9, __VMLINUX_SYMBOL_STR(drm_modeset_unlock_all) },
	{ 0xa8ab39a3, __VMLINUX_SYMBOL_STR(drm_pci_init) },
	{ 0x745b2bdc, __VMLINUX_SYMBOL_STR(drm_framebuffer_init) },
	{ 0x16dc4d1f, __VMLINUX_SYMBOL_STR(fence_init) },
	{ 0xc360e7e2, __VMLINUX_SYMBOL_STR(drm_ut_debug_printk) },
	{ 0xa4466414, __VMLINUX_SYMBOL_STR(drm_mm_remove_node) },
	{ 0x30b04526, __VMLINUX_SYMBOL_STR(ida_init) },
	{ 0x5fb2e8ef, __VMLINUX_SYMBOL_STR(idr_init) },
	{ 0x829534b3, __VMLINUX_SYMBOL_STR(fence_free) },
	{ 0xeb9cdaab, __VMLINUX_SYMBOL_STR(ttm_pool_unpopulate) },
	{ 0xb37e1ee6, __VMLINUX_SYMBOL_STR(pci_enable_device) },
	{ 0x39f1c2f4, __VMLINUX_SYMBOL_STR(ida_get_new_above) },
	{ 0x4f6b400b, __VMLINUX_SYMBOL_STR(_copy_from_user) },
	{ 0x52cfb587, __VMLINUX_SYMBOL_STR(dma_pool_create) },
	{ 0x3e4a4621, __VMLINUX_SYMBOL_STR(drm_connector_register) },
	{ 0xacb99769, __VMLINUX_SYMBOL_STR(ida_destroy) },
	{ 0xd5ee2b9f, __VMLINUX_SYMBOL_STR(ttm_bo_clean_mm) },
	{ 0xb5e1a8c5, __VMLINUX_SYMBOL_STR(drm_mode_crtc_set_gamma_size) },
	{ 0x680fdd20, __VMLINUX_SYMBOL_STR(drm_mode_object_find) },
	{ 0x4e8dd264, __VMLINUX_SYMBOL_STR(ttm_bo_global_release) },
	{ 0xb3372e39, __VMLINUX_SYMBOL_STR(__init_rwsem) },
	{ 0xab397e67, __VMLINUX_SYMBOL_STR(pci_request_region) },
	{ 0x47c68e03, __VMLINUX_SYMBOL_STR(drm_poll) },
	{ 0x2b04fec, __VMLINUX_SYMBOL_STR(dma_ops) },
	{ 0x452cf44e, __VMLINUX_SYMBOL_STR(drm_mode_vrefresh) },
	{ 0x3174bd79, __VMLINUX_SYMBOL_STR(bitmap_clear) },
	{ 0x801fa0e0, __VMLINUX_SYMBOL_STR(drm_open) },
	{ 0xfbc2c5ec, __VMLINUX_SYMBOL_STR(ttm_object_file_release) },
	{ 0xf9a516bb, __VMLINUX_SYMBOL_STR(pci_save_state) },
	{ 0xb5540008, __VMLINUX_SYMBOL_STR(drm_global_item_unref) },
	{ 0x5af9fc70, __VMLINUX_SYMBOL_STR(drm_modeset_lock_crtc) },
	{ 0x7729dcad, __VMLINUX_SYMBOL_STR(drm_framebuffer_cleanup) },
	{ 0x1bb67b39, __VMLINUX_SYMBOL_STR(unregister_framebuffer) },
	{ 0xd279edba, __VMLINUX_SYMBOL_STR(ttm_bo_mmap) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=ttm,drm,drm_kms_helper";

MODULE_ALIAS("pci:v000015ADd00000405sv*sd*bc*sc*i*");

MODULE_INFO(srcversion, "0594DECDA132CD791DEE2E1");
