#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x5e862211, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xe56a9336, __VMLINUX_SYMBOL_STR(snd_pcm_format_width) },
	{ 0x2dee2b6d, __VMLINUX_SYMBOL_STR(snd_soc_dapm_kcontrol_widget) },
	{ 0x7e104a81, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x5c912edc, __VMLINUX_SYMBOL_STR(pci_bus_read_config_byte) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xc0e1ce85, __VMLINUX_SYMBOL_STR(snd_hdac_stream_start) },
	{ 0x86b34ddd, __VMLINUX_SYMBOL_STR(skl_ipc_get_large_config) },
	{ 0xdae80100, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0x6cfe61c1, __VMLINUX_SYMBOL_STR(snd_pcm_lib_default_mmap) },
	{ 0xb9f3a641, __VMLINUX_SYMBOL_STR(snd_soc_unregister_platform) },
	{ 0xa5ad197, __VMLINUX_SYMBOL_STR(snd_hdac_ext_bus_get_link) },
	{ 0xd2d04982, __VMLINUX_SYMBOL_STR(snd_soc_tplg_widget_bind_event) },
	{ 0xb94b6efd, __VMLINUX_SYMBOL_STR(snd_hdac_bus_alloc_stream_pages) },
	{ 0x62d0edee, __VMLINUX_SYMBOL_STR(snd_pcm_period_elapsed) },
	{ 0x6332ebe7, __VMLINUX_SYMBOL_STR(snd_hdac_stream_reset) },
	{ 0x532099c1, __VMLINUX_SYMBOL_STR(snd_hdac_stream_sync_trigger) },
	{ 0x2ec4577a, __VMLINUX_SYMBOL_STR(pci_disable_device) },
	{ 0x7f75a83, __VMLINUX_SYMBOL_STR(snd_pcm_lib_preallocate_free_for_all) },
	{ 0x714f44b0, __VMLINUX_SYMBOL_STR(snd_soc_set_runtime_hwparams) },
	{ 0x92ced0e2, __VMLINUX_SYMBOL_STR(snd_hdac_ext_link_set_stream_id) },
	{ 0x11fb1ed9, __VMLINUX_SYMBOL_STR(snd_hdac_ext_link_clear_stream_id) },
	{ 0x3083d33f, __VMLINUX_SYMBOL_STR(snd_hdac_bus_handle_stream_irq) },
	{ 0xad8865be, __VMLINUX_SYMBOL_STR(snd_hdac_ext_bus_get_ml_capabilities) },
	{ 0x9cfae1a5, __VMLINUX_SYMBOL_STR(pci_release_regions) },
	{ 0x6af9273, __VMLINUX_SYMBOL_STR(snd_hdac_stream_set_params) },
	{ 0xf56b4641, __VMLINUX_SYMBOL_STR(snd_hdac_stream_setup) },
	{ 0xb5f05fbc, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0xd42c3170, __VMLINUX_SYMBOL_STR(skl_ipc_set_large_config) },
	{ 0x27e06c47, __VMLINUX_SYMBOL_STR(pm_runtime_allow) },
	{ 0x4d3c493c, __VMLINUX_SYMBOL_STR(snd_soc_register_component) },
	{ 0x70ce87ba, __VMLINUX_SYMBOL_STR(skl_ipc_delete_pipeline) },
	{ 0xf4c91ed, __VMLINUX_SYMBOL_STR(ns_to_timespec) },
	{ 0xd05b9e13, __VMLINUX_SYMBOL_STR(snd_pcm_hw_constraint_integer) },
	{ 0xce2840e7, __VMLINUX_SYMBOL_STR(irq_set_irq_wake) },
	{ 0x4f8b5ddb, __VMLINUX_SYMBOL_STR(_copy_to_user) },
	{ 0x26bdfd02, __VMLINUX_SYMBOL_STR(pci_set_master) },
	{ 0xd288d901, __VMLINUX_SYMBOL_STR(snd_pcm_sgbuf_ops_page) },
	{ 0x49581969, __VMLINUX_SYMBOL_STR(pci_restore_state) },
	{ 0x98782fd0, __VMLINUX_SYMBOL_STR(dev_err) },
	{ 0x1916e38c, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0x2dcd62e5, __VMLINUX_SYMBOL_STR(snd_hdac_stream_sync) },
	{ 0xf8bb5fe8, __VMLINUX_SYMBOL_STR(snd_soc_tplg_component_load) },
	{ 0x7ae82978, __VMLINUX_SYMBOL_STR(snd_hdac_ext_link_stream_reset) },
	{ 0x668e6bb4, __VMLINUX_SYMBOL_STR(sst_acpi_find_machine) },
	{ 0x2232533c, __VMLINUX_SYMBOL_STR(platform_device_alloc) },
	{ 0xe81df7a2, __VMLINUX_SYMBOL_STR(snd_hdac_ext_bus_parse_capabilities) },
	{ 0xe260d833, __VMLINUX_SYMBOL_STR(platform_device_add) },
	{ 0x9e9fdd9d, __VMLINUX_SYMBOL_STR(memunmap) },
	{ 0x992dbd0c, __VMLINUX_SYMBOL_STR(snd_hdac_ext_stream_init_all) },
	{ 0x9a344261, __VMLINUX_SYMBOL_STR(snd_hdac_ext_stream_set_lpib) },
	{ 0xedaa19a7, __VMLINUX_SYMBOL_STR(pci_bus_write_config_dword) },
	{ 0x1081a331, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0xc9629d0d, __VMLINUX_SYMBOL_STR(snd_pcm_lib_free_pages) },
	{ 0xf831558, __VMLINUX_SYMBOL_STR(snd_hdac_ext_stream_release) },
	{ 0x8a1a20f3, __VMLINUX_SYMBOL_STR(snd_hdac_ext_stream_assign) },
	{ 0xab7daa67, __VMLINUX_SYMBOL_STR(skl_dsp_wake) },
	{ 0x14a4e0b4, __VMLINUX_SYMBOL_STR(platform_device_unregister) },
	{ 0x2072ee9b, __VMLINUX_SYMBOL_STR(request_threaded_irq) },
	{ 0x69d7dd8a, __VMLINUX_SYMBOL_STR(snd_pcm_lib_ioctl) },
	{ 0x2b4c06fe, __VMLINUX_SYMBOL_STR(snd_soc_unregister_component) },
	{ 0x1616cb30, __VMLINUX_SYMBOL_STR(acpi_evaluate_dsm) },
	{ 0xdd9a804a, __VMLINUX_SYMBOL_STR(snd_hdac_calc_stream_format) },
	{ 0x609c4bcd, __VMLINUX_SYMBOL_STR(snd_pcm_lib_malloc_pages) },
	{ 0xb51b2894, __VMLINUX_SYMBOL_STR(snd_hdac_ext_stream_set_dpibr) },
	{ 0xe523ad75, __VMLINUX_SYMBOL_STR(synchronize_irq) },
	{ 0xc542933a, __VMLINUX_SYMBOL_STR(timecounter_read) },
	{ 0x94308950, __VMLINUX_SYMBOL_STR(snd_hdac_stream_cleanup) },
	{ 0x2bfeb410, __VMLINUX_SYMBOL_STR(acpi_get_handle) },
	{ 0x167c5967, __VMLINUX_SYMBOL_STR(print_hex_dump) },
	{ 0x5ee95b30, __VMLINUX_SYMBOL_STR(snd_hdac_stream_stop) },
	{ 0xcf537c55, __VMLINUX_SYMBOL_STR(snd_hdac_bus_init_chip) },
	{ 0xa805454d, __VMLINUX_SYMBOL_STR(_dev_info) },
	{ 0xd4530daa, __VMLINUX_SYMBOL_STR(snd_hdac_stream_free_all) },
	{ 0xc5e4c7d5, __VMLINUX_SYMBOL_STR(snd_hdac_ext_stream_drsm_enable) },
	{ 0x254efb5b, __VMLINUX_SYMBOL_STR(snd_hdac_ext_stream_decouple) },
	{ 0xcd265af1, __VMLINUX_SYMBOL_STR(pci_bus_read_config_dword) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x5f864e0, __VMLINUX_SYMBOL_STR(pci_intx) },
	{ 0x852ff015, __VMLINUX_SYMBOL_STR(snd_hdac_ext_bus_exit) },
	{ 0xd8272a87, __VMLINUX_SYMBOL_STR(snd_hdac_ext_bus_link_power_up_all) },
	{ 0x352defe2, __VMLINUX_SYMBOL_STR(snd_soc_register_platform) },
	{ 0xd85cf120, __VMLINUX_SYMBOL_STR(snd_hdac_bus_free_stream_pages) },
	{ 0x211f68f1, __VMLINUX_SYMBOL_STR(getnstimeofday64) },
	{ 0x1c62648c, __VMLINUX_SYMBOL_STR(snd_hdac_ext_stop_streams) },
	{ 0x24d58c8c, __VMLINUX_SYMBOL_STR(snd_hdac_ext_link_stream_start) },
	{ 0xb0660713, __VMLINUX_SYMBOL_STR(snd_hdac_stream_timecounter_init) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0xe06de3d4, __VMLINUX_SYMBOL_STR(skl_dsp_sleep) },
	{ 0x61c31280, __VMLINUX_SYMBOL_STR(skl_sst_dsp_cleanup) },
	{ 0x70d5af07, __VMLINUX_SYMBOL_STR(pci_unregister_driver) },
	{ 0xd3fbfdba, __VMLINUX_SYMBOL_STR(snd_pcm_set_sync) },
	{ 0x211b597f, __VMLINUX_SYMBOL_STR(snd_hdac_ext_bus_ppcap_int_enable) },
	{ 0x123f82f3, __VMLINUX_SYMBOL_STR(getrawmonotonic64) },
	{ 0xe69002d6, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xe259ae9e, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x65bd2eb5, __VMLINUX_SYMBOL_STR(pci_ioremap_bar) },
	{ 0x9948d78b, __VMLINUX_SYMBOL_STR(__dynamic_dev_dbg) },
	{ 0x680ec266, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0x310f02ec, __VMLINUX_SYMBOL_STR(memremap) },
	{ 0xddabd652, __VMLINUX_SYMBOL_STR(skl_ipc_set_pipeline_state) },
	{ 0x54058003, __VMLINUX_SYMBOL_STR(snd_hdac_ext_bus_device_init) },
	{ 0x168dcc37, __VMLINUX_SYMBOL_STR(skl_ipc_create_pipeline) },
	{ 0xdca79e31, __VMLINUX_SYMBOL_STR(snd_hdac_link_free_all) },
	{ 0xe8109543, __VMLINUX_SYMBOL_STR(pci_bus_write_config_byte) },
	{ 0x2441a4ba, __VMLINUX_SYMBOL_STR(snd_hdac_ext_link_stream_setup) },
	{ 0xffcb65d2, __VMLINUX_SYMBOL_STR(snd_hdac_ext_bus_init) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0xb2aa351b, __VMLINUX_SYMBOL_STR(snd_hdac_ext_bus_link_power_up) },
	{ 0x1729abed, __VMLINUX_SYMBOL_STR(pci_request_regions) },
	{ 0xa52f4064, __VMLINUX_SYMBOL_STR(snd_hdac_bus_stop_chip) },
	{ 0xcc403ef2, __VMLINUX_SYMBOL_STR(dma_supported) },
	{ 0x360e82d7, __VMLINUX_SYMBOL_STR(snd_pcm_hw_constraint_minmax) },
	{ 0xedc03953, __VMLINUX_SYMBOL_STR(iounmap) },
	{ 0xf58a45ab, __VMLINUX_SYMBOL_STR(pci_dev_run_wake) },
	{ 0xa755261f, __VMLINUX_SYMBOL_STR(__pci_register_driver) },
	{ 0xcf14c2f, __VMLINUX_SYMBOL_STR(request_firmware) },
	{ 0x79cfee46, __VMLINUX_SYMBOL_STR(snd_hdac_ext_link_stream_clear) },
	{ 0x7e77e84d, __VMLINUX_SYMBOL_STR(snd_pcm_lib_preallocate_pages_for_all) },
	{ 0x2eb077a5, __VMLINUX_SYMBOL_STR(snd_hdac_ext_bus_ppcap_enable) },
	{ 0x9b645614, __VMLINUX_SYMBOL_STR(dev_warn) },
	{ 0x6e616586, __VMLINUX_SYMBOL_STR(skl_ipc_init_instance) },
	{ 0xde9fd958, __VMLINUX_SYMBOL_STR(skl_ipc_bind_unbind) },
	{ 0xcdd142a3, __VMLINUX_SYMBOL_STR(pci_dev_put) },
	{ 0x4dd9bd95, __VMLINUX_SYMBOL_STR(snd_hdac_bus_update_rirb) },
	{ 0xd4b7f4e2, __VMLINUX_SYMBOL_STR(snd_hdac_bus_get_response) },
	{ 0x3874d1d6, __VMLINUX_SYMBOL_STR(snd_hdac_bus_enter_link_reset) },
	{ 0xd56b5f64, __VMLINUX_SYMBOL_STR(ktime_get_ts64) },
	{ 0x6da3eb4f, __VMLINUX_SYMBOL_STR(snd_hdac_bus_send_cmd) },
	{ 0xb37e1ee6, __VMLINUX_SYMBOL_STR(pci_enable_device) },
	{ 0x2a86697b, __VMLINUX_SYMBOL_STR(devm_kmalloc) },
	{ 0x4f6b400b, __VMLINUX_SYMBOL_STR(_copy_from_user) },
	{ 0xd7378b04, __VMLINUX_SYMBOL_STR(skl_sst_dsp_init) },
	{ 0x173ad2ac, __VMLINUX_SYMBOL_STR(release_firmware) },
	{ 0x2b04fec, __VMLINUX_SYMBOL_STR(dma_ops) },
	{ 0xf20dabd8, __VMLINUX_SYMBOL_STR(free_irq) },
	{ 0x290f11e1, __VMLINUX_SYMBOL_STR(snd_hdac_ext_bus_link_power_down_all) },
	{ 0xf9a516bb, __VMLINUX_SYMBOL_STR(pci_save_state) },
	{ 0x879dcb22, __VMLINUX_SYMBOL_STR(platform_device_put) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=snd-pcm,snd-soc-core,snd-hda-core,snd-soc-skl-ipc,snd-hda-ext-core,snd-soc-sst-match";

MODULE_ALIAS("pci:v00008086d00009D70sv*sd*bc*sc*i*");
