#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x5e862211, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xf6e679b, __VMLINUX_SYMBOL_STR(param_ops_bool) },
	{ 0x2f418796, __VMLINUX_SYMBOL_STR(blk_mq_map_queue) },
	{ 0x1c16d6f6, __VMLINUX_SYMBOL_STR(bus_unregister) },
	{ 0xacb99769, __VMLINUX_SYMBOL_STR(ida_destroy) },
	{ 0x8c03d20c, __VMLINUX_SYMBOL_STR(destroy_workqueue) },
	{ 0xb5c97aba, __VMLINUX_SYMBOL_STR(device_unregister) },
	{ 0x91bec164, __VMLINUX_SYMBOL_STR(bus_register) },
	{ 0x71bb4555, __VMLINUX_SYMBOL_STR(device_register) },
	{ 0x43a53735, __VMLINUX_SYMBOL_STR(__alloc_workqueue_key) },
	{ 0x92234a23, __VMLINUX_SYMBOL_STR(kmem_cache_create) },
	{ 0x466b85b8, __VMLINUX_SYMBOL_STR(libceph_compatible) },
	{ 0x6b2e3bcd, __VMLINUX_SYMBOL_STR(ceph_get_snap_context) },
	{ 0x9f0ec565, __VMLINUX_SYMBOL_STR(blk_mq_start_request) },
	{ 0x5733ce2d, __VMLINUX_SYMBOL_STR(blk_mq_end_request) },
	{ 0x8c222b18, __VMLINUX_SYMBOL_STR(osd_req_op_raw_data_in_pages) },
	{ 0x564f21c1, __VMLINUX_SYMBOL_STR(bio_advance) },
	{ 0x2a555bb8, __VMLINUX_SYMBOL_STR(bio_clone_bioset) },
	{ 0x67bf69ce, __VMLINUX_SYMBOL_STR(fs_bio_set) },
	{ 0x8b2f5c83, __VMLINUX_SYMBOL_STR(add_disk) },
	{ 0x71a50dbc, __VMLINUX_SYMBOL_STR(register_blkdev) },
	{ 0x97862a03, __VMLINUX_SYMBOL_STR(device_add) },
	{ 0x6aca8238, __VMLINUX_SYMBOL_STR(dev_set_name) },
	{ 0x1e7bc4b9, __VMLINUX_SYMBOL_STR(blk_queue_max_discard_sectors) },
	{ 0x4f424dcf, __VMLINUX_SYMBOL_STR(blk_queue_io_opt) },
	{ 0x2653117, __VMLINUX_SYMBOL_STR(blk_queue_io_min) },
	{ 0xf841e0b4, __VMLINUX_SYMBOL_STR(blk_queue_max_segment_size) },
	{ 0x77774e02, __VMLINUX_SYMBOL_STR(blk_queue_max_segments) },
	{ 0xe60e848e, __VMLINUX_SYMBOL_STR(blk_queue_max_hw_sectors) },
	{ 0x21052bb3, __VMLINUX_SYMBOL_STR(blk_mq_init_queue) },
	{ 0xef63b191, __VMLINUX_SYMBOL_STR(blk_mq_alloc_tag_set) },
	{ 0x28318305, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0x21a13cd3, __VMLINUX_SYMBOL_STR(alloc_disk) },
	{ 0x21e992a5, __VMLINUX_SYMBOL_STR(ida_simple_get) },
	{ 0x4c67412c, __VMLINUX_SYMBOL_STR(ceph_open_session) },
	{ 0x2a8b0f37, __VMLINUX_SYMBOL_STR(ceph_create_client) },
	{ 0x1a33ccc0, __VMLINUX_SYMBOL_STR(ceph_monc_wait_osdmap) },
	{ 0xd075e3cc, __VMLINUX_SYMBOL_STR(ceph_monc_request_next_osdmap) },
	{ 0xbec65644, __VMLINUX_SYMBOL_STR(ceph_monc_do_get_version) },
	{ 0x56d64b1b, __VMLINUX_SYMBOL_STR(ceph_pg_poolid_by_name) },
	{ 0xb5f05fbc, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0xc7672334, __VMLINUX_SYMBOL_STR(ceph_destroy_options) },
	{ 0x54fbd6cb, __VMLINUX_SYMBOL_STR(ceph_compare_options) },
	{ 0x1081a331, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x40e9fb59, __VMLINUX_SYMBOL_STR(ceph_parse_options) },
	{ 0x448eac3e, __VMLINUX_SYMBOL_STR(kmemdup) },
	{ 0x1ac5d3cb, __VMLINUX_SYMBOL_STR(strcspn) },
	{ 0xc29bf967, __VMLINUX_SYMBOL_STR(strspn) },
	{ 0x419d3f61, __VMLINUX_SYMBOL_STR(try_module_get) },
	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
	{ 0xbc36c391, __VMLINUX_SYMBOL_STR(ceph_pg_pool_name_by_id) },
	{ 0x71f4c8a, __VMLINUX_SYMBOL_STR(ceph_osdc_create_event) },
	{ 0x6bbf635a, __VMLINUX_SYMBOL_STR(revalidate_disk) },
	{ 0x2cde5e39, __VMLINUX_SYMBOL_STR(up_write) },
	{ 0xbfb6ce61, __VMLINUX_SYMBOL_STR(down_write) },
	{ 0xa916b694, __VMLINUX_SYMBOL_STR(strnlen) },
	{ 0x449ad0a7, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0xae3515ba, __VMLINUX_SYMBOL_STR(ceph_create_snap_context) },
	{ 0xc499ae1e, __VMLINUX_SYMBOL_STR(kstrdup) },
	{ 0xcec4bbd3, __VMLINUX_SYMBOL_STR(ceph_copy_from_page_vector) },
	{ 0x7713d83f, __VMLINUX_SYMBOL_STR(osd_req_op_cls_response_data_pages) },
	{ 0x48bbfb4, __VMLINUX_SYMBOL_STR(osd_req_op_cls_request_data_pagelist) },
	{ 0xe3b042ca, __VMLINUX_SYMBOL_STR(ceph_pagelist_append) },
	{ 0x1b3d20e9, __VMLINUX_SYMBOL_STR(ceph_alloc_page_vector) },
	{ 0x50a90e8d, __VMLINUX_SYMBOL_STR(bsearch) },
	{ 0xb5a459dc, __VMLINUX_SYMBOL_STR(unregister_blkdev) },
	{ 0x9eeb2c7c, __VMLINUX_SYMBOL_STR(device_del) },
	{ 0x49c41207, __VMLINUX_SYMBOL_STR(ceph_osdc_flush_notifies) },
	{ 0x3c80c06c, __VMLINUX_SYMBOL_STR(kstrtoull) },
	{ 0x4fb9f94, __VMLINUX_SYMBOL_STR(put_device) },
	{ 0xbf87b69b, __VMLINUX_SYMBOL_STR(osd_req_op_cls_request_data_pages) },
	{ 0x6a86d633, __VMLINUX_SYMBOL_STR(osd_req_op_cls_init) },
	{ 0xb52ed15c, __VMLINUX_SYMBOL_STR(__blk_mq_end_request) },
	{ 0xf1004d18, __VMLINUX_SYMBOL_STR(blk_update_request) },
	{ 0x3f688151, __VMLINUX_SYMBOL_STR(ceph_put_snap_context) },
	{ 0x27882b9b, __VMLINUX_SYMBOL_STR(ida_simple_remove) },
	{ 0xc122d486, __VMLINUX_SYMBOL_STR(ceph_osdc_cancel_event) },
	{ 0xbb2495b, __VMLINUX_SYMBOL_STR(ceph_osdc_set_request_linger) },
	{ 0xccd5dce0, __VMLINUX_SYMBOL_STR(osd_req_op_watch_init) },
	{ 0x27ca11d7, __VMLINUX_SYMBOL_STR(osd_req_op_extent_osd_data_pages) },
	{ 0xe992fb07, __VMLINUX_SYMBOL_STR(osd_req_op_extent_osd_data_bio) },
	{ 0xa0946383, __VMLINUX_SYMBOL_STR(osd_req_op_init) },
	{ 0x61c1cbcc, __VMLINUX_SYMBOL_STR(osd_req_op_alloc_hint_init) },
	{ 0xbbcb2d53, __VMLINUX_SYMBOL_STR(osd_req_op_extent_init) },
	{ 0xe8ef0ff0, __VMLINUX_SYMBOL_STR(current_kernel_time64) },
	{ 0x7392596b, __VMLINUX_SYMBOL_STR(ceph_osdc_build_request) },
	{ 0x75e4bbba, __VMLINUX_SYMBOL_STR(ceph_osdc_alloc_request) },
	{ 0x71b221d5, __VMLINUX_SYMBOL_STR(bio_put) },
	{ 0xe17f8bc8, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0xe6ad0926, __VMLINUX_SYMBOL_STR(ceph_release_page_vector) },
	{ 0xd1a3419b, __VMLINUX_SYMBOL_STR(ceph_osdc_put_request) },
	{ 0x8dfc89f0, __VMLINUX_SYMBOL_STR(get_device) },
	{ 0x2e0d2f7f, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0x57dc20d7, __VMLINUX_SYMBOL_STR(set_disk_ro) },
	{ 0xbfe6f427, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irq) },
	{ 0xe5815f8a, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irq) },
	{ 0x6729d3df, __VMLINUX_SYMBOL_STR(__get_user_4) },
	{ 0x108a8dd8, __VMLINUX_SYMBOL_STR(ceph_client_id) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0x79f29d12, __VMLINUX_SYMBOL_STR(__module_get) },
	{ 0xd40413b5, __VMLINUX_SYMBOL_STR(device_initialize) },
	{ 0xb3372e39, __VMLINUX_SYMBOL_STR(__init_rwsem) },
	{ 0x13be5989, __VMLINUX_SYMBOL_STR(module_put) },
	{ 0xa6990ecd, __VMLINUX_SYMBOL_STR(ceph_destroy_client) },
	{ 0xdae80100, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0xe259ae9e, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x4e3567f7, __VMLINUX_SYMBOL_STR(match_int) },
	{ 0x44e9a829, __VMLINUX_SYMBOL_STR(match_token) },
	{ 0xb3b90fa3, __VMLINUX_SYMBOL_STR(blk_mq_free_tag_set) },
	{ 0xd3542d1f, __VMLINUX_SYMBOL_STR(blk_cleanup_queue) },
	{ 0xc61a97c7, __VMLINUX_SYMBOL_STR(del_gendisk) },
	{ 0xe57d6a2b, __VMLINUX_SYMBOL_STR(put_disk) },
	{ 0x878cd015, __VMLINUX_SYMBOL_STR(wait_for_completion_interruptible_timeout) },
	{ 0xf7e113c6, __VMLINUX_SYMBOL_STR(ceph_osdc_start_request) },
	{ 0x8a0b12c6, __VMLINUX_SYMBOL_STR(complete_all) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0xfb578fc5, __VMLINUX_SYMBOL_STR(memset) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x955a832f, __VMLINUX_SYMBOL_STR(___preempt_schedule) },
	{ 0x78764f4e, __VMLINUX_SYMBOL_STR(pv_irq_ops) },
	{ 0x4629334c, __VMLINUX_SYMBOL_STR(__preempt_count) },
	{ 0xbcf9c794, __VMLINUX_SYMBOL_STR(current_task) },
	{ 0x138be331, __VMLINUX_SYMBOL_STR(up_read) },
	{ 0x72e426bc, __VMLINUX_SYMBOL_STR(down_read) },
	{ 0x9e88526, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0xd189bba9, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x754d539c, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0xe69002d6, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x7e104a81, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x44b1d426, __VMLINUX_SYMBOL_STR(__dynamic_pr_debug) },
	{ 0x886ef925, __VMLINUX_SYMBOL_STR(ceph_osdc_cancel_request) },
	{ 0xae405b5f, __VMLINUX_SYMBOL_STR(kmem_cache_destroy) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=libceph";

