#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x5e862211, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x287d469c, __VMLINUX_SYMBOL_STR(inet_csk_reqsk_queue_drop) },
	{ 0x59814a84, __VMLINUX_SYMBOL_STR(dccp_statistics) },
	{ 0x49045426, __VMLINUX_SYMBOL_STR(icmp_err_convert) },
	{ 0x6766147a, __VMLINUX_SYMBOL_STR(dccp_init_sock) },
	{ 0xdae80100, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0x1145602c, __VMLINUX_SYMBOL_STR(__ip_route_output_key_hash) },
	{ 0xb8d00d93, __VMLINUX_SYMBOL_STR(dccp_set_state) },
	{ 0xcfad9f3e, __VMLINUX_SYMBOL_STR(ip_getsockopt) },
	{ 0x2b71f763, __VMLINUX_SYMBOL_STR(inet_unhash) },
	{ 0x5204fa0c, __VMLINUX_SYMBOL_STR(inet_twsk_put) },
	{ 0x23672cd0, __VMLINUX_SYMBOL_STR(dccp_hashinfo) },
	{ 0xdb047081, __VMLINUX_SYMBOL_STR(ip_setsockopt) },
	{ 0x3b26c9fd, __VMLINUX_SYMBOL_STR(dccp_sendmsg) },
	{ 0x58c75f2d, __VMLINUX_SYMBOL_STR(ip_build_and_send_pkt) },
	{ 0xe756ab03, __VMLINUX_SYMBOL_STR(sk_setup_caps) },
	{ 0x297d115c, __VMLINUX_SYMBOL_STR(dccp_ctl_make_reset) },
	{ 0x793b8977, __VMLINUX_SYMBOL_STR(dccp_destroy_sock) },
	{ 0xdf91754, __VMLINUX_SYMBOL_STR(dccp_make_response) },
	{ 0x654e8ddd, __VMLINUX_SYMBOL_STR(sock_release) },
	{ 0xa48703ac, __VMLINUX_SYMBOL_STR(dst_release) },
	{ 0x1622e87d, __VMLINUX_SYMBOL_STR(dccp_send_sync) },
	{ 0x37ed3ddc, __VMLINUX_SYMBOL_STR(dccp_rcv_established) },
	{ 0x1e96ee46, __VMLINUX_SYMBOL_STR(inet_csk_prepare_forced_close) },
	{ 0x39597ab4, __VMLINUX_SYMBOL_STR(dccp_create_openreq_child) },
	{ 0xaccf4693, __VMLINUX_SYMBOL_STR(dccp_check_req) },
	{ 0xf808098, __VMLINUX_SYMBOL_STR(inet_sendmsg) },
	{ 0x40a11b3a, __VMLINUX_SYMBOL_STR(dccp_recvmsg) },
	{ 0x8a2e846b, __VMLINUX_SYMBOL_STR(inet_del_protocol) },
	{ 0xa3003347, __VMLINUX_SYMBOL_STR(inet_sk_rebuild_header) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0x9759d026, __VMLINUX_SYMBOL_STR(dccp_ioctl) },
	{ 0x9a9372bb, __VMLINUX_SYMBOL_STR(compat_sock_common_setsockopt) },
	{ 0x6759972e, __VMLINUX_SYMBOL_STR(dccp_setsockopt) },
	{ 0xe8cfa45d, __VMLINUX_SYMBOL_STR(sock_common_recvmsg) },
	{ 0xc052e782, __VMLINUX_SYMBOL_STR(sock_no_sendpage) },
	{ 0xe18ccbd2, __VMLINUX_SYMBOL_STR(dccp_child_process) },
	{ 0xa37745a9, __VMLINUX_SYMBOL_STR(__pskb_pull_tail) },
	{ 0xcfaae361, __VMLINUX_SYMBOL_STR(sock_no_mmap) },
	{ 0x2097a95f, __VMLINUX_SYMBOL_STR(compat_sock_common_getsockopt) },
	{ 0xfe9ded95, __VMLINUX_SYMBOL_STR(sock_no_socketpair) },
	{ 0xc939e253, __VMLINUX_SYMBOL_STR(skb_checksum) },
	{ 0xdc36ad08, __VMLINUX_SYMBOL_STR(compat_ip_getsockopt) },
	{ 0xdd727d5a, __VMLINUX_SYMBOL_STR(unregister_pernet_subsys) },
	{ 0x17439aed, __VMLINUX_SYMBOL_STR(dccp_parse_options) },
	{ 0x64deb9ab, __VMLINUX_SYMBOL_STR(compat_dccp_setsockopt) },
	{ 0xe2a3c198, __VMLINUX_SYMBOL_STR(dccp_getsockopt) },
	{ 0x3f5f16cf, __VMLINUX_SYMBOL_STR(inet_csk_update_pmtu) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0xc5aaf2b5, __VMLINUX_SYMBOL_STR(inet_csk_route_req) },
	{ 0xf3ae43b5, __VMLINUX_SYMBOL_STR(inet_csk_route_child_sock) },
	{ 0xe17f8bc8, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x3f8aa41, __VMLINUX_SYMBOL_STR(inet_hash_connect) },
	{ 0xeac14361, __VMLINUX_SYMBOL_STR(dccp_reqsk_init) },
	{ 0x77da680d, __VMLINUX_SYMBOL_STR(dev_get_by_index_rcu) },
	{ 0xf0471e18, __VMLINUX_SYMBOL_STR(dccp_close) },
	{ 0x1c059ecb, __VMLINUX_SYMBOL_STR(sk_free) },
	{ 0xaf77c9c9, __VMLINUX_SYMBOL_STR(inet_shutdown) },
	{ 0x45338ae9, __VMLINUX_SYMBOL_STR(inet_add_protocol) },
	{ 0xda4405c2, __VMLINUX_SYMBOL_STR(dccp_orphan_count) },
	{ 0x2469810f, __VMLINUX_SYMBOL_STR(__rcu_read_unlock) },
	{ 0xa6606a1a, __VMLINUX_SYMBOL_STR(dccp_sync_mss) },
	{ 0x3e0edeb0, __VMLINUX_SYMBOL_STR(inet_accept) },
	{ 0x28f30109, __VMLINUX_SYMBOL_STR(inet_csk_reqsk_queue_drop_and_put) },
	{ 0x5118c382, __VMLINUX_SYMBOL_STR(secure_dccp_sequence_number) },
	{ 0x974b0281, __VMLINUX_SYMBOL_STR(inet_ioctl) },
	{ 0x912b714f, __VMLINUX_SYMBOL_STR(inet_csk_get_port) },
	{ 0x4e2d4d99, __VMLINUX_SYMBOL_STR(dccp_death_row) },
	{ 0xf8773807, __VMLINUX_SYMBOL_STR(inet_ctl_sock_create) },
	{ 0xa650bc11, __VMLINUX_SYMBOL_STR(dccp_poll) },
	{ 0xeab98c2f, __VMLINUX_SYMBOL_STR(inet_hash) },
	{ 0x6af4f237, __VMLINUX_SYMBOL_STR(proto_register) },
	{ 0x22610aef, __VMLINUX_SYMBOL_STR(dccp_disconnect) },
	{ 0xd957e7aa, __VMLINUX_SYMBOL_STR(__sk_dst_check) },
	{ 0x64eb65a8, __VMLINUX_SYMBOL_STR(inet_release) },
	{ 0x9de95db3, __VMLINUX_SYMBOL_STR(dccp_done) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x85207649, __VMLINUX_SYMBOL_STR(inet_reqsk_alloc) },
	{ 0xaa7ada3e, __VMLINUX_SYMBOL_STR(kfree_skb) },
	{ 0x7e2c2962, __VMLINUX_SYMBOL_STR(proto_unregister) },
	{ 0x5b1f3aa0, __VMLINUX_SYMBOL_STR(inet_stream_connect) },
	{ 0x357bca35, __VMLINUX_SYMBOL_STR(inet_getname) },
	{ 0xcc857a37, __VMLINUX_SYMBOL_STR(inet_ehash_nolisten) },
	{ 0x34b50929, __VMLINUX_SYMBOL_STR(register_pernet_subsys) },
	{ 0x5ad9591e, __VMLINUX_SYMBOL_STR(inet_csk_bind_conflict) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0x4cdd391d, __VMLINUX_SYMBOL_STR(dccp_feat_list_purge) },
	{ 0xe259ae9e, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0xbd7fa83f, __VMLINUX_SYMBOL_STR(compat_ip_setsockopt) },
	{ 0xac859661, __VMLINUX_SYMBOL_STR(sk_receive_skb) },
	{ 0x3e34c034, __VMLINUX_SYMBOL_STR(inet_csk_reqsk_queue_hash_add) },
	{ 0x2a18c74, __VMLINUX_SYMBOL_STR(nf_conntrack_destroy) },
	{ 0x87d5c5d9, __VMLINUX_SYMBOL_STR(compat_dccp_getsockopt) },
	{ 0xd3c2b3d0, __VMLINUX_SYMBOL_STR(ip_route_output_flow) },
	{ 0xf6ebc03b, __VMLINUX_SYMBOL_STR(net_ratelimit) },
	{ 0x8f5e27aa, __VMLINUX_SYMBOL_STR(sock_common_setsockopt) },
	{ 0x41adf462, __VMLINUX_SYMBOL_STR(__xfrm_policy_check) },
	{ 0xc1796d4a, __VMLINUX_SYMBOL_STR(inet_register_protosw) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x61a80b09, __VMLINUX_SYMBOL_STR(inet_dccp_listen) },
	{ 0xd7e961c2, __VMLINUX_SYMBOL_STR(__inet_inherit_port) },
	{ 0xc08b94c0, __VMLINUX_SYMBOL_STR(inet_bind) },
	{ 0xff81a72a, __VMLINUX_SYMBOL_STR(sock_common_getsockopt) },
	{ 0x86be7924, __VMLINUX_SYMBOL_STR(dccp_packet_name) },
	{ 0x100fd53f, __VMLINUX_SYMBOL_STR(inet_csk_accept) },
	{ 0xe5173623, __VMLINUX_SYMBOL_STR(__inet_lookup_listener) },
	{ 0x7c39059a, __VMLINUX_SYMBOL_STR(dccp_reqsk_send_ack) },
	{ 0xed48e632, __VMLINUX_SYMBOL_STR(dccp_rcv_state_process) },
	{ 0x3c6a715, __VMLINUX_SYMBOL_STR(dccp_connect) },
	{ 0xcbc1b41f, __VMLINUX_SYMBOL_STR(dccp_shutdown) },
	{ 0x8d522714, __VMLINUX_SYMBOL_STR(__rcu_read_lock) },
	{ 0xe41c1ce7, __VMLINUX_SYMBOL_STR(ip_queue_xmit) },
	{ 0xcbf395c7, __VMLINUX_SYMBOL_STR(inet_unregister_protosw) },
	{ 0xbc69b555, __VMLINUX_SYMBOL_STR(inet_csk_addr2sockaddr) },
	{ 0x37876d78, __VMLINUX_SYMBOL_STR(__inet_lookup_established) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=dccp";

